### ISSUE TITLE
proxies.txt file thing 

### ISSUE THREAD

**Issue by froy1337** [BeepIsla/csgo-commend-bot#167]
how do we do a tutorial about the proxy video picture or something I do not understand if you can understand if anyone can help or remove the proxy can not

**Comment by BeepFelix** [comment]
The [README](../blob/master/README.md#proxies) tells you everything you need to know and even includes 2 examples.

1. Get a list of HTTP proxies
2. Create a file called `proxies.txt`
3. Add all of your proxies in that file, one proxy per line
4. Enable proxies in your config by setting `proxy` > `enabled` to `true`

**Comment by froy1337** [comment]
i don't want to use proxy ' if I change it as wrong is disabled?

**Comment by BeepFelix** [comment]
Set `enabled` to `false`

**Comment by reloaded175** [comment]
It shows as timedout for me.
I checked the proxies already they are working.

PS C:\Users\****\Desktop\csgo-commend-bot> node index.js
 Checking for new update...
 Up to date!
 Checking protobufs...
 Found protobufs
 Loading proxies...
 Got 39 proxies
 Opening database...
 There are a total of 2129 operational accounts
 Getting an available server
 Logging into target account
{
  name: 'Error',
  message: 'GC connection timeout',
  stack: 'Error: GC connection timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\****\\Desktop\\csgo-commend-bot\\helpers\\GameCoordinator.js:71:12)\n' +
    '    at listOnTimeout (internal/timers.js:531:17)\n' +
    '    at processTimers (internal/timers.js:475:7)'
node version:v12.7.0

**Comment by BeepFelix** [comment]
Your proxies might be too slow.

**Comment by reloaded175** [comment]
The proxy has 170ms timeout.

**Comment by BeepFelix** [comment]
Nice, I don't know what the cause of this could be. Just try again.

**Comment by UnbreakCode** [comment]
GC Connection Timeout with Proxies means that the Proxy has been banned from steam/can't reach steam or doesn't work because it's a socks4/5 proxy

**Comment by reloaded175** [comment]
I encountered same error even when I set proxy enabled as false. Whereas the previous version of commend bot works fine.

**Comment by UnbreakCode** [comment]
Well I tested the Proxy Support now multiple times and can tell you that it's working fine
