### ISSUE TITLE
Error: InvalidPassword

### ISSUE THREAD

**Issue by ErykApps** [BeepIsla/csgo-commend-bot#170]
How I can Fix this ?

https://i.imgur.com/1q1olt6.png

**Comment by BeepFelix** [comment]
Read the error, it clearly says the password is invalid. *Also your version is out of date.*

**Comment by ErykApps** [comment]
I have the same error on the latest version

**Comment by BeepFelix** [comment]
Read the error, read when it happens.

The script tries to log into the fetcher account, and then errors because the password is invalid. So what you have to do is fix your fetcher account in your config.
