### ISSUE TITLE
Report its working but its bugged?

### ISSUE THREAD

**Issue by Falghere** [BeepIsla/csgo-commend-bot#172]
![image](https://user-images.githubusercontent.com/16209066/70397125-4b08cc00-19ee-11ea-9816-cafec62327d6.png)

I was testing to see the report bot is really working, but it seems not, it sends the report's but it seems not working ...

When you report through the script it doesn't specify what was reported on steam, but says it was reported (I don't know how it is possible)

When you report manually it shows exactly what you reported

///////////////
Where can I find good HTTP proxies to use? because all I found to fail "Failed to login and due to proxy timeout"

**Comment by BeepFelix** [comment]
I will look into this.

---

> Where can I find good HTTP proxies to use? because all I found to fail "Failed to login and due to proxy timeout"

This is something I can't answer.

**Comment by sherlockparadox** [comment]
Hi Falghere, did you find any good proxies to use? Also, is there any limit to the number of commends we can send on 1 server?
I saw that some guy was able to send commends on competitive matchmaking server, is that a functionality we have as well? 
Thanks and cheers!

**Comment by BeepFelix** [comment]
> Hi Falghere, did you find any good proxies to use? Also, is there any limit to the number of commends we can send on 1 server?
> I saw that some guy was able to send commends on competitive matchmaking server, is that a functionality we have as well?
> Thanks and cheers!

This is offtopic and not related to this issue. Please keep things related to the issue.

---

You should be able to commend/report on competitive servers. Though you have to get the server ID and match ID manually as currently `auto` doesn't have the functionality to do this.

**Comment by BeepFelix** [comment]
I have found the issue and I am working on a fix.

At the moment you aren't even reporting.

**Comment by BeepFelix** [comment]
Fixed in 14bb7b3f82e39a4709743bf436df21fbeaeb7b47, please update and report back.

**Comment by ypc123** [comment]
@Falghere how do you look at the accounts reported?

**Comment by BeepFelix** [comment]
> @Falghere how do you look at the accounts reported?

You can do so [here](https://steamcommunity.com/my/gcpd/730/?tab=playerreports).

**Comment by xSuspect** [comment]
> I will look into this tomorrow.

will you make a version?

**Comment by BeepIsla** [comment]
> > I will look into this tomorrow.
> 
> will you make a version?

What do you mean? The fix has already been published and a new version (`2.4.1`) has been pushed.

**Comment by xSuspect** [comment]
thanks now I noticed and where what place should the file be placed (.txt) proxy ?

**Comment by BeepIsla** [comment]
Main directory (Same as `index.js`, `config.json`, etc)

**Comment by xSuspect** [comment]
how can I report, and what commands should be used:ex
node index ? https://prnt.sc/q8kigc
https://prnt.sc/q8kitz

**Comment by BeepIsla** [comment]
> how can I report, and what commands should be used:ex
> node index ? https://prnt.sc/q8kigc
> https://prnt.sc/q8kitz
> and there question:
> if I report during the game does it work better?

1. This is offtopic for this issue, please create your [own issue](https://github.com/BeepIsla/csgo-commend-bot/issues/new/choose).
2. You need a server ID.
