### ISSUE TITLE
unknow response

### ISSUE THREAD

**Issue by xShany** [BeepIsla/csgo-commend-bot#174]
**Detailed bug description**
Tried to commend bot someone, after it found the server it returned a  { response: {} }

**Error**
```
https://i.imgur.com/GfwJBei.png
```

**Config**
```
Your "config.json" - Censor your API Key and account details

https://i.imgur.com/tgLMnB6.png

**Comment by BeepIsla** [comment]
Fixed in f557366f40bfa43365d9cf52025388e2e0b6531f
