### ISSUE TITLE
Error: AccountDisabled

### ISSUE THREAD

**Issue by FPSGuilherme** [BeepIsla/csgo-commend-bot#177]
I have some accounts that were created some time ago, and steam has blocked some accounts

In removing mode all accounts that do not work could remove those that are blocked by steam

https://prnt.sc/qaex73

**Comment by BeepIsla** [comment]
There is no reason to remove not working accounts, they don't get used anways.

**Comment by FPSGuilherme** [comment]
so can this account still work? because I'm already trying for 3 days with them and is giving this error message always

**Comment by BeepIsla** [comment]
If the account is disabled by Steam how do you expect it to work? If the script detects an account is not working it will mark it as such and never use the account again so the error should only ever appear once.
