### ISSUE TITLE
Proxies

### ISSUE THREAD

**Issue by dwnhauhdwnuhd** [BeepIsla/csgo-commend-bot#182]
So ive got this bug with proxies. I have 5300 Proxies from purves.cc, I tried using them but i just get "[ACCOUNT] Failed to login due to proxy timeout (20/20) { name: 'Error',
message: 'Failed to log in withing given 60000ms',

I have a text document names proxies.txt with all my proxies on one line each.

**Comment by xSuspect** [comment]
1. Proxy is "blocked by Steam". they are not paid(free)  purves.cc=any free proxy site
2.the response time is too high(60000ms) or proxy are dead
