### ISSUE TITLE
Plain text in Proxy.txt got only 1 proxy

### ISSUE THREAD

**Issue by ccsimplyspolit** [BeepIsla/csgo-commend-bot#183]
Plain text of proxy.txt example:

127.0.0.1:12345
127.0.0.1:67890
127.0.0.2:12345
127.0.0.2:67890

But i got only 1 proxy.
if i use json format & extension of file .json all works good.

**Comment by BeepIsla** [comment]
Works perfectly fine for me, I assume the `proxy` > `file` key in your `config.json` is set to the correct file name?

There isn't a lot of information to help with. You may have to screenshot exactly how your `proxy.txt` looks like.
