### ISSUE TITLE
Invalid Password

### ISSUE THREAD

**Issue by R3ALF4KT** [BeepIsla/csgo-commend-bot#184]
**Invalid Password**
I cant commend myself because it says invalid password. Even though the Database said every account is working. And i tested it myself (accounts are working).

**Error: InvalidPassword**
```
https://cdn.discordapp.com/attachments/660426098060034068/660426234144227328/8aa1be9404c9069834140856e8854b5e.png
```

**Config**
```
{
	"commend": {
		"friendly": 1,
		"teaching": 1,
		"leader": 1
	},
	"report": {
		"aimbot": 0,
		"wallhack": 0,
		"speedhack": 0,
		"teamharm": 0,
		"textabuse": 0,
		"voiceabuse": 0
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"fetcher": {
		"username": "PrimeAccount",
		"password": "PrimePassword",
		"sharedSecret": "",
		"maxTries": 10,
		"tryDelay": 2500,
		"askSteamGuard": false
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "CENSORED",
	"serverID": "auto",
	"matchID": "0",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"steamWebAPIKey": "CENSORED"
}

```

**Version**
- NodeJS: v13.1.0
- Script version: "version": "2.4.5"

**Additional information**
Maybe its because it wasn't my server, it was from someone else (public).
![8aa1be9404c9069834140856e8854b5e](https://user-images.githubusercontent.com/59320846/71549747-d6a8c380-29c2-11ea-8d19-39f891bd56ee.png)

**Comment by BeepIsla** [comment]
Read the README, using `AUTO` will require a fetcher account.
