### ISSUE TITLE
Response Error

### ISSUE THREAD

**Issue by orcnaydn** [BeepIsla/csgo-commend-bot#185]
ı typed status my console this:
version : 1.37.3.5/13735 1043/7712 secure  [A:1:8769546:13858] 
I copy [A:1:8769546:13858] this and paste my server id and when i start bot they give this error:
 Checking protobufs...
 Found protobufs
 Opening database...
 There are a total of 778 operational accounts
 Parsing target account...
 Chunking 1 account into groups of 20...
 Parsing server input
 Parsed server input to 90131512212967434
 { response: {} }

What can i do for fix this?

**Comment by BeepIsla** [comment]
What type of server was this? Self hosted? Dedicated server? Valve server?

**Comment by orcnaydn** [comment]
Workshop map

**Comment by BeepIsla** [comment]
Use a real server, not a localhost one.

**Comment by orcnaydn** [comment]
I saw someone he can sending commends in someones in a workshop map how can he do that?

**Comment by BeepIsla** [comment]
What version are you using? Are you not up-to-date?

**Comment by orcnaydn** [comment]
I updated now but still same error.

**Comment by BeepIsla** [comment]
What is your config?

**Comment by orcnaydn** [comment]
{
	"commend": {
		"friendly": 1,
		"teaching": 1,
		"leader": 1
	},
	"report": {
		"aimbot": 10,
		"wallhack": 10,
		"speedhack": 10,
		"teamharm": 10,
		"textabuse": 10,
		"voiceabuse": 10
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"fetcher": {
		"username": "PrimeAccount",
		"password": "PrimePassword",
		"sharedSecret": "",
		"maxTries": 10,
		"tryDelay": 2500,
		"askSteamGuard": true
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/id/orcnaydn/",
	"serverID": "[A:1:8769546:13858]",
	"matchID": "0",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"steamWebAPIKey": "XXXXXXXXXXXXXXXXX"
}

**Comment by BeepIsla** [comment]
The server could not be found as online server and therefore cannot be used by the script. That's really all I can say, unless the server shows on the community server list it can't be used to my knowledge.

You could simply try opening the `index.js` in Notepad++ and comment out the lines 358-371. So it looks something like this:
```js
}

// let info = await helper.getServerInfo(serverToUse).catch((err) => {
// 	console.log("red", err.message === "Invalid Server" ? "Server is no longer available" : err);
// });
// if (!info) {
// 	if (targetAcc instanceof Target) {
// 		targetAcc.logOff();
// 	}
// 
// 	await db.close();
// 
// 	// Force exit the process if it doesn't happen automatically within 15 seconds
// 	setTimeout(process.exit, 15000, 1).unref();
// 	return;
// }

for (let i = 0; i < chunks.length; i++) {
```

then try again and tell me if it works or not

**Comment by orcnaydn** [comment]
Yeesss!! Worked tysm, i want to ask one more question personal u have discord or something?

**Comment by BeepIsla** [comment]
My Discord is on my [Github profile](https://github.com/BeepIsla).
