### ISSUE TITLE
Proxy error

### ISSUE THREAD

**Issue by Velortex** [BeepIsla/csgo-commend-bot#187]
If i start 30 commends with 2 proxys only 20 commend can be send

LOG:
https://i.imgur.com/xorS7K6.png
https://i.imgur.com/ml74z9a.png
https://i.imgur.com/SCftHBC.png

**Config**
```
{
	"commend": {
		"friendly": 30,
		"teaching": 30,
		"leader": 30
	},
	"report": {
		"aimbot": 10,
		"wallhack": 10,
		"speedhack": 10,
		"teamharm": 10,
		"textabuse": 10,
		"voiceabuse": 10
	},
	"account": {
		"username": "XXX",
		"password": "XXX",
		"sharedSecret": ""
	},
	"fetcher": {
		"username": "XXX",
		"password": "XXX",
		"sharedSecret": "",
		"maxTries": 10,
		"tryDelay": 2500,
		"askSteamGuard": true
	},
	"proxy": {
		"enabled": true,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 15
	},
	"type": "COMMEND",
	"method": "LOGIN",
	"target": "XXX",
	"serverID": "XXX",
	"matchID": "0",
	"perChunk": 15,
	"betweenChunks": 5000,
	"cooldown": 28800000,
	"steamWebAPIKey": "XXX"
}

```

**Version**
- NodeJS: v10.15.2
- Script version: 2.4.5

**Comment by Velortex** [comment]
Im dumb i find out that the target has the limit usless issue i close it

**Comment by BeepIsla** [comment]
To my knowledge each IP can do 20 commends per 5 minutes. The limit is within the IP the commends come from and not within the target.

**Comment by 45656456kawai** [comment]
Sorry for hijacking the post but I really wanted to know if there's any way to use free proxies  : o I tried so many and all I got was timed out : (

**Comment by BeepIsla** [comment]
> Sorry for hijacking the post but I really wanted to know if there's any way to use free proxies : o I tried so many and all I got was timed out : (

Find proxies which haven't been blocked by Steam yet but you will likely never find any free ones which will work. Even **a lot** of paid ones are blocked.

**Comment by Velortex** [comment]
> To my knowledge each IP can do 20 commends per 5 minutes. The limit is within the IP the commends come from and not within the target. This could be related to using LOGIN method but I doubt it.
> 
> I am unsure what the problem here is.

i will try it with SERVER methode
