### ISSUE TITLE
Process timeout

### ISSUE THREAD

**Issue by bruteforcehacker** [BeepIsla/csgo-commend-bot#188]
**Detailed bug description**

  name: 'Error',
  message: 'GC connection timeout',
  stack: 'Error: GC connection timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\xxxxx\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:86:12)\n' +
    '    at listOnTimeout (internal/timers.js:531:17)\n' +
    '    at processTimers (internal/timers.js:475:7)'
```
A full error log or screenshot.
```

**Config**
```
Your "config.json" - Censor your API Key and account details
 {
	"commend": {
		"friendly": 100,
		"teaching": 100,
		"leader": 100
	},
	"report": {
		"aimbot": 10,
		"wallhack": 10,
		"speedhack": 10,
		"teamharm": 10,
		"textabuse": 10,
		"voiceabuse": 10
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"fetcher": {
		"username": "XXXXX",
		"password": "XXXXXX",
		"sharedSecret": "",
		"maxTries": 10,
		"tryDelay": 2500,
		"askSteamGuard": true
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "Login",
	"target": "XXXXXXX",
	"serverID": "auto",
	"matchID": "auto",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"steamWebAPIKey": "XXXXXXX"
}


**Version**
Latest

**Additional information**
Add any other potentially useful information about your issue here.

**Comment by BeepIsla** [comment]
Trying to use LOGIN method without an account in the `account` section?

**Comment by Siezek1** [comment]
Same

**Comment by Siezek1** [comment]
![Przechwytywanie](https://user-images.githubusercontent.com/40297405/71592136-581d6480-2b2f-11ea-829a-4a6f19b4189b.PNG) My config

**Comment by BeepIsla** [comment]
You have just shown your API key to everyone. This can be used to scam you. Delete it and regenerate it [here](https://steamcommunity.com/dev/apikey).

---

Again same with you, `LOGIN` method without having an account filled in. This does not work. Use your brain, `LOGIN` method **logs into the account** so you have to provide username and password.

**Comment by Siezek1** [comment]
So how do I make the commend bot work on casual?

**Comment by BeepIsla** [comment]
Read the README, its simple.

Use the `SERVER` method and either fill in `serverID` and `matchID` manually or create a bot account and fill it in as `fetcher` account, then use `auto` for `serverID` & `matchID`.

**Comment by Siezek1** [comment]
I am sorry but I am learning English and I use google translator in 99% and he does not translate well and understand it a bit ;/

**Comment by Siezek1** [comment]
Where is matchID? But I cannot find

**Comment by BeepIsla** [comment]
> I am sorry but I am learning English and I use google translator in 99% and he does not translate well and understand it a bit ;/

Then learn English or ask someone who knows it. English is the [World Language](https://wikipedia.org/wiki/World_language), everyone should know it.

> Where is matchID? But I cannot find

Just use `"0"` if you use commend bot.

**Comment by Siezek1** [comment]
Not work ;/

**Comment by BeepIsla** [comment]
Open your own issue [here](https://github.com/BeepIsla/csgo-commend-bot/issues/new/choose). Don't hijack one of someone else.
