### ISSUE TITLE
Bot not work

### ISSUE THREAD

**Issue by Siezek1** [BeepIsla/csgo-commend-bot#189]
My bot does not work on official valve servers

**Config**
![Przechwytywanie](https://user-images.githubusercontent.com/40297405/71592964-67ea7800-2b32-11ea-97dc-1523d8c5cb5d.PNG)

**Version**
- NodeJS: `latest` 
- Script version: `latest`

**Comment by BeepIsla** [comment]
Your server ID is wrong.

Look at the example on the README:

- Community Server: `1.37.0.1/13701 934/7508 secure [A:1:1297634312:12708]` > `[A:1:1297634312:12708]`
- Valve Server: `Connected to =[A:1:3849827331:12657]:0` > `[A:1:3849827331:12657]`

**Comment by Siezek1** [comment]
Thanks MAN! Its work!
