### ISSUE TITLE
SteamAPIkey Problem (i think)

### ISSUE THREAD

**Issue by Puch1x** [BeepIsla/csgo-commend-bot#191]
This error comes up when i try to run the index file, can someone tell me whats the problem here and how i can solve it please? thanks

![image](https://user-images.githubusercontent.com/59456258/71697041-0129c080-2db7-11ea-881d-5503dd664a05.png)

**Comment by BeepIsla** [comment]
Did you ever think about following the README?

**Comment by Puch1x** [comment]
I read it many times but it seems like i overread it, sorry. Thanks for the very quick help!
