### ISSUE TITLE
proxy problem

### ISSUE THREAD

**Issue by shortguy123** [BeepIsla/csgo-commend-bot#192]
"TypeError: Cannot read property 'switchProxyEveryXaccounts' of undefined
    at C:\Users\Jyoti\Desktop\csgo-commend-bot-master\index.js:246:35 Promise {
  <rejected> TypeError: Cannot read property 'switchProxyEveryXaccounts' of undefined
      at C:\Users\Jyoti\Desktop\csgo-commend-bot-master\index.js:246:35" 

error coming in powershell i never used proxies till now but after updating the bot there are some problems now

**Comment by BeepIsla** [comment]
Whats your config
