### ISSUE TITLE
Failed to log in within given 60000ms

### ISSUE THREAD

**Issue by nk260203** [BeepIsla/csgo-commend-bot#193]
Failed to log in within given 60000ms

![Sem títulaaao](https://user-images.githubusercontent.com/48919928/71732721-be073600-2e26-11ea-8e64-dc3a5301ea7e.png)

![Sem taaaítulo](https://user-images.githubusercontent.com/48919928/71732806-eee76b00-2e26-11ea-9f5e-bf45fc4faf81.png)

- NodeJS: v12.9.1
- Script version: 2.4.5

This error message appears on almost every commend I try to send.

**Comment by BeepIsla** [comment]
Are the bot accounts VAC/Game banned?

**Comment by nk260203** [comment]
No

**Comment by BeepIsla** [comment]
Then I don't really know, has this always happened or does it only recently happen?

**Comment by nk260203** [comment]
always happened, there is this other error too, the error message is very similar
![Sem títulaaaaaaaaaaaaao](https://user-images.githubusercontent.com/48919928/71733982-982f6080-2e29-11ea-9c8e-ca92d30513e8.png)

**Comment by BeepIsla** [comment]
Those two errors are something completely different, one fails to send the commend the other one fails to connect to CSGO.

**Comment by nk260203** [comment]
Do you think there is anything I can do to solve the first mistake?

**Comment by BeepIsla** [comment]
There must be something wrong with the account, for some reason it cannot connect to CSGO servers, and I don't know why. Try logging into the account manually on Steam and see if everything works fine.

**Comment by nk260203** [comment]
I opened csgo in one of the accounts that gave the first error and was able to initiate a normal deathmath on the valve.

**Comment by BeepIsla** [comment]
Weird, I don't know what the cause of this could be. Are the accounts created from China/Are you from China?

**Comment by nk260203** [comment]
I don't know if the accounts are created in china, but it is possible that I am from Brazil

**Comment by nk260203** [comment]
I don't know if the accounts are created in China, but it's possible, I'm from Brazil

**Comment by BeepIsla** [comment]
I sadly don't know what the cause of this could be.

**Comment by UnbreakCode** [comment]
Timeout could come from an IP-Ban. Ever tried proxies?

**Comment by BeepIsla** [comment]
No reply in a very long time and there have been major changes on Valves side and on the commend bot itself. If the issue continues please reopen.
