### ISSUE TITLE
Proxys

### ISSUE THREAD

**Issue by KarateOgd** [BeepIsla/csgo-commend-bot#194]
I Hv a proxy list, but i don't know where to put them
wait reply

**Comment by BeepIsla** [comment]
Have you tried reading the Proxy section of the [README](https://github.com/BeepIsla/csgo-commend-bot#proxies)

**Comment by KarateOgd** [comment]
Ok, I read, but I create a .json file named proxies and there I write proxies?

**Comment by BeepIsla** [comment]
Call it whatever you want, put your proxies inside of it, one per line (or as array), put the name of your file in the config at the right place under the `proxy` section, done.

**Comment by KarateOgd** [comment]
![image](https://user-images.githubusercontent.com/56985029/71756297-cf276580-2e6d-11ea-9d88-384bf45137e7.png)
proxy section???

**Comment by BeepIsla** [comment]
proxy section in your config

**Comment by KarateOgd** [comment]
![image](https://user-images.githubusercontent.com/56985029/71756343-0433b800-2e6e-11ea-819b-c565f7bc3719.png)
I put a .txt file with that name in the folder, and config already detects it as a proxy?

**Comment by BeepIsla** [comment]
Yes

**Comment by KarateOgd** [comment]
Ok, thx y felix, i have create a interface for y system, dm me in discord and i invite for y 𝐊𝐚𝐫𝐚𝐭𝐞 𝐨𝐠#4610
![image](https://user-images.githubusercontent.com/56985029/71756399-65f42200-2e6e-11ea-9770-6b4c93c56035.png)

**Comment by BeepIsla** [comment]
No thanks, don't need it/want it/care for it.

My Discord is always on the left side of my Github profile.

**Comment by KarateOgd** [comment]
good service and speed
