### ISSUE TITLE
Proxie Authentication / Timeout

### ISSUE THREAD

**Issue by Vejas04** [BeepIsla/csgo-commend-bot#195]
Hello,
so this is my Issue.
I have Proxies but they need to be Authenticated but how i do that?
I can do a IP Authentication and a Name:Password one. But both dont work...

[17cclark] Failed to login and due to proxy timeout (1/20) {
  name: 'Error',
  message: 'HTTP CONNECT 407 Proxy Authentication Required',
  stack: 'Error: HTTP CONNECT 407 Proxy Authentication Required\n' +
    '    at ClientRequest.<anonymous> (C:\\Users\\NICKUS\\Desktop\\GLOBAL\\node_modules\\steam-user\\components\\connection_protocols\\tcp.js:59:29)\n' +
    '    at ClientRequest.emit (events.js:209:13)\n' +
    '    at Socket.socketOnData (_http_client.js:490:11)\n' +
    '    at Socket.emit (events.js:209:13)\n' +
    '    at addChunk (_stream_readable.js:305:12)\n' +
    '    at readableAddChunk (_stream_readable.js:286:11)\n' +
    '    at Socket.Readable.push (_stream_readable.js:220:10)\n' +
    '    at TCP.onStreamRead (internal/stream_base_commons.js:182:23)'

(IP-Authentication)

 [0cptsem0] Failed to login and due to proxy timeout (15/20) {
  name: 'Error',
  message: 'HTTP CONNECT 429 Too Many Requests',
  stack: 'Error: HTTP CONNECT 429 Too Many Requests\n' +
    '    at ClientRequest.<anonymous> (C:\\Users\\NICKUS\\Desktop\\GLOBAL\\node_modules\\steam-user\\components\\connection_protocols\\tcp.js:59:29)\n' +
    '    at ClientRequest.emit (events.js:209:13)\n' +
    '    at Socket.socketOnData (_http_client.js:490:11)\n' +
    '    at Socket.emit (events.js:209:13)\n' +
    '    at addChunk (_stream_readable.js:305:12)\n' +
    '    at readableAddChunk (_stream_readable.js:286:11)\n' +
    '    at Socket.Readable.push (_stream_readable.js:220:10)\n' +
    '    at TCP.onStreamRead (internal/stream_base_commons.js:182:23)'

(Name:Password Authentication)

Greetings
Vejas

**Comment by BeepIsla** [comment]
Example proxy with authentification `http://username:password@127.0.0.1:8181`

**Comment by Vejas04** [comment]
Okay i wrote it now like that but now i get another error message:

[Bsharky28] Failed to login and due to proxy timeout (16/20) {
  name: 'Error',
  message: 'Proxy connection timed out',
  stack: 'Error: Proxy connection timed out\n' +
    '    at ClientRequest.<anonymous> (C:\\Users\\NICKUS\\Desktop\\GLOBAL\\node_modules\\steam-user\\components\\connection_protocols\\tcp.js:69:28)\n' +
    '    at ClientRequest.emit (events.js:209:13)\n' +
    '    at Socket.emitRequestTimeout (_http_client.js:690:9)\n' +
    '    at Object.onceWrapper (events.js:298:28)\n' +
    '    at Socket.emit (events.js:209:13)\n' +
    '    at Socket._onTimeout (net.js:468:8)\n' +
    '    at listOnTimeout (internal/timers.js:531:17)\n' +
    '    at processTimers (internal/timers.js:475:7)'

Some of those worked but like only 1 did successfully sent a commend.

**Comment by BeepIsla** [comment]
Well I would say your proxies are banned from Steam.
