### ISSUE TITLE
I can't delete commends.

### ISSUE THREAD

**Issue by sachi55** [BeepIsla/csgo-commend-bot#196]
**Detailed bug description**
When i tried to delete some commends it says something like that.

**Error**
```
http://prntscr.com/qjed1x
```

**Config**
```
{
	"commend": {
		"friendly": 47,		
		"teaching": 47,
		"leader": 47	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"fetcher": {
		"username": "PrimeAccount",
		"password": "PrimePassword",
		"sharedSecret": "",
		"maxTries": 10,
		"tryDelay": 2500,
		"askSteamGuard": true
	},
	"method": "SERVER",
	"target": "",
	"serverID": "45.10.56.87:27015",
	"matchID": "0",
	"perChunk": 20,
	"betweenChunks": 600000,
	"cooldown": 100500,
	"steamWebAPIKey": ""
}

```

**Version**
- NodeJS: `v12.10.0
- Script version: `2.2.5`

**Comment by BeepIsla** [comment]
You cannot delete commends, only clear out the database so it forgets which bot has already commended who. **Be aware of this, it will likely cause issues in the future and you should normally never have to use this functionality.**

With that out of the way, try using the SteamID64.

**Comment by sachi55** [comment]
Uh, ok. Thanks for fast reply!
