### ISSUE TITLE
Problem with getting recommends

### ISSUE THREAD

**Issue by Siezek1** [BeepIsla/csgo-commend-bot#197]
Hello
I have a problem with recommends. I kind of get recommendations, but I do not get them, that is, the bot gives me praise, it is written on the chat that I got praise, but on the profile in csgo there is the same number of praises all the time. What's the problem?

Picture: 
![2](https://user-images.githubusercontent.com/40297405/71783610-6c5ad900-2fe9-11ea-8bef-f3556ae6f013.png)

Config: 
![Bez tytułu](https://user-images.githubusercontent.com/40297405/71783623-adeb8400-2fe9-11ea-8a14-f0264eb69acc.png)

**Comment by GoliasEd** [comment]
Happens to me too

**Comment by BeepIsla** [comment]
Duplicate #119
