### ISSUE TITLE
just a suggestion

### ISSUE THREAD

**Issue by HyperArda** [BeepIsla/csgo-commend-bot#198]
everything is good on commend bot but if i use a account to so much i getting already connected error code 2.  
![Screenshot_26](https://user-images.githubusercontent.com/48220802/71894564-48b5a100-3157-11ea-806a-99d533affd44.png)

If you add a checkerfor this error, Bot is be better.

**Comment by BeepIsla** [comment]
Error 2 means you already commended the target, it should never happen unless you deleted something out of your accounts.sqlite.

If you use the default cooldown of 8 hours this error should also never happen.

**Comment by HyperArda** [comment]
Okey. Thank you. I make miss click and remove some zero from cooldown.
