### ISSUE TITLE
command bot config

### ISSUE THREAD

**Issue by mrflt** [BeepIsla/csgo-commend-bot#199]
please send me defeult config file with proxy and when i set to proxies where i can see the proxies is true and work?

**Comment by BeepIsla** [comment]
Default `config.json` is provided, proxy help is in the README.

**Comment by mrflt** [comment]
i know but i cant set this and type true lines...please send the demo of proxy config type...

**Comment by BeepIsla** [comment]
If you cannot understand what is written in the README then you have other problems. It tells you **exactly** what to do, which is: Create a file, put in your proxies, one proxy per line like in the example in the README, put in the name of the file in your config under `proxy.file` and you're done.

**Comment by mrflt** [comment]
},
	"proxy": {
		"enabled": true,
		"file": "proxi.txt",
		"switchProxyEveryXaccounts": 20
        }.
is this ture?

**Comment by BeepIsla** [comment]
Why don't you just try it out and come back if it doesn't work?

**Comment by mrflt** [comment]
i try this but i get timeout in commands...without any errors of proxies

**Comment by BeepIsla** [comment]
Show the error.
