### ISSUE TITLE
fetcher account

### ISSUE THREAD

**Issue by fiskerface** [BeepIsla/csgo-commend-bot#200]
Hello,

first of all nice work :)

it were too nice if u could update ur script to a graphical user interface (GUI) where we could adjust the config settings fetcherACC / serverID / matchID / steamprofile(target) / report/commend-button

my question is if I would use a fetcher acc, can I use this fetcher acc to report/commend too?

thx

**Comment by BeepIsla** [comment]
>it were too nice if u could update ur script to a graphical user interface (GUI) where we could adjust the config settings fetcherACC / serverID / matchID / steamprofile(target) / report/commend-button

no

>my question is if I would use a fetcher acc, can I use this fetcher acc to report/commend too?

no
