### ISSUE TITLE
i cant login

### ISSUE THREAD

**Issue by mrflt** [BeepIsla/csgo-commend-bot#201]
im download new version of command bot and my accounts in new version cant login and i get this error: 
Failed to login and has been marked as invalid (20/20) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read',
  name: 'Error',
  message: 'read ECONNRESET',
  stack: 'Error: read ECONNRESET\n' +
    '    at TCP.onStreamRead (internal/stream_base_commons.js:201:27)'

please help me

**Comment by BeepIsla** [comment]
Do you use proxies?

**Comment by mrflt** [comment]
yes im use proxies...my accounts is worked in older version of program but in new program....

**Comment by BeepIsla** [comment]
Get better proxies.

**Comment by mrflt** [comment]
im checked proxies with steam proxy checker all of them is worked and good!

**Comment by BeepIsla** [comment]
As you can see, they don't work.

**Comment by mrflt** [comment]
this message for proxies?

**Comment by BeepIsla** [comment]
Yes, your proxies don't work. Just going to the Steam website with a proxy is no problem **but** logging in with a proxy is hard, almost all proxies are blocked.

**Comment by mrflt** [comment]
where i can good proxies?? please help me...

**Comment by BeepIsla** [comment]
Search for residential proxies, they will cost a lot but will maybe work. I can't help with this further because I don't use proxies myself.

**Comment by mrflt** [comment]
so how u send commands??? without proxies??? your ip is not block?

**Comment by BeepIsla** [comment]
I don't commend bot people anymore. If I do 20 per 5 minutes that's it.

**Comment by mrflt** [comment]
ok sir thankyou for help <3
