### ISSUE TITLE
Failed to commend

### ISSUE THREAD

**Issue by 45656456kawai** [BeepIsla/csgo-commend-bot#206]
Hi, so I tried LOGIN method and it seems to be having issue Idk if it's just me or not but here's my problem -

With LOGIN method I'm only getting around 40-60 and sometimes even 80 commends successfully and after that, all failing "Failed to commend" despite having different IP/Proxy each chunk (20) with 5-minute delay in between.

With the config except for method SERVER (in official DEATHMATCH), I'm getting way less "Failed to commend" error maybe 2-3 once in every other chunk.

So far I ran both method for over 4 hours and here's the result - 

LOGIN - 75 commends since after that all failed for 4 hours
SERVER - 1000+ and around ~200 failed

**Comment by BeepIsla** [comment]
`LOGIN` method hasn't really been paid attention too at all. I assume the client would have to set their currently active server at an interval every half an hour or so.

I don't have the time to test these things for so long, I will try and come up with a potential reason tomorrow and then try to fix it. Will likely be something like a loop and set server ID on target-account every few minutes.

**Comment by BeepIsla** [comment]
This (c660ed8518a141e561f29e5f50ea9814bfa2f916) *might* fix the problem, maybe not. Needs testing.

**Comment by 45656456kawai** [comment]
testing it now : )

**Comment by 45656456kawai** [comment]
Unfortunately, It acting pretty much the same. After 6 chunks of the 20 all commends failed.

**Comment by BeepIsla** [comment]
Okay then I sadly don't actually know what could cause this problem.

**Comment by reloaded175** [comment]
Joining a different server after 3-4 chunks works for me. Maybe there is a limit on number of Commends on each server.

**Comment by BeepIsla** [comment]
Closing this due to major changes on Valves side and on the commend bot itself. If the issue continues please reopen.
