### ISSUE TITLE
I can't use it

### ISSUE THREAD

**Issue by djkcyl** [BeepIsla/csgo-commend-bot#207]
**Detailed question description**
A clear and concise description of your question.

**Config**
```
{
	"commend": {
		"friendly": 10,
		"teaching": 10,
		"leader": 10
	},
	"report": {
		"aimbot": 10,
		"wallhack": 10,
		"speedhack": 10,
		"teamharm": 10,
		"textabuse": 10,
		"voiceabuse": 10
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"fetcher": {
		"username": "PrimeAccount",
		"password": "PrimePassword",
		"sharedSecret": "",
		"maxTries": 10,
		"tryDelay": 2500,
		"askSteamGuard": true
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",          	
	"target": "https://steamcommunity.com/id/cylcsgo/",
	"serverID": "60.169.75.29:11111",
	"matchID": "0",
	"perChunk": 10,
	"betweenChunks": 200000,
	"cooldown": 28800000,
	"steamWebAPIKey": "0B026350DE19AFB77C7162ABF8469960"
}

```

**Version**
- NodeJS: `v12.14.0` (You can find this using `node -v`)
- Script version: `2.4.6` (You can find this in **your** `package.json` file under `version`)

csgo-commend-bot-master>node index.js
 Checking for new update...
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:201:27) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
} Promise {
  <rejected> Error: read ECONNRESET
      at TLSWrap.onStreamRead (internal/stream_base_commons.js:201:27) {
    errno: 'ECONNRESET',
    code: 'ECONNRESET',
    syscall: 'read'
  }
}

**Comment by BeepIsla** [comment]
Fill out the template. Don't just copy paste an error with no description, no config, no nothing.

**Comment by djkcyl** [comment]
I completed it

**Comment by BeepIsla** [comment]
Does it happen all the time or only sometimes?

**Comment by BeepIsla** [comment]
Also you just showed your API key to everyone, revoke it [here](https://steamcommunity.com/dev/apikey) and generate a new one.

**Comment by djkcyl** [comment]
I cannot use it after using it successfully once

**Comment by BeepIsla** [comment]
The same error happens all the time or a different error?

**Comment by djkcyl** [comment]
Same every time

**Comment by BeepIsla** [comment]
What happens when you go to https://raw.githubusercontent.com/BeepIsla/csgo-commend-bot/master/package.json ? Does it show an error or the expected ` "name": "csgo-commend-bot",` and stuff?

**Comment by djkcyl** [comment]
No errors
![image](https://user-images.githubusercontent.com/59153990/72213389-2772fd00-3529-11ea-9658-8088e90ec5b1.png)


![image](https://user-images.githubusercontent.com/59153990/72213378-07433e00-3529-11ea-8573-37674c6cc6e0.png)

**Comment by djkcyl** [comment]
But I can't connect after I close my vpn

**Comment by BeepIsla** [comment]
Something seems to block the connection to Github, this seems like it has nothing to do with the script itself.

Depending on where you are from maybe your country, internet provider, or something else has blocked Github. You need to unblock it somehow.

**Comment by djkcyl** [comment]
Can i make it run offline

**Comment by BeepIsla** [comment]
Is Steam also blocked or does it work? https://steamcommunity.com/ and https://store.steampowered.com/ ?

**Comment by djkcyl** [comment]
I can connect to the steamstore, but my steamprofile cannot be opened

**Comment by djkcyl** [comment]
I ’m from China. Is it because of GFW?

**Comment by BeepIsla** [comment]
Yes, this is the problem here. There is nothing I can do.

**Comment by djkcyl** [comment]
Okay thank you
