### ISSUE TITLE
When cheater play offline on steam reportbot not work

### ISSUE THREAD

**Issue by ilovegame1985** [BeepIsla/csgo-commend-bot#208]
Target is likely not in a server or in a full server // Failed to find connect bytes
 Failed to receive Valve CSGO Server information
 Target is likely not in a server or in a full server // Failed to find connect bytes
 Failed to receive Valve CSGO Server information
 Target is likely not in a server or in a full server // Failed to find connect bytes
 Failed to receive Valve CSGO Server information
 Target is likely not in a server or in a full server // Failed to find connect bytes
 Failed to receive Valve CSGO Server information
 Target is likely not in a server or in a full server // Failed to find connect bytes
 Failed to receive Valve CSGO Server information
 Target is likely not in a server or in a full server // Failed to find connect bytes
 Failed to receive Valve CSGO Server information
 Target is likely not in a server or in a full server // Failed to find connect bytes
 Failed to receive Valve CSGO Server information
 Target is likely not in a server or in a full server // Failed to find connect bytes
 Failed to receive Valve CSGO Server information
 Target is likely not in a server or in a full server // Failed to find connect bytes
 Failed to receive Valve CSGO Server information
 Target is likely not in a server or in a full server // Failed to find connect bytes
 Failed to receive Valve CSGO Server information
 Failed to find server after 11 tries

getting this massage

and then if cheater go online on steam reportbot bot work
its bug ?
sorry for bad English

Thank you!

**Comment by BeepIsla** [comment]
You can't report/commend unless you know their server ID, they are on a Valve server, or use `cl_join_advertise 2` on a community server.

**Comment by ilovegame1985** [comment]
if I set auto server and match id work?

**Comment by BeepIsla** [comment]
If you know them, yes. If you don't know them you can't report/commend bot them

**Comment by ilovegame1985** [comment]
can u share discord id sir?

**Comment by BeepIsla** [comment]
My Discord is on the left side of my Github profile.

**Comment by ilovegame1985** [comment]
ok ty Sir
