### ISSUE TITLE
Not sure what's the problem or what I did wrong

### ISSUE THREAD

**Issue by Loadable** [BeepIsla/csgo-commend-bot#212]
![image](https://user-images.githubusercontent.com/40679332/72479533-8c3c8a80-37a9-11ea-864b-5b59efe9dcc7.png)
![image](https://user-images.githubusercontent.com/40679332/72479545-98284c80-37a9-11ea-8e4b-1f8f598d9175.png)

**Comment by BeepIsla** [comment]
You don't fulfill the requirements listed on the README. I quote:

> [NodeJS **v12**](https://nodejs.org/dist/v12.9.1/) - You will likely need `node-v12.9.1-x64.msi`
