### ISSUE TITLE
Error on npm install?

### ISSUE THREAD

**Issue by KernCS** [BeepIsla/csgo-commend-bot#213]
So a few days ago i reset my pc and now im trying to setup this commend bot again but i keep getting this error, how can i fix this? im using v13.6.0 of Node 
![JeSSW17](https://user-images.githubusercontent.com/31683300/72480005-4fe34b80-37f6-11ea-9fc4-997e58c26ffe.png)

**Comment by BeepIsla** [comment]
You don't fulfill the requirements listed on the README. I quote:

> [NodeJS **v12**](https://nodejs.org/dist/v12.9.1/) - You will likely need `node-v12.9.1-x64.msi`
