### ISSUE TITLE
Valve servers

### ISSUE THREAD

**Issue by louieyesyes** [BeepIsla/csgo-commend-bot#214]
Hello, I was wondering how you commend bot people using server but i was wondering if there was a way to do it if there in a matchmaking server, so a standard 64-tick mm server.

Thanks in advanced.

**Comment by BeepIsla** [comment]
Valve or Community server doesn't matter. Steps are very similar, the README tells you everything you need to know.

By far the easiest way would be to simply get a fetcher account and settings both `serverID` and `matchID` to `"auto"`.
