### ISSUE TITLE
In-game timeout because of mass commends

### ISSUE THREAD

**Issue by lustie** [BeepIsla/csgo-commend-bot#217]
I know this is a known issue, but it doesn't only time out in game, it times out my entire internet connection, so I would like an option to add delay between commends, for example:
Commend -> 1 second -> Commend
This could make the process slower but will be better for some users, and it should be optional. Thanks!

**Comment by BeepIsla** [comment]
What you could do instead if change `perChunk` to something like 5 (so you get 5 commends at once) and then change `betweenChunks` to something like 75000.

That should be much less internet usage but would still be equals to 20 commends per 5 minutes just more spread out.
