### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by Roki100** [BeepIsla/csgo-commend-bot#218]
**Detailed question description**
I have 2 questions: 
1. How can i reportbot community server?
2. How can i undo commends for user?
If i remember correctly there was an option for those but i cant find it

**Config**
```
I dont think config will be needed for those?
```

**Version**
- NodeJS: `v12.14.1` (You can find this using `node -v`)
- Script version: `2.4.7` (You can find this in **your** `package.json` file under `version`)

**Comment by BeepIsla** [comment]
Reporting is like commending, it works on any server. Just do the usual stuff, set type to `REPORT` and set the server ID (or use `auto` if `cl_join_advertise 2` is set).

You cannot undo commends.

**Comment by Roki100** [comment]
so the undo commends thing that was in the bot like year ago didnt work?

**Comment by BeepIsla** [comment]
As far as I know you cannot remove commends, so no. If you want to prove me wrong go ahead but it would be somewhat of a pain to add the ability to undo commends.

**Comment by Roki100** [comment]
just tested, it seems its only possible to change commends so if you commended someone for all leader,teaching and friendly, you can change these to only for ex. leader

**Comment by BeepIsla** [comment]
I am not gonna implement a way to change commends later. Its too much work for almost no gain at all.

**Comment by Roki100** [comment]
true and also i think it would be possible to do with resetting database & commending again
