### ISSUE TITLE
Issue regarding using same accounts when trying to commend 

### ISSUE THREAD

**Issue by sgupta-1** [BeepIsla/csgo-commend-bot#22]
well i commend usually 1-3 people per 3 hrs
but problem comes when i see that the available accounts are not being used instead timed out once are used again and again.. Please solve this issue

[AssortedSickLemur] Connected to CSGO GameCoordinator                            [BrightStingyBarracuda] Has encountered an error                                 Error: Failed to send commend: Timeout                                               at Timeout.setTimeout [as _onTimeout] (E:\Steam Tricks\Commend Bot\csgo-comm end-bot-master\helpers\account.js:137:12)                                            at ontimeout (timers.js:436:11)                                                  at tryOnTimeout (timers.js:300:5)                                                at listOnTimeout (timers.js:263:5)                                               at Timer.processTimers (timers.js:223:10)                                    [BlushingRoastedBeaver] Has encountered an error                                 Error: Failed to send commend: Timeout                                               at Timeout.setTimeout [as _onTimeout] (E:\Steam Tricks\Commend Bot\csgo-comm end-bot-master\helpers\account.js:137:12)                                            at ontimeout (timers.js:436:11)                                                  at tryOnTimeout (timers.js:300:5)                                                at listOnTimeout (timers.js:263:5)                                               at Timer.processTimers (timers.js:223:10)                                    [BerserkVerdantViper] Has encountered an error
--

**Comment by BeepFelix** [comment]
One of the recent commits solved a important bug which caused the script to use the wrong accounts.

You can only commend once every 12 hours.
