### ISSUE TITLE
The term `npm` is not recognized

### ISSUE THREAD

**Issue by noord101** [BeepIsla/csgo-commend-bot#220]
**Detailed question description**
I can't install npm. This is what pops up when trying to install it: 
PS C:\Users\Elis Hippe Runsten\Desktop\csgo-commend-bot-master> npm install
npm : The term 'npm' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ npm install
+ ~~~
    + CategoryInfo          : ObjectNotFound: (npm:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\Elis Hippe Runsten\Desktop\csgo-commend-bot-master>

Any help regarding this issue?

**Comment by BeepIsla** [comment]
Have you even installed NodeJS as listed on the README?
