### ISSUE TITLE
Error by timeout

### ISSUE THREAD

**Issue by dassakkebabi** [BeepIsla/csgo-commend-bot#223]
{
  name: 'Error',
  message: 'GC connection timeout - GCHello',
  stack: 'Error: GC connection timeout - GCHello\n' +
    '    at Timeout._onTimeout (C:\\Users\\deniz\\Desktop\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:89:12)\n' +
    '    at listOnTimeout (internal/timers.js:531:17)\n' +
    '    at processTimers (internal/timers.js:475:7)'
}

**Comment by BeepIsla** [comment]
Use the issue template.

Show config, Show the actual full log

**Comment by dassakkebabi** [comment]
![Ekran Alıntısı](https://user-images.githubusercontent.com/52428190/72979474-705c6880-3de9-11ea-9e82-32e718f31f4a.PNG)

**Comment by dassakkebabi** [comment]
Can you give me sample config file?

**Comment by BeepIsla** [comment]
Your config doesn't seem to be wrong. Do you have any vac or game bans?

**Comment by dassakkebabi** [comment]
No my account havent any bans but my trust factor is very low, so i'm doing it u know.

**Comment by dassakkebabi** [comment]
PS C:\Users\deniz\Desktop\csgo-commend-bot-master> node index.js
 Checking for new update...
 Up to date!
 Checking protobufs...
 Found protobufs
 Opening database...
 There are a total of 10 operational accounts
 Parsing target account...
 Chunking 10 accounts into groups of 20...
 Parsing server input
 Logging into fetcher account...
Steam Guard App Code: blabla(cencored i was put true code)
Error: GC connection timeout - GCHello
    at Timeout._onTimeout (C:\Users\deniz\Desktop\csgo-commend-bot-master\helpers\GameCoordinator.js:89:12)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) Promise {
  <rejected> Error: GC connection timeout - GCHello
      at Timeout._onTimeout (C:\Users\deniz\Desktop\csgo-commend-bot-master\helpers\GameCoordinator.js:89:12)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)
}

**Comment by BeepIsla** [comment]
Wait, you use `LOGIN` method, right? Why does it then try to log into fetcher account?

**Comment by dassakkebabi** [comment]
Yes, i dont know why.

**Comment by dassakkebabi** [comment]
İ'm trying again, sorry if ur country time is night its 6 am on Turkey...

**Comment by BeepIsla** [comment]
This makes no sense, its impossible for it to do "`Logging into fetcher account`" when you use `LOGIN` method.

**Comment by dassakkebabi** [comment]
İ check this method

**Comment by dassakkebabi** [comment]
No way dude its login allready

**Comment by BeepIsla** [comment]
I look in the code, the **only** way it logs "`Logging into fetcher account`" is when `method` is set to `SERVER` and either `serverID` or `matchID` are set to `AUTO`. Its impossible for the things to happen that happen to you.

Do you have multiple config files? Show your folder.

**Comment by dassakkebabi** [comment]
![Ekran Alıntısı](https://user-images.githubusercontent.com/52428190/73042123-0b4c5580-3e71-11ea-9653-0854e19112e6.PNG)

**Comment by dassakkebabi** [comment]
Maybe because i just write login, should i write LOGIN?

**Comment by BeepIsla** [comment]
It automatically forces capitalization to check. I don't know why it doesn't work?!

**Comment by dassakkebabi** [comment]
Dude i fix that problem, i just spend my 0.40 dollars for buy 150 commends.
Thats bullshit so cheap why i just spend my time for this. Thanks for everything.

**Comment by dassakkebabi** [comment]
But i will fix it and do it for your helping effort.

**Comment by RonnieeTV** [comment]
I also have this same problem.
Did anyone manage to work out a fix?

**Comment by BeepIsla** [comment]
What *I* think is happening is that the account it tries to log into has an empty username, causing Steam to log on anonymously, anonymous accounts cannot connect to the GameCoordinator causing this error.

**Comment by BeepIsla** [comment]
This hasn't been replied to for a very long time and there have been major changes on Valves side and on the commend bot itself. If the issue continues please reopen.

**Comment by pedro6k** [comment]
the same error happens to me, yesterday I managed to do it with 150 accounts, today I bought 200 new accounts and I m having that timeout error

**Comment by Blerkk** [comment]
Happens to me too. Weird since it used to work not so long ago with the same config.

**Comment by pedro6k** [comment]
It’s happening cuz steam update i guess (??)

**Comment by ludicsa** [comment]
It's happening with me too, I just bought new bots. At first it works, but when I try again I got the time out error.
