### ISSUE TITLE
Infinite loop for fetching target's server

### ISSUE THREAD

**Issue by 45656456kawai** [BeepIsla/csgo-commend-bot#224]
Hello, I have a request

I was wondering if it would be possible to have the fetching loop (maybe every 5 mins) until the target is spotted in a server instead of just trying 10 times for reportbot

It would be really nice if you could tell me which lines need to be changed. Idk if that will require a drastic change or not but I'll wait for your response.

Thank you so much for this awesome work really appreciate 👍

**Comment by BeepIsla** [comment]
Set `maxTries` to `9007199254740991` (Max safe integer in JS) and set `tryDelay` to `300000`, that will make it check every 5 minutes 9007199254740991 times, which is roughly 85684924417 years for the entire thing to fail and then exit.

Another issue would be when Steam has an outage or maintenance the fetcher will lose connection and you will be unable to send/receive any data until you manually restart it.

I will not add support for this further than what I said you can do in your config as I think its out of scope for this project, its just suppose to be used a handful of times and not as a service or anything like that.

**Comment by 45656456kawai** [comment]
Thank you bro. I will test this out.

**Comment by 45656456kawai** [comment]
sorry I'm not really a coder or anything so just to make sure where do i have to add number exactly?

found 3 results index.js


console.log("blue", "Trying to fetch target " + config.fetcher.maxTries + " time" + (config.fetcher.maxTries === 1 ? "" : "s") + " with a delay of " + config.fetcher.tryDelay + "ms");

			let tries = 0;
			while (!serverToUse) {
				tries++;

				if (tries > config.fetcher.maxTries) {
					console.log("red", "Failed to find server after " + tries + " tr" + (tries === 1 ? "y" : "ies"));
					break;

**Comment by BeepIsla** [comment]
> [...] I said you can do in your config [...]

I said config.

**Comment by 45656456kawai** [comment]
oh jeez im retarded.. sorry : / thanks
