### ISSUE TITLE
Commending issue

### ISSUE THREAD

**Issue by RadicalRedemption** [BeepIsla/csgo-commend-bot#225]
"Got response code 2, already commended target"

Any clue what is causing this error, when trying to commend a fresh account?

**Comment by BeepIsla** [comment]
Response code 2 is just a generic "Fail" error, though it only seems to happen when the target has already been commended, for any other problem it usually doesn't even respond and you get a "Commend Timeout".

As the log suggests the target has already been commended by the bot-account.

**Comment by RadicalRedemption** [comment]
Well the target was not commended? It is a fresh account with 0 0 0 commends.

**Comment by BeepIsla** [comment]
Then its a new unknown error or you have multiple configs and you're editing the wrong one or similar.

Show your config, censor things like API key and login details first of course.

**Comment by RadicalRedemption** [comment]
{
	"commend": {
		"friendly": 60,
		"teaching": 60,
		"leader": 60
	},
	"report": {
		"aimbot": 10,
		"wallhack": 10,
		"speedhack": 10,
		"teamharm": 10,
		"textabuse": 10,
		"voiceabuse": 10
	},
	"account": {
		"username": "xxxxxxxxxxxxx",
		"password": "xxxxxxxxxxxx",
		"sharedSecret": ""
	},
	"fetcher": {
		"username": "Account",
		"password": "Password",
		"sharedSecret": "",
		"maxTries": 10,
		"tryDelay": 2500,
		"askSteamGuard": true
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "LOGIN",
	"target": "xxxxxxxxxxxxxxxxxxxx",
	"serverID": "auto",
	"matchID": "0",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 31536000000,
	"steamWebAPIKey": "xxxxxxxxxxxxxxxxxxxxx",
	"disableUpdateCheck": false
}

**Comment by RadicalRedemption** [comment]
Started having this issue last night. I believe Valve did something..

**Comment by BeepIsla** [comment]
Config seems fine, maybe Valve did something. Who knows, will have to wait for more answers from others if Valve actually did something or not.

**Comment by mak47s** [comment]
Error Code : "Got response code 2, already commended target" 
Not: Since yesterday Fix is Coming.
