### ISSUE TITLE
Getting this problem :(

### ISSUE THREAD

**Issue by AbdallahMehiz** [BeepIsla/csgo-commend-bot#226]
**Detailed bug description**

**Error**
```
{ type: 'FORBIDDEN', key: 'xxxxxxxxxxxxxxxxxxxxx' } Promise {
  <rejected> { type: 'FORBIDDEN', key: 'xxxxxxxxxxxxxxxxxxxxx' }
}
```

**Config**
```
{
"commend": {
"friendly": 180,
"teaching": 180,
"leader": 180
},
"report": {
"aimbot": 10,
"wallhack": 10,
"speedhack": 10,
"teamharm": 10,
"textabuse": 10,
"voiceabuse": 10
},
"account": {
"username": "censored",
"password": "censored",
"sharedSecret": ""
},
"fetcher": {
"username": "Account",
"password": "Password",
"sharedSecret": "",
"maxTries": 10,
"tryDelay": 2500,
"askSteamGuard": true
},
"proxy": {
"enabled": true,
"file": "proxies.txt",
"switchProxyEveryXaccounts": 20
},
"type": "COMMEND",
"method": "LOGIN",
"target": "xxxxxxxxxxxxxxxxxxxx",
"serverID": "auto",
"matchID": "0",
"perChunk": 20,
"betweenChunks": 300000,
"cooldown": 31536000000,
"steamWebAPIKey": "xxxxxxxxxxxxxxxxxxxxx",
"disableUpdateCheck": false
}```

**Version**
latest
latest
**Additional information**
it worked fine for months, now it isnt working because of that

**Comment by AbdallahMehiz** [comment]
ok i actually fixed it now i have this issue 
{
  name: 'Error',
  message: 'GC connection timeout - GCHello',
  stack: 'Error: GC connection timeout - GCHello\n' +
    '    at Timeout._onTimeout (C:\\Users\\Abdallah\\Desktop\\commendbot\\helpers\\GameCoordinator.js:89:12)\n' +
    '    at listOnTimeout (internal/timers.js:531:17)\n' +
    '    at processTimers (internal/timers.js:475:7)'
}

i added the steam api key and got this error afterwards :"(

**Comment by BeepIsla** [comment]
Show the full output not just this small part

**Comment by AbdallahMehiz** [comment]
Checking for new update...
 Up to date!
 Checking protobufs...
 Found protobufs
 Opening database...
 There are a total of 176 operational accounts
 Parsing target account...
 Chunking 20 accounts into groups of 20...
 Parsing server input
 Parsed server input to 85568392922675362
 Error: connect ETIMEDOUT 104.126.90.181:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '104.126.90.181',
  port: 443
}

**Comment by AbdallahMehiz** [comment]
ok sorry i fixed so yeah :D sorry
