### ISSUE TITLE
Cooldown

### ISSUE THREAD

**Issue by RadicalRedemption** [BeepIsla/csgo-commend-bot#227]
I noticed that the parameter "cooldown" will add a cooldown on every account thas been used to commend, but as we know, we can commend different accounts. Is it possible to make the cooldown to apply seperately, when commending different accounts? For example, i'm commending account1 with 100 bots. Those 100 bots get cooldowns. Then i change the target to account2. Those 100 accounts should not have cooldown now. You feel me?

**Comment by BeepIsla** [comment]
I get what you want, I originally wanted to do that but ended up not doing it because I was too lazy and too complicated with the database statements required.

This is why the cooldown is 8 hours and not 24 hours. You can commend 3 times within 24 hours, 8 * 3 = 24.

**Comment by RadicalRedemption** [comment]
Can i have your discord?

**Comment by BeepIsla** [comment]
My Discord is linked on my Github profile.
