### ISSUE TITLE
 Got response code 2, already commended target

### ISSUE THREAD

**Issue by tintinqq** [BeepIsla/csgo-commend-bot#229]
Hi, sends such an error - Got response code 2, already commended target, as I understand it, what is the limit on likes on these accounts?

**Comment by BeepIsla** [comment]
Same rules apply as when you normally commend in-game.

Once commended a target you can **never** commend the same target again.

**Comment by tintinqq** [comment]
But I never liked this person

**Comment by BeepIsla** [comment]
Duplicate: #225
