### ISSUE TITLE
Why this error coming 

### ISSUE THREAD

**Issue by folvos** [BeepIsla/csgo-commend-bot#232]
[6FqQ3lpnI9pN] Failed to login and has been marked as invalid (1/20) {
  name: 'Error',
  message: 'Failed to log in within given 60000ms',
  stack: 'Error: Failed to log in within given 60000ms\n' +
    '    at Timeout._onTimeout (/home/ubuntu/csgo-commend-bot-master/helpers/account.js:52:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
} 
 [8vXkhRpxFaRH] Failed to login and has been marked as invalid (2/20) {
  name: 'Error',
  message: 'Failed to log in within given 60000ms',
  stack: 'Error: Failed to log in within given 60000ms\n' +
    '    at Timeout._onTimeout (/home/ubuntu/csgo-commend-bot-master/helpers/account.js:52:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
} 
 [DljKETbViTbx] Failed to login and has been marked as invalid (3/20) {
  name: 'Error',
  message: 'Failed to log in within given 60000ms',
  stack: 'Error: Failed to log in within given 60000ms\n' +
    '    at Timeout._onTimeout (/home/ubuntu/csgo-commend-bot-master/helpers/account.js:52:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
} 
 [EXW34XxD2XGV] Failed to login and has been marked as invalid (4/20) {
  name: 'Error',
  message: 'Failed to log in within given 60000ms',
  stack: 'Error: Failed to log in within given 60000ms\n' +
    '    at Timeout._onTimeout (/home/ubuntu/csgo-commend-bot-master/helpers/account.js:52:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
} 
 [Fvs5RKNGyeXV] Failed to login and has been marked as invalid (5/20) {
  name: 'Error',
  message: 'Failed to log in within given 60000ms',
  stack: 'Error: Failed to log in within given 60000ms\n' +
    '    at Timeout._onTimeout (/home/ubuntu/csgo-commend-bot-master/helpers/account.js:52:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
} 
 [ISEEFlcsE8Yg] Failed to login and has been marked as invalid (6/20) {
  name: 'Error',
  message: 'Failed to log in within given 60000ms',
  stack: 'Error: Failed to log in within given 60000ms\n' +
    '    at Timeout._onTimeout (/home/ubuntu/csgo-commend-bot-master/helpers/account.js:52:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
} 
 [Ly9rhLeuNLwQ] Failed to login and has been marked as invalid (7/20) {
  name: 'Error',
  message: 'Failed to log in within given 60000ms',
  stack: 'Error: Failed to log in within given 60000ms\n' +
    '    at Timeout._onTimeout (/home/ubuntu/csgo-commend-bot-master/helpers/account.js:52:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
} 
 [QPoX5nhPkkkv] Failed to login and has been marked as invalid (8/20) {
  name: 'Error',
  message: 'Failed to log in within given 60000ms',
  stack: 'Error: Failed to log in within given 60000ms\n' +
    '    at Timeout._onTimeout (/home/ubuntu/csgo-commend-bot-master/helpers/account.js:52:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
} 
 [SF9rzLS0sPSA] Failed to login and has been marked as invalid (9/20) {
  name: 'Error',
  message: 'Failed to log in within given 60000ms',
  stack: 'Error: Failed to log in within given 60000ms\n' +
    '    at Timeout._onTimeout (/home/ubuntu/csgo-commend-bot-master/helpers/account.js:52:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
} 
 [UwH0dryJq1LA] Failed to login and has been marked as invalid (10/20) {
  name: 'Error',
  message: 'Failed to log in within given 60000ms',
  stack: 'Error: Failed to log in within given 60000ms\n' +
    '    at Timeout._onTimeout (/home/ubuntu/csgo-commend-bot-master/helpers/account.js:52:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
} 
 [WWZCnYHw4zkr] Failed to login and has been marked as invalid (11/20) {
  name: 'Error',
  message: 'Failed to log in within given 60000ms',
  stack: 'Error: Failed to log in within given 60000ms\n' +
    '    at Timeout._onTimeout (/home/ubuntu/csgo-commend-bot-master/helpers/account.js:52:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
} 
 [ZpuKDrfhuM5w] Failed to login and has been marked as invalid (12/20) {
  name: 'Error',
  message: 'Failed to log in within given 60000ms',
  stack: 'Error: Failed to log in within given 60000ms\n' +
    '    at Timeout._onTimeout (/home/ubuntu/csgo-commend-bot-master/helpers/account.js:52:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
} 
 [bZw7iIbPMzdN] Failed to login and has been marked as invalid (13/20) {
  name: 'Error',
  message: 'Failed to log in within given 60000ms',
  stack: 'Error: Failed to log in within given 60000ms\n' +
    '    at Timeout._onTimeout (/home/ubuntu/csgo-commend-bot-master/helpers/account.js:52:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
} 
 [iYne1cwuXi5Z] Failed to login and has been marked as invalid (14/20) {
  name: 'Error',
  message: 'Failed to log in within given 60000ms',
  stack: 'Error: Failed to log in within given 60000ms\n' +
    '    at Timeout._onTimeout (/home/ubuntu/csgo-commend-bot-master/helpers/account.js:52:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
} 
 [ij5ojF5qvWx8] Failed to login and has been marked as invalid (15/20) {
  name: 'Error',
  message: 'Failed to log in within given 60000ms',
  stack: 'Error: Failed to log in within given 60000ms\n' +
    '    at Timeout._onTimeout (/home/ubuntu/csgo-commend-bot-master/helpers/account.js:52:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
} 
 [mu3LKzj0prI4] Failed to login and has been marked as invalid (16/20) {
  name: 'Error',
  message: 'Failed to log in within given 60000ms',
  stack: 'Error: Failed to log in within given 60000ms\n' +
    '    at Timeout._onTimeout (/home/ubuntu/csgo-commend-bot-master/helpers/account.js:52:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
} 
 [nRHlbzTvXvZm] Failed to login and has been marked as invalid (17/20) {
  name: 'Error',
  message: 'Failed to log in within given 60000ms',
  stack: 'Error: Failed to log in within given 60000ms\n' +
    '    at Timeout._onTimeout (/home/ubuntu/csgo-commend-bot-master/helpers/account.js:52:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
} 
 [p85qDm6odgaA] Failed to login and has been marked as invalid (18/20) {
  name: 'Error',
  message: 'Failed to log in within given 60000ms',
  stack: 'Error: Failed to log in within given 60000ms\n' +
    '    at Timeout._onTimeout (/home/ubuntu/csgo-commend-bot-master/helpers/account.js:52:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
} 
 [z6doGZTDW6m5] Failed to login and has been marked as invalid (19/20) {
  name: 'Error',
  message: 'Failed to log in within given 60000ms',
  stack: 'Error: Failed to log in within given 60000ms\n' +
    '    at Timeout._onTimeout (/home/ubuntu/csgo-commend-bot-master/helpers/account.js:52:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
} 
 [ziAoxRMTLYBR] Failed to login and has been marked as invalid (20/20) {
  name: 'Error',
  message: 'Failed to log in within given 60000ms',
  stack: 'Error: Failed to log in within given 60000ms\n' +
    '    at Timeout._onTimeout (/home/ubuntu/csgo-commend-bot-master/helpers/account.js:52:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
} 
 Chunk 1/1 finished with 0 successful commends and 20 failed commends 
 Finished all chunks with a total of 0 successful and 20 failed commends

**Comment by BeepIsla** [comment]
Show your config,

**Comment by folvos** [comment]
![Capture](https://user-images.githubusercontent.com/18247507/73614376-62e28200-4624-11ea-9979-2c10f0d63524.PNG)

**Comment by folvos** [comment]
![Capture](https://user-images.githubusercontent.com/18247507/73614401-b359df80-4624-11ea-8ba5-b9e76b5d2317.PNG)

**Comment by BeepIsla** [comment]
I am unsure, something must be wrong with the accounts.

**Comment by aks19n** [comment]
Getting the same error. Of 700 accounts only ~200 actually commend, other 500 just say "TImeout"

**Comment by BeepIsla** [comment]
Closing this due to major changes on Valves side and on the commend bot itself. If the issue continues please reopen.
