### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by aciidiic** [BeepIsla/csgo-commend-bot#235]
**Detailed bug description**
When sending it shoots me an error

**Error**
```
 [arshunter] Failed to commend (20/20) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\Jacob\\Downloads\\csgo-commend-bot-master\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:191:12)\n' +
    '    at listOnTimeout (internal/timers.js:531:17)\n' +
    '    at processTimers (internal/timers.js:475:7)'
}
```

**Config**
```
https://gyazo.com/bbda9a24c685fc0ac4e591fcd74b45d5
```

**Version**
- NodeJS: `v12.14.1
- Script version: `2.5.2)

**Additional information**
Add any other potentially useful information about your issue here.

**Comment by BeepIsla** [comment]
Full log would help more, is it only on the 20th per chunk?

**Comment by ohyhello** [comment]
same problem

**Comment by BeepIsla** [comment]
Closing this due to major changes on Valves side and on the commend bot itself. If the issue continues please reopen.
