### ISSUE TITLE
Cannot find module 'sqlite'

### ISSUE THREAD

**Issue by imprisonedmind** [BeepIsla/csgo-commend-bot#236]
`C:\Users\imaho\Downloads\csgo-commend-bot-master\csgo-commend-bot-master>node index.js
internal/modules/cjs/loader.js:775
    throw err;
    ^

Error: Cannot find module 'sqlite'
Require stack:
- C:\Users\imaho\Downloads\csgo-commend-bot-master\csgo-commend-bot-master\index.js
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:677:27)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:830:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:68:18)[39m
    at Object.<anonymous> (C:\Users\imaho\Downloads\csgo-commend-bot-master\csgo-commend-bot-master\index.js:1:16)
[90m    at Module._compile (internal/modules/cjs/loader.js:936:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:790:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:703:12)[39m
[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [
    [32m'C:\\Users\\imaho\\Downloads\\csgo-commend-bot-master\\csgo-commend-bot-master\\index.js'[39m
  ]
}`

Any help, Thanks

**Comment by BeepIsla** [comment]
As per README installation instructions: 

> Enter `npm install`

Did you do that? Was it successful? Did you do it in the right folder?

**Comment by imprisonedmind** [comment]
SOLVED ALREADY #178
