### ISSUE TITLE
can't connect to servers

### ISSUE THREAD

**Issue by mrflt** [BeepIsla/csgo-commend-bot#237]
bot cant connect to server...
Could not find online server for A:1:1946497032:14065 this is error...!!!

**Comment by BeepIsla** [comment]
1. Bots never connect to a server
2. Use the issue template, config, actually show the full logs, etc.
2. That's not a ServerID. [Read](https://github.com/BeepIsla/csgo-commend-bot#server-id--match-id) how a server ID looks like. `[A:1:1946497032:14065]`

**Comment by mrflt** [comment]
i try my own private server ip and i see this error...
{ response: {} }
 Could not find online server for A:1:1946497032:14065

**Comment by BeepIsla** [comment]
Read what I said. Especially point 2 and 3. You are missing brackets.
