### ISSUE TITLE
Found target on Community server

### ISSUE THREAD

**Issue by MrJack9919** [BeepIsla/csgo-commend-bot#239]
It gives this error, with the SERVER method, I already tried everything, the serverID in brackets, everything is as it should [A:X:XXXXXX:XXX] tell me what to do?

ERROR:

Found target on Community server [A:X:XXXXXXX:XXXXX] after 0 tries
 { response: {} }
(Where is X my numbers)

[MY CONFIG.JSON](https://imgur.com/a/LTVdGo6)

NodeJS: v12.15.0
Script version: 2.5.3

**Comment by BeepIsla** [comment]
Is it a community server, valve server or localhost

**Comment by MrJack9919** [comment]
localhost with bots

**Comment by BeepIsla** [comment]
I don't think the script supports localhost, use a community idle server or valve server.

**Comment by MrJack9919** [comment]
Ehh((( It is very sad
