### ISSUE TITLE
Stuck on npm install

### ISSUE THREAD

**Issue by Arbaz2** [BeepIsla/csgo-commend-bot#240]
It was working fine till yesterday. but today when i updated it to latest version it was stuck on "node-pre-gyp WARN Using request for node-pre-gyp https download" in "CMD" after typed "npm install".
 I updated csgo-commend-bot by removing old folder of  csgo-commend-bot completely.

Any fixes?

**Comment by Arbaz2** [comment]
![Capture](https://user-images.githubusercontent.com/43499686/74045142-144f3200-49ee-11ea-9972-b373e640c2d5.PNG)

And when i type node databasemanager.js it says as you seen in picture
![1](https://user-images.githubusercontent.com/43499686/74045209-2d57e300-49ee-11ea-96ba-268aa18132d1.PNG)

**Comment by BeepIsla** [comment]
> I updated csgo-commend-bot by removing old folder of csgo-commend-bot completely

I hope you kept your accounts.sqlite, becwuse thats where all important infomation is stored, and you will run into response code 2 if you try to commend an already commended target.

You should have used the issue template, most important: What is your node version?

**Comment by Arbaz2** [comment]
No i deleted full folder with accounts.sqlite

And my node verison is v12.14.1.

**Comment by BeepIsla** [comment]
Just do `npm install` and wait until its done. Its downloading required binaries

**Comment by Arbaz2** [comment]
i waited like 20 to 25 mins but nothing happens. it just stuck on it

**Comment by BeepIsla** [comment]
Does the same happen if you just type `npm install sqlite`?

**Comment by cptmacp** [comment]
> ![Capture](https://user-images.githubusercontent.com/43499686/74045142-144f3200-49ee-11ea-9972-b373e640c2d5.PNG)
> 
> And when i type node databasemanager.js it says as you seen in picture
> ![1](https://user-images.githubusercontent.com/43499686/74045209-2d57e300-49ee-11ea-96ba-268aa18132d1.PNG)


it says here sqlite is missing

use command as told by beeplsla

**Comment by BeepIsla** [comment]
Closing due to 17 days of no replies, I assume this is solved.
