### ISSUE TITLE
no such column NaN

### ISSUE THREAD

**Issue by ha6000** [BeepIsla/csgo-commend-bot#241]
**Detailed bug description**
When I report a user I get a sqlite error saying no such column NaN

**Error**
```
 Checking for new update...
 Up to date!
 Checking protobufs...
 Found protobufs
 Opening database...
 There are a total of 34 operational accounts
 Parsing target account...
[Error: SQLITE_ERROR: no such column: NaN] {
  errno: 1,
  code: 'SQLITE_ERROR'
} Promise {
  <rejected> [Error: SQLITE_ERROR: no such column: NaN] {
    errno: 1,
    code: 'SQLITE_ERROR'
  }
}
```

**Config**
```
{
    "commend": {
        "friendly": 5,
        "teaching": 10,
        "leader": 15
    },
    "report": {
        "aimbot": 1
    },
    "account": {
        "username": "",
        "password": "",
        "sharedSecret": ""
    },
    "fetcher": {
        "username": "Account",
        "password": "Password",
        "sharedSecret": "",
        "maxTries": 10,
        "tryDelay": 2500,
        "askSteamGuard": true
    },
    "proxy": {
        "enabled": false,
        "file": "proxies.txt",
        "switchProxyEveryXaccounts": 20
    },
    "type": "REPORT",
    "method": "SERVER",
    "target": "xxxx",
    "serverID": "xxxxx",
    "matchID": "0",
    "perChunk": 20,
    "betweenChunks": 300000,
    "cooldown": 28800000,
    "steamWebAPIKey": "xxxxx",
    "disableUpdateCheck": false
}
```

**Version**
- NodeJS: `v12.14.1`
- Script version: `1.5.14`

**Additional information**
I found it was coming from line 206 in index.js

**Comment by BeepIsla** [comment]
Why did you remove the other values in report?

**Comment by ha6000** [comment]
> Why did you remove the other values in report?

As I didnt actually wanted the user to get banned. I was only doing it for testing. But if you want me to, I can add them back

**Comment by BeepIsla** [comment]
Don't remove anything from the config, you can simply set it to `0`.

**Comment by ha6000** [comment]
Weird. That fixed it. 
Strange because that is not used on line 206?

**Comment by BeepIsla** [comment]
> Strange because that is not used on line 206?

Line 206 gets enough accounts from the database as needed, previously on line 67 it tries to figure out how many accounts are needed to fulfill your report amount in the most efficient way. Since you had values missing it didn't know what to do and outputted `NaN`, not a number. The SQL statement to get accounts from the database needs a number though and therefore returned an error.
