### ISSUE TITLE
100 Commend in 2 Minutes?

### ISSUE THREAD

**Issue by orcnaydn** [BeepIsla/csgo-commend-bot#242]
I saw someone he commended himself 100 commend in 2 minutes how can he do that? This is possible? Or Example I have 3 API key i can send 60 (20-20-20) commend to myself?

**Comment by 45656456kawai** [comment]
proxies maybe?

**Comment by BeepIsla** [comment]
Good Residential Proxies, 20 commends per IP as far as I know.
