### ISSUE TITLE
Timeout on Accounts after a few successful commends

### ISSUE THREAD

**Issue by GitZurah** [BeepIsla/csgo-commend-bot#243]
Hey, 
First off thanks for making this commend bot, it worked well for me for the past few days and weeks.

But now I ran into a problem. Every time i want to commend, I either timeout on all accounts or on all but the first 2 or 3. I've tried both SERVER and LOGIN method, both with the same result.

(https://user-images.githubusercontent.com/60843536/74101340-f93d0900-4b38-11ea-835d-c7614a495e69.jpg)
- Screenshot of my config file

I hope there is a way to fix this problem

**Comment by cptmacp** [comment]
i think you need to wait for 24 hours or some time idk
one account can commend 2 ID's in some time interval

**Comment by BeepIsla** [comment]
Good question, I don't know. Would have to look more into it, especially LOGIN method is known to be a little weird.

**Comment by GitZurah** [comment]
` name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\Zurah\\Desktop\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:191:12)\n' +
    '    at listOnTimeout (internal/timers.js:531:17)\n' +
    '    at processTimers (internal/timers.js:475:7)'
}`

This error is really annoying because it makes commend botting (and most of my commends already don't go through even though they're labeled as successful) even more ineffective :( I hope you or someone else can figure something out

**Comment by BeepIsla** [comment]
Timeout error usually only happens if you do something wrong. Nobody else reported any issues.

**Comment by GitZurah** [comment]
The question is what am I doing wrong ?
The weird thing is that sometimes it can login into Accounts, but sometimes just not, so it can't be a firewall problem or any problem of these sorts..

**Comment by BeepIsla** [comment]
Not being able to log in and just timeout error are two completely different things. Timeout is usually when the server ID is not the same as the target's server. Login error depends on what it actually outputs.

**Comment by GitZurah** [comment]
Well then I am getting the timeout error it seems. I am currently using the LOGIN method but I will look back into the SERVER method, maybe I have more success there

**Comment by GitZurah** [comment]
I tested it with the SERVER method and got the same faulty result - I time out on all accounts after 10 or 20... :(

**Comment by BeepIsla** [comment]
Closing this due to major changes on Valves side and on the commend bot itself. If the issue continues please reopen.
