### ISSUE TITLE
help meh

### ISSUE THREAD

**Issue by KissLevente15** [BeepIsla/csgo-commend-bot#244]
**Detailed bug description**
Error: InvalidPassword

**Error**
```
![image](https://user-images.githubusercontent.com/60847596/74104291-8d1bce80-4b53-11ea-9973-7b0b70c6ec90.png)

```

**Config**
```
![image](https://user-images.githubusercontent.com/60847596/74104369-5c886480-4b54-11ea-9e8c-9af65d4e0a85.png)


```

**Version**
- NodeJS: `v12.15.0`
- Script version: `2.6.0`

**Additional information**
Add any other potentially useful information about your issue here.

**Comment by BeepIsla** [comment]
Have you tried actually entering an account in the `fetcher` potion of the config? You use `AUTO` so you need it.

**Comment by KissLevente15** [comment]
I tried.

**Comment by KissLevente15** [comment]
I redownloaded, now its good idk what was the problem.
