### ISSUE TITLE
Cannot read property

### ISSUE THREAD

**Issue by wytrom** [BeepIsla/csgo-commend-bot#247]
**Detailed bug description**

**Error**
TypeError: Cannot read property 'switchProxyEveryXaccounts' of undefined
    at C:\Users\SsdSys1\Desktop\csgo-commend-bot-master\index.js:249:35 Promise {
  <rejected> TypeError: Cannot read property 'switchProxyEveryXaccounts' of undefined
      at C:\Users\SsdSys1\Desktop\csgo-commend-bot-master\index.js:249:35
A full error log or screenshot.

https://prnt.sc/r0s865

**Config**
https://prnt.sc/r0s8rb

```

**Version**
- NodeJS: `v12.15.0` 
- Script version: `"2.6.0",` 
**Additional information**
Error occurred after adding too many accounts

**Comment by BeepIsla** [comment]
Update your config and don't delete stuff out of it.
