### ISSUE TITLE
Question about my config

### ISSUE THREAD

**Issue by BananasToaster** [BeepIsla/csgo-commend-bot#248]
so uh i got this error when executin node index.js
https://gyazo.com/4770095896e0b0b42536e5c051b8945a

and heres my config

https://gyazo.com/900d525bbadccbebbec2a8ee55d424e7

and, do i really need to put my API key.. i've seen people commendin me without givin them my key

**Comment by Weazoo** [comment]
When someone is commending you they use your steamid so for example this here is a frinds of mines account i would use this link for the steamip https://steamcommunity.com/profiles/76561199021847985/
and other i think you do need your steam key in the config file hope this helps if not i hope someone more knowledgeable gets to this and helps you

**Comment by BeepIsla** [comment]
Actually put in a real fetcher account if you use `AUTO` anywhere.
