### ISSUE TITLE
two word  fuck val !  i cant send commend any more!

### ISSUE THREAD

**Issue by masonmmd** [BeepIsla/csgo-commend-bot#250]
dude plz help us fix it plz !

**Comment by BeepIsla** [comment]
Why do you make your own issue when you already commended on #249? Don't do this.

**Comment by masonmmd** [comment]
sry dude im angery!

**Comment by BeepIsla** [comment]
Its a virtual number with no impact on anything, calm down. It literally does not matter.

**Comment by masonmmd** [comment]
dude im working with this !

**Comment by codsec** [comment]
Valve deactivated the relevance of free accounts, the bot is not 100% in-functional if you have active Prime Accounts you can continue using the bot normally, both for report and for commend

**Comment by OTGCable** [comment]
> Valve deactivated the relevance of free accounts, the bot is not 100% in-functional if you have active Prime Accounts you can continue using the bot normally, both for report and for commend

That'd be a lot of prime accounts depending on how many commends you wanted tbh.
Hella expensive no matter how you look at it

**Comment by codsec** [comment]
> > Valve deactivated the relevance of free accounts, the bot is not 100% in-functional if you have active Prime Accounts you can continue using the bot normally, both for report and for commend
> 
> That'd be a lot of prime accounts depending on how many commends you wanted tbh.
> Hella expensive no matter how you look at it

This is not the problem of the bot but of who uses it

**Comment by OTGCable** [comment]
> > > Valve deactivated the relevance of free accounts, the bot is not 100% in-functional if you have active Prime Accounts you can continue using the bot normally, both for report and for commend
> > 
> > 
> > That'd be a lot of prime accounts depending on how many commends you wanted tbh.
> > Hella expensive no matter how you look at it
> 
> This is not the problem of the bot but of who uses it

Never blamed the bot tbh. It's just a dumb suggestion because at that point you're better off just not messing with commends at all

**Comment by masonmmd** [comment]
any one can help me for crack steam acc?

**Comment by BeepIsla** [comment]
Things like cracking accounts will not be discussed here.

**Comment by masonmmd** [comment]
ok
