### ISSUE TITLE
node_sqlite3.node is not a valid Win32 application.

### ISSUE THREAD

**Issue by crx9** [BeepIsla/csgo-commend-bot#251]
\csgo-commend-bot-master>node index.js
internal/modules/cjs/loader.js:977
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: \\?\C:\Users\åæ¨é\Desktop\csgo-commend-bot-master\node_modules\sqlite3\lib\binding\node-v72-win32-x64\node_sqlite3.node is not a valid Win32 application.

**Comment by BeepIsla** [comment]
Did you copy paste the entire thing with `node_modules` from one computer to another?

**Comment by crx9** [comment]
> Did you copy paste the entire thing with `node_modules` from one computer to another?

No .i use "npm install"

**Comment by BeepIsla** [comment]
Well, I don't think it matters much.

1. Valve patched it in the last update (#249)

2. If you still want to try fixing your issue you could just try `npm install sqlite3` I suppose.

**Comment by crx9** [comment]
> Well, I don't think it matters much.
> 
> 1. Valve patched it in the last update (#249)
> 2. If you still want to try fixing your issue you could just try `npm install sqlite3` I suppose.

OKay ,when will u fix commend-bot?

**Comment by BeepIsla** [comment]
I don't know. Maybe never, maybe tomorrow. Depends when someone finds a fix.

**Comment by crx9** [comment]
> 我不认为这很重要。
> 
> 1. 在上一次更新中，阀门对它进行了修补(#249)
> 2. 如果你还想解决你的问题，你可以试试`npm install sqlite3`我想是吧。

npm install sqlite3 

C:\Users\nmy\Desktop\csgo-commend-bot-master>npm install sqlite3
npm ERR! path C:\Users\nmy\Desktop\csgo-commend-bot-master\node_modules\.bin\needle.cmd
npm ERR! code EEXIST
npm ERR! Refusing to delete C:\Users\nmy\Desktop\csgo-commend-bot-master\node_modules\.bin\needle.cmd: is outside C:\Users\nmy\Desktop\csgo-commend-bot-master\node_modules\needle and not a link
npm ERR! File exists: C:\Users\nmy\Desktop\csgo-commend-bot-master\node_modules\.bin\needle.cmd
npm ERR! Move it away, and try again.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\nmy\AppData\Roaming\npm-cache\_logs\2020-02-12T16_22_24_450Z-debug.log

**Comment by BeepIsla** [comment]
No idea what that is. Google suggests: Delete your entire `node_modules` folder and do `npm install` again.

**Comment by crx9** [comment]
> No idea what that is. Google suggests: Delete your entire `node_modules` folder and do `npm install` again.

C:\Users\nmy\Desktop\csgo-commend-bot-master>npm install

> sqlite3@4.1.0 install C:\Users\nmy\Desktop\csgo-commend-bot-master\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download

**Comment by BeepIsla** [comment]
Just wait, it should automatically download the required binaries and then just finish.

**Comment by BeepIsla** [comment]
No further replies for 2 weeks, I assume this is solved.
