### ISSUE TITLE
Trust Factor

### ISSUE THREAD

**Issue by shubhamedge** [BeepIsla/csgo-commend-bot#253]
Sir,
  I am having Red Trust factor in CSGO due to Mass report , DO u have any Fix for this i have RED TF Since last Week . Please Help Me sir , i dont have much source so i am writing you ,hope you will read this..
Regards :

**Comment by BeepIsla** [comment]
No. This is the wrong place to ask these kind of questions. Refer to [The Trust Factor FAQ](https://blog.counter-strike.net/index.php/the-trust-factor/) for more information.

Commend bots do **not** increase Trust Factor.
