### ISSUE TITLE
how do i check accounts?

### ISSUE THREAD

**Issue by shortguy123** [BeepIsla/csgo-commend-bot#255]
i have more than 20k accounts but 75 % only work so how do i check if they work and only filter working ones?

**Comment by BeepIsla** [comment]
You use them and it will automatically mark the nit working ones, then later you can export a list of working accounts via datbase manager.

**Comment by shubhamedge** [comment]
IS it working ? Report bot?

**Comment by shubhamedge** [comment]
is there any active report bot?

**Comment by BeepIsla** [comment]
Its not working but that doesn't matter. If it fails to login or is vac/game banned it will be marked as invalid, if it successfully logs in but fails to report/commend then so what? It doesn't matter if it fails, you just want to know if they work or not and if they can log in successfully then they work.

**Comment by shubhamedge** [comment]
Accounts are login but reporting doesn't work neither commendation

**Comment by M0nday1337** [comment]
there are a lot of brutefore apps for a steam accounts check, since valve doesn't want to fix bruting by client side (not from sites fields) i guess, that's kinda easy to find them.
e.x 
https://i.imgur.com/Obmg5Xr.png - russian version of brute/checker with old combo and proxies.

**Comment by BeepIsla** [comment]
Cracking accounts will **not** be discussed.

**Comment by M0nday1337** [comment]
> Cracking accounts will **not** be discussed.

he asked for a checking accounts only.
