### ISSUE TITLE
Helping!!!! it worked before

### ISSUE THREAD

**Issue by nachitov15** [BeepIsla/csgo-commend-bot#256]
I am having a problem, and it used to be normal, and now all accounts tell me: "time out error" and reinstall the program change the ip, reset the api key I did my best and it is not solved

LOG:

  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout \ n' +
    'at Timeout._onTimeout (C: \\ Users \\ Nacho \\ Desktop \\ Things \\ Lua \\ Recommendations Cs \\ helpers \\ GameCoordinator.js: 191: 12) \ n' +
    'at listOnTimeout (internal / timers.js: 531: 17) \ n' +
    'at processTimers (internal / timers.js: 475: 7)'
}

**Comment by BeepIsla** [comment]
#249
