### ISSUE TITLE
node index.js    error

### ISSUE THREAD

**Issue by KKTZZ** [BeepIsla/csgo-commend-bot#258]
**Detailed bug description**
F:\csgo-commend-bot-master>node F:\csgo-commend-bot-master\index.js
 Checking for new update...
Error: connect ETIMEDOUT 151.101.108.133:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '151.101.108.133',
  port: 443
} Promise {
  <rejected> Error: connect ETIMEDOUT 151.101.108.133:443
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14) {
    errno: 'ETIMEDOUT',
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '151.101.108.133',
    port: 443
  }
}

**Error**
```
A full error log or screenshot.
```

**Config**
```
[config.zip](https://github.com/BeepIsla/csgo-commend-bot/files/4240723/config.zip)

```

**Version**
- NodeJS: `vXX.XX.X` (You can find this using `node -v`)
- Script version: `X.X.X` (You can find this in **your** `package.json` file under `version`)

**Additional information**
Add any other potentially useful information about your issue here.

**Comment by BeepIsla** [comment]
Something is blocking Github.

**Comment by KKTZZ** [comment]
What should I do

**Comment by KKTZZ** [comment]
> 某些东西阻止了Github。



> 某些东西阻止了Github。

What should I do

**Comment by BeepIsla** [comment]
This might be related: https://github.com/BeepIsla/csgo-commend-bot/issues/207#issuecomment-573376802

**Comment by KKTZZ** [comment]
> 这可能与以下方面有关：[＃207（评论）](https://github.com/BeepIsla/csgo-commend-bot/issues/207#issuecomment-573376802)
Ok, thank you，
I can take the next step after the modification of the host

And there is an error

A new version is available on Github @ https://github.com/BeepIsla/csgo-commend-bot Downloading is optional but recommended. Make sure to check if there are any new values to be added in your old "config.json" Checking protobufs... Found protobufs Opening database... There are a total of 9 operational accounts Not enough accounts available, got 9/10

**Comment by BeepIsla** [comment]
Two things:

1. **Currently it does not work, Valve fixed it. It will work again after March 1st when I update it.** (#249)

2. Please read [the README](https://github.com/BeepIsla/csgo-commend-bot/blob/master/README.md) and adjust your config accordingly.

You only added 9 accounts into the database but selected 10 commends, so you do not have accounts to fulfill your selected amount.

**Comment by KKTZZ** [comment]
> Two things:
> 
> 1. **Currently it does not work, Valve fixed it. It will work again after March 1st when I update it.** (#249)
> 2. Please read [the README](https://github.com/BeepIsla/csgo-commend-bot/blob/master/README.md) and adjust your config accordingly.
> 
> You only added 9 accounts into the database but selected 10 commends, so you do not have accounts to fulfill your selected amount.

I think this might be a mistake
Do have 10


[accounts.zip](https://github.com/BeepIsla/csgo-commend-bot/files/4243373/accounts.zip)

**Comment by BeepIsla** [comment]
1. Generate a new Steam API key - You exposed yours in an earlier comment

2. You probably have to use new accounts now because you just showed everyone username and password to them

3. I am not aware of any problem with adding accounts, there is likely a mistake on your side. Make sure you actually added them all to the database using the database manager

**Comment by KKTZZ** [comment]
> 1. 生成一个新的Steam API密钥-您在前面的评论中公开了您的密钥
> 2. 您可能现在必须使用新帐户，因为您刚刚向所有人显示了用户名和密码
> 3. ~我不知道添加帐户有任何问题，可能您这边出错。确保使用数据库管理器将它们全部实际添加到数据库中。~我弄错了，您的数据库中**确实**有10个帐户，但只有9个可用。要么处于冷却状态，要么登录失败，并且该帐户已被标记为无效。

Thank you for your reminding, this account has no inventory, if someone is so mean, that I don't care, adding process test for 3 times, 3 groups of 10 bot, are display only 9 of bot. In addition, when I communicate with another user, he told me a bot can only get a great, is it? On March 1, updated? By that time I use it again?

**Comment by BeepIsla** [comment]
I will know of a fix to bypass Valve's latest implementation to prevent commend bots from working, it will be released March 1st.

Commending works just like it is in-game. You can only commend one person once but you can commend infinite **different** people.

**Comment by KKTZZ** [comment]
> 我将知道一个绕过Valve的最新实现的修复程序，以防止值得赞扬的机器人正常工作，该修复程序将于3月1日发布。
> 
> 赞扬作品就像在游戏中一样。您只能表彰一个人一次，但可以表扬无限的**其他**人（但即使是每8小时仅限1人）

ok thank y  follow
