### ISSUE TITLE
 Trouble giving recommendations!!!

### ISSUE THREAD

**Issue by delfin420** [BeepIsla/csgo-commend-bot#259]
name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\PC\\Desktop\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:191:12)\n' +
    '    at listOnTimeout (internal/timers.js:531:17)\n' +
    '    at processTimers (internal/timers.js:475:7)' 

Help. How to fix it?

**Comment by BeepIsla** [comment]
#249
