### ISSUE TITLE
Is there anyway to reportbot in a demo?

### ISSUE THREAD

**Issue by CKH0** [BeepIsla/csgo-commend-bot#260]
Dule to the last csgo update , now players can do a report in a demo
so is there any way to report bot in a demo?

**Comment by BeepIsla** [comment]
Didn't test it but most likely not as Valve can just check if the reporter was in the same match as the target just like they do right now when reporting in a live game.

**Comment by BeepIsla** [comment]
I tried and it does not work. No response.

**Comment by CKH0** [comment]
thx for your reply
