### ISSUE TITLE
forget set commend in config

### ISSUE THREAD

**Issue by mrflt** [BeepIsla/csgo-commend-bot#261]
hey beepsila you are forget set server id command in config

**Comment by BeepIsla** [comment]
Read the changelogs. This is on purpose. ServerID is irrelevant.

**Comment by mrflt** [comment]
so we can't set server id ??!!

**Comment by BeepIsla** [comment]
Correct. Server ID is not needed anymore.

**Comment by mrflt** [comment]
im sorry about that but i dont undrestand how i can set commend for user with out server id??? where can set commends for account with out server id?

**Comment by BeepIsla** [comment]
You don't need it. Just put in your target and start the bot.

**Comment by mrflt** [comment]
realy?????????? and target account most be online in CSGO??? or not? sorry for many question!

**Comment by BeepIsla** [comment]
Target must be on a community server/valve deathmatch/casual/etc.

Doesn't work on Competitive and Wingman.

**Comment by mrflt** [comment]
oh thankyou very much for this..and Commend bot Detect Account with out server id thats true???
and if target be in private server with vps thats work??? 
i set lastest command server id in config and worked with 7 version xD

**Comment by BeepIsla** [comment]
Just try it.
