### ISSUE TITLE
 '[target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function',

### ISSUE THREAD

**Issue by j0t4ribeiro** [BeepIsla/csgo-commend-bot#263]
[AgonizingAboundingTherapeuticHornet1452] Logged onto Steam - GC Time: 2/26/2020, 5:48:53 PM
 [AgonizingAboundingTherapeuticHornet1452] Authenticated to anonymous server with ticket 1218945517
 [AgonizingAboundingTherapeuticHornet1452] Failed to login and has been marked as invalid (5/5) { name: 'TypeError',
  message:
   '[target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function',
  stack:
   'TypeError: [target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function\n    at a.login.then (/root/csgo-commend-bot/helpers/Bots.js:88:7)\n    at process._tickCallback (internal/process/next_tick.js:68:7)' }
 Chunk 1/1 finished with 0 successful commends and 5 failed commends
 Finished all chunks with a total of 0 successful and 5 failed commends

**Comment by BeepIsla** [comment]
Update NodeJS.

`flat()` came in NodeJS v11.0.0 - You should update to v12 as mentioned in the README.

**Comment by j0t4ribeiro** [comment]
wow, i updated and came back, and had not seen the version, thank you very much
