### ISSUE TITLE
freez

### ISSUE THREAD

**Issue by mrflt** [BeepIsla/csgo-commend-bot#264]
hello 
i set commend bot and commends send and with a second later  i see this  error
Failed to authenticate to target server
and next commend bot is be freezed

**Comment by BeepIsla** [comment]
Show config (Censor important stuff), Show picture of the whole output, write this message again its impossible to understand.

**Comment by mrflt** [comment]
sorry for my bad language...
`http://uupload.ir/files/epno_cccc.png`   this is picture of error

**Comment by BeepIsla** [comment]
2 possible problems:

1. Message takes too long to send and the bot did not receive a response within 5 seconds.

2. An invalid authentication ticket was sent back as confirmation

The 2nd one is **very** unlikely so only 1st remains. Basically: I don't know, I never had this issue. Just something is preventing the bot from receiving a response within 5 seconds. I maybe need to up the max-time for it to 10 or 15 seconds.

**Comment by mrflt** [comment]
om...one think... in older version (2.6.1) i dont recive this error... and when i update to 2.7.0 i see this...

**Comment by mrflt** [comment]
and one think...commend bot is be freez and dont work with betwen 18,19 commends and i should close the program and open it again...

**Comment by BeepIsla** [comment]
Likely unrelated. You can try opening up `helpers/account.js` in Notepad++ and on line `272` change `5000` to something like `20000` to increase the max time from 5 seconds to 20 seconds.

Then save it and try again to see if that solves the issue.

**Comment by mrflt** [comment]
i do that i give this error again in 1 time but i give new error!!!!
see this => http://uupload.ir/files/l6f_222222.png

**Comment by BeepIsla** [comment]
> You can try opening up `helpers/account.js` in Notepad++ and on line `272` change `5000` to something like `20000` to increase the max time from 5 seconds to 20 seconds.

I released an update to do this by default.

---

Your new error comes from the bot losing connection. Try lowering `perChunk` in your config.

**Comment by mrflt** [comment]
hey i have a problem with install newer version...

`http://uupload.ir/files/bol2_eeee.png`

**Comment by BeepIsla** [comment]
There is nothing wrong here.

**Comment by mrflt** [comment]
realy?? this is new :D thankyou beepisla <3
