### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by kura6789** [BeepIsla/csgo-commend-bot#265]
I'm getting this error:
![1](https://user-images.githubusercontent.com/28402838/75385956-1582c900-58e1-11ea-8cfb-8ed9206523a9.jpg)
On my linux VPS everything is good (same config file). What cause this error? Node reinstalled, Could it be the database problem?

**Comment by BeepIsla** [comment]
Looks like your protobufs folder is not up-to-date

**Comment by kura6789** [comment]
Wow you are faster than my internet, will check. Thanks

**Comment by kura6789** [comment]
yep, outdated protobufs. Fixed thanks.
BTW. I will write question to your servers project 
Thanks again!

**Comment by BeepIsla** [comment]
> I will write question to your servers project

What are you talking about?
