### ISSUE TITLE
Got response code 2, already commended target

### ISSUE THREAD

**Issue by xhujova** [BeepIsla/csgo-commend-bot#266]
Havent used commend bot on this account, fresh made no idea why it saying that its already commended 
https://gyazo.com/933910bc219786c0e56b6eba6d6f14cb

config file screenshot:  https://gyazo.com/b699fe368a4fa432e556ba8026d4613f

**Comment by BeepIsla** [comment]
Nothing I can do, ask Valve why it responds with code 2. Code 2 means "Fail" in Steam terms but in commend botting terms that usually means "Already commended". As I said nothing I can do, Valve responded with 2 for some reason, if something is wrong with sending it doesn't respond at all, if its a duplicate (Already commended) then its response code 2. So I can't really say much to this sadly.

**Comment by xhujova** [comment]
> Nothing I can do, ask Valve why it responds with code 2. Code 2 means "Fail" in Steam terms but in commend botting terms that usually means "Already commended". As I said nothing I can do, Valve responded with 2 for some reason, if something is wrong with sending it doesn't respond at all, if its a duplicate (Already commended) then its response code 2. So I can't really say much to this sadly.

well thanks for a good response i guess, weird that every account says its commended but i havent commended anything yet ill try creating some fresh accounts i guess
