### ISSUE TITLE
commend error

### ISSUE THREAD

**Issue by RealBugzy** [BeepIsla/csgo-commend-bot#267]
What am i doing wrong, i keep getting this error.
https://i.imgur.com/CQnNrqb.png

**Config**
{
	"commend": {
		"friendly": 187,
		"teaching": 187,
		"leader": 187
	},
	"report": {
		"aimbot": 0,
		"wallhack": 0,
		"speedhack": 0,
		"teamharm": 0,
		"abusive": 0
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/profiles/76561199029204250/",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"steamWebAPIKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	"disableUpdateCheck": false
}

**Version**
- NodeJS: v10.15.3
- Script version: 2.7.1

**Comment by BeepIsla** [comment]
#263
