### ISSUE TITLE
Best place to use BOT?

### ISSUE THREAD

**Issue by nk260203** [BeepIsla/csgo-commend-bot#268]
before, the best place to use the bot was on community servers. In this latest update, which removed the "serverid" option, I was in doubt: what is the best place to use the bot now? workshop map, menu / lobby or other location.

Thank you for your attention and THANK YOU so much for updating bot <3

I apologize for my English, I'm using google translator to type this.

**Comment by BeepIsla** [comment]
Doesn't matter. Works anywhere except Competitive/Wingman. I am unsure about local servers and have not tested those. You **have** to be on a server, main menu is not enough.

**Comment by nk260203** [comment]
Okay, I tested it here on the workshop map and it's working on them, thanks again for updating the BOT.
