### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by nk260203** [BeepIsla/csgo-commend-bot#269]
Honestly, I don't know what to say about this error, it just seems

```
![unknown](https://user-images.githubusercontent.com/48919928/75422021-65ca4d00-591a-11ea-825d-d45c8995d75a.png)

```

- NodeJS: v12.9.1
- Script version: 2.7.1

**Comment by nk260203** [comment]
![unknown](https://user-images.githubusercontent.com/48919928/75422136-a75af800-591a-11ea-9cf2-dcd7de159ebd.png)
apparently the photo was not sent with the ticket

**Comment by BeepIsla** [comment]
Update your node_modules using `npm update` or `npm install`

**Comment by nk260203** [comment]
Ok, I can't take the test now, because I'm opening this ticket for a friend (he doesn't have a Github account), but as soon as he gets online, I ask him to test

**Comment by kekov133** [comment]
> ![неизвестный](https://user-images.githubusercontent.com/48919928/75422136-a75af800-591a-11ea-9cf2-dcd7de159ebd.png)
> судя по всему, фотография не была отправлена вместе с билетом

try rewriting the config.JSON,adding the "server ID" line made everything work for me.
![Screenshot_1](https://user-images.githubusercontent.com/61566400/75496020-1004ac00-59d1-11ea-872f-16eaf00a7446.png)

**Comment by BeepIsla** [comment]
I assume this was solved as what I have written above is *literally* the only solution to this problem unless the `package.json`/`package-lock.json` are not up-to-date.
