### ISSUE TITLE
Failed to send message: Timeout

### ISSUE THREAD

**Issue by dopplere** [BeepIsla/csgo-commend-bot#270]
[ExcitingQuickestHawk96] Failed to commend (20/20) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +

i get this after 15-20 succesful commends even though im using proxies

**Comment by BeepIsla** [comment]
Proxies only change once per chunk at the very most, there used to always be a problem with the last few commends not going through. I don't know why that happens and have no solution for it.

**Comment by dopplere** [comment]
but it happened even when i selected that it changes proxies after 1 only can commen 20 then need to wait like i would when im using it without proxies

**Comment by BeepIsla** [comment]
Likely just NodeJS being slow, putting a lot of strain on it with 20 commends at once. A lot of internal stuff is going on, you can try reducing `perChunk` to like 10 and also halving `betweenChunks`

**Comment by dopplere** [comment]
how much betweenchuncs do you recomend because i did that but the error is still happening

**Comment by BeepIsla** [comment]
Half perChunk and half betweenChunks.

**Comment by SajmonExp** [comment]
im having same problem 💯

**Comment by despa1r1337** [comment]
same

**Comment by snareplug** [comment]
I got working proxies but some chunks wont work, i tested 10 per 10 between and 5/5 still same error.

**Comment by BeepIsla** [comment]
So you all do this:

1. Join a server

2. Adjust config

3. Start the bot

and it sometimes doesn't work or all the time?

**Comment by snareplug** [comment]
Most likely using Login mehtod but on server method i get the same errors, even tried 5 per chunk and  5 to switch proxies same thing

**Comment by BeepIsla** [comment]
Show your config.

**Comment by snareplug** [comment]
and its only sometime

**Comment by snareplug** [comment]
{
	"commend": {
		"friendly": 1839,
		"teaching": 1839,
		"leader": 1839
	},
	"report": {
		"aimbot": 10,
		"wallhack": 10,
		"speedhack": 10,
		"teamharm": 10,
		"abusive": 10
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"proxy": {
		"enabled": true,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 15
	},
	"type": "COMMEND",
	"method": "LOGIN",
	"target": "https://steamcommunity.com/id/gabelogannewell",
	"perChunk": 15,
	"betweenChunks": 45000,
	"cooldown": 28800000,
	"steamWebAPIKey": "",
	"disableUpdateCheck": false
}


tested again, 2 chunks without problem and third timeout

**Comment by BeepIsla** [comment]
45 seconds between chunks, 15 per chunk but you are using proxies. Its likely you are sending too many commends, yes you are using proxies but just try increasing the time between. I don't know if proxies even help bypass the "20 commends per 5 minutes"-limit anymore.

**Comment by snareplug** [comment]
they do my record yesterday was 80 in 4 min , i will try to increase time

**Comment by BeepIsla** [comment]
Does this only happen at the last few of the chunk? Or does it happen to all of them in a chunk?

**Comment by snareplug** [comment]
all of the chunk

**Comment by BeepIsla** [comment]
So it happens after 2 chunks of 15 perChunk and 45000 betweenChunks, right? It could maybe be ticket expiring.

**Comment by BeepIsla** [comment]
Its not tickets expiring, they last 21 days. Can't hurt to loop it anyways and request a new ticket every few minutes or so.

**Comment by snareplug** [comment]
it happends every third chunk doesnt matter if i use 5 per chunk or 20, even with 2min betweenchunks
i even tested new dedicated proxies same

**Comment by BeepIsla** [comment]
This makes no sense, what if you try no proxies at all?

**Comment by snareplug** [comment]
i will test soon

**Comment by BeepIsla** [comment]
5 perChunk, 20 total, LOGIN method, no proxies. Worked for me just fine, all 20 successful.

**Comment by dopplere** [comment]
i tryed all of those things but don't seem to work

**Comment by dopplere** [comment]
like i can do the 20 olmoust everytime (not always) but even though i use proxies it still wont let me spam commends faster than every 150000ms

**Comment by BeepIsla** [comment]
@snareplug said:
> they do my record yesterday was 80 in 4 min

300000ms is default, 150000ms is still better but not as expected. Those are some weird and very inconsistent issues, I am unsure what the cause could be.

**Comment by dopplere** [comment]
and i even tryed that i ran 2 bots at the same time with different accounts different steamWebAPIKey and different proxys still had the same problem

**Comment by BeepIsla** [comment]
Same issue without proxies and 300000ms betweenChunks?

**Comment by dopplere** [comment]
i had no other problem than that i cant run commends any faster

**Comment by dopplere** [comment]
and that sometimes 1 or 2 fails but that happens dont matter what

**Comment by BeepIsla** [comment]
Very weird, I will test some combinations and see if I can reproduce the issue.

**Comment by dopplere** [comment]
i can commend just as fast if i use or i dont use proxies with vpn i can commend faster if i use ip X and then switch to ip Y it commends ok

**Comment by BeepIsla** [comment]
Sounds like proxies don't properly get applied. How does your proxylist look like, can you show an example with fake IPs so you don't show everyone what proxies you use if you want to keep that a secret.

**Comment by dopplere** [comment]
XXX.XX.XXX.XX:80 something along those lines

**Comment by BeepIsla** [comment]
I will take a look in a bit and see if I broke something with proxies since the latest update.

**Comment by dopplere** [comment]
i can pm u more details etc in private if u want

**Comment by BeepIsla** [comment]
I tried without proxies (As I don't have any and don't use them anyways) and it worked just fine, except for the last one of a chunk not working sometimes but other than that it worked perfectly fine. So it must be related to proxies, I have to ask some other people who *do* use proxies if they encounter the same issue or not.

**Comment by snareplug** [comment]
i dont know what happened but i was able to send 13 chuncks without problems

**Comment by UnbreakCode** [comment]
working fine for me.

**Comment by BeepIsla** [comment]
Closed due to inactivity.
