### ISSUE TITLE
Account problem

### ISSUE THREAD

**Issue by KKTZZ** [BeepIsla/csgo-commend-bot#271]
Add 10 accounts only read into nine, successfully get to 9 praise, continue to add new accounts, Parsing target account...
Not enough accounts available at the current time

? What would you like to do? Remove account from database
? Enter username you want to remove
Successfully removed 0 entries from the commend history and 0 accounts

**Comment by KKTZZ** [comment]
Continue to add accounts, reading to zero

**Comment by KKTZZ** [comment]
F:\csgo-commend-bot-master>node F:\csgo-commend-bot-master\databaseManager.js
Opening database...

? What would you like to do? Remove account from database
? Enter username you want to remove
Successfully removed 0 entries from the commend history and 0 accounts

? What would you like to do? Add account(s) to database
? What would you like to do? Import from username:password file
? Enter the name of the file you want to import F:\csgo-commend-bot-master\accounts.txt
Failed to find file at "F:\csgo-commend-bot-master\F:\csgo-commend-bot-master\accounts.txt"

? What would you like to do? Exit
Safely closing database...

F:\csgo-commend-bot-master>node F:\csgo-commend-bot-master\index.js
 Checking for new update...
 Up to date!
 Checking protobufs...
 Found protobufs
 Opening database...
 There are a total of 9 operational accounts
 Parsing target account...
 Not enough accounts available at the current time, got 0/9

**Comment by lujiangz** [comment]
Up to date!
 Checking protobufs...
 Found protobufs
 Opening database...
 There are a total of 0 operational accounts
 Not enough accounts available, got 0/15

**Comment by KKTZZ** [comment]
Test increase 65 accounts, still read only 9

F:\csgo-commend-bot-master>node F:\csgo-commend-bot-master\databaseManager.js
Opening database...

? What would you like to do? Remove account from database
? Enter username you want to remove
Successfully removed 0 entries from the commend history and 0 accounts

? What would you like to do? Add account(s) to database
? What would you like to do? Import from username:password file
? Enter the name of the file you want to import F:\csgo-commend-bot-master\accounts.txt
Failed to find file at "F:\csgo-commend-bot-master\F:\csgo-commend-bot-master\accounts.txt"

? What would you like to do? Exit
Safely closing database...

F:\csgo-commend-bot-master>node F:\csgo-commend-bot-master\index.js
 Checking for new update...
 Up to date!
 Checking protobufs...
 Found protobufs
 Opening database...
 There are a total of 9 operational accounts
 Not enough accounts available, got 9/90

**Comment by xhujova** [comment]
reset your database and add account again, should work

**Comment by BeepIsla** [comment]
Read the error.

> ? Enter the name of the file you want to import F:\csgo-commend-bot-master\accounts.txt
> Failed to find file at "F:\csgo-commend-bot-master\F:\csgo-commend-bot-master\accounts.txt"

Don't put in the full file path, instead just put in the file name.

**Comment by KKTZZ** [comment]
Thank you, that's true, written accounts.txt, rather than drag files, problem solved

? What would you like to do? Add account(s) to database
? What would you like to do? Import from username:password file
? Enter the name of the file you want to import accounts.txt

**Comment by KKTZZ** [comment]
written accounts.txt, rather than drag files, problem solved

**Comment by KKTZZ** [comment]
written accounts.txt, rather than drag files, problem solved
