### ISSUE TITLE
empty lines inbetween commending and logging in

### ISSUE THREAD

**Issue by Craxto** [BeepIsla/csgo-commend-bot#272]
there are random empty lines inbetween the lines

![grafik](https://user-images.githubusercontent.com/16746475/75476402-ce590e80-599a-11ea-8635-645bfe838d82.png)

**Version**
- NodeJS: `v12.16.1` 
- Script version: `2.7.1`

**Comment by BeepIsla** [comment]
The background and text match colors and therefore it looks invisible. You can change the color on line `181` in the `index.js`. Available colors can be seen on line `14`.
