### ISSUE TITLE
freez time

### ISSUE THREAD

**Issue by mrflt** [BeepIsla/csgo-commend-bot#273]
hello again...
this update is be freez see that...
the commend bot is freezed and not work for 15 minute..!!!!
<img width="942" alt="ee" src="https://user-images.githubusercontent.com/59624565/75483483-2ce2b480-59bc-11ea-9be0-631c0e252b69.png">

**Comment by BeepIsla** [comment]
Does it work if you just restart it?

**Comment by mrflt** [comment]
yes when i restart commend bot its work but i cant restart this anytime...can u fix that?

**Comment by BeepIsla** [comment]
So it happens every time you start it? At what chunk does this happen? What is your config?

**Comment by mrflt** [comment]
<img width="688" alt="cc" src="https://user-images.githubusercontent.com/59624565/75511743-5f180480-5a04-11ea-89d7-d494cb558873.png">
this is my config and next first chunk im be freezing...!!! 
no this not for everytime but usualy its freezed...

**Comment by BeepIsla** [comment]
I don't know whats causing the issue, I assume its one specific account of yours which is having some problem but I don't know what or how. I handle all possible errors from the Steam library so something must be broken in a weird way and I don't know how.

**Comment by mrflt** [comment]
thats too bad before update of commend bot i dont hve this problem...anything with new update is come...

**Comment by BeepIsla** [comment]
You can try downloading [SQLite Browser](https://sqlitebrowser.org/), open up the `accounts.sqlite` file, click on `accounts` in the dropdown at `Browse Data` and check if there is anything weird with account usernames and passwords. It **must** be something on your end not working and not the bot itself else more people would report this issue.

Try using a command prompt instead of a powershell because of #272. Maybe it actually outputs something but its invisible due to the powershell background color.

**Comment by BeepIsla** [comment]
Does this issue still exist?

**Comment by mrflt** [comment]
no fixed thank you

**Comment by mrflt** [comment]
hello again... beepisla... this problem is not fix for me... :(( i have a serious problem with this...please help me

**Comment by BeepIsla** [comment]
Does the same thing happen again?

**Comment by mrflt** [comment]
yes i have this problem...its realy bad... everything in my config is ok...but in lastest account of per chunk bot is be freez...

**Comment by BeepIsla** [comment]
Show config and bot outout

**Comment by mrflt** [comment]
i upload my config upest this post

**Comment by BeepIsla** [comment]
I just want to make sure again, there could be a tiny difference which matters.

**Comment by mrflt** [comment]
<img width="520" alt="cccccss" src="https://user-images.githubusercontent.com/59624565/75999081-f99da980-5f16-11ea-8dcb-64a8b1f14505.png">

**Comment by BeepIsla** [comment]
Copy the **entire** output of the command prompt and post it, I will be able to maybe figure out where the issue is.

**Comment by mrflt** [comment]
ok where is entire output????

**Comment by BeepIsla** [comment]
You run it > Right click > "Copy All" > Press enter > CTRL + V somewhere to paste.

**Comment by mrflt** [comment]
i close last freezed porblem and re open program...This is not a permanent problem and sometimes it does happen to me.

**Comment by BeepIsla** [comment]
So its an account issue, okay. Just come back to this issue with the logs when it happens again.

**Comment by mrflt** [comment]
ok can i send logs in the private???

**Comment by BeepIsla** [comment]
It doesn't matter, its just account names. If you want more security replace the names with like `Account1`, `Account2`, `Account3` but make sure you do it correctly because its very important its easy to distinguish between them.

**Comment by BeepIsla** [comment]
Closed due to inactivity.
