### ISSUE TITLE
help pls

### ISSUE THREAD

**Issue by BABoom12** [BeepIsla/csgo-commend-bot#274]
(node:17472) UnhandledPromiseRejectionWarning: TypeError: serializeError.serializeError is not a function
    at C:\Users\Acer\Desktop\csgo-commend-bot-master\helpers\Bots.js:115:28
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:17472) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4) error
![image](https://user-images.githubusercontent.com/28574138/75561993-90b6bd00-5a50-11ea-8ba9-623273ef41f6.png)

**Comment by BeepIsla** [comment]
Update your node modules using `npm update` or `npm install`, if it doesn't work make sure your `package.json` and `package-lock.json` are up-to-date.

**Comment by BABoom12** [comment]
i got this
npm WARN deprecated request@2.88.2: request has been deprecated, see
https://github.com/request/request/issues/3142
npm ERR! path
C:\Users\Acer\Desktop\csgo-commend-bot-master\node_modules\.bin\uuid.cmd
npm ERR! code EEXIST
npm ERR! Refusing to delete
C:\Users\Acer\Desktop\csgo-commend-bot-master\node_modules\.bin\uuid.cmd:
is outside C:\Users\Acer\Desktop\csgo-commend-bot-master\node_modules\uuid
and not a link
npm ERR! File exists:
C:\Users\Acer\Desktop\csgo-commend-bot-master\node_modules\.bin\uuid.cmd
npm ERR! Move it away, and try again.

npm ERR! A complete log of this run can be found in:
npm ERR!
C:\Users\Acer\AppData\Roaming\npm-cache\_logs\2020-02-28T15_45_30_198Z-debug.log

În vin., 28 feb. 2020 la 17:39, Isla <notifications@github.com> a scris:

**Comment by BeepIsla** [comment]
Delete `node_modules` and run `npm install`

**Comment by BABoom12** [comment]
love u bro!

În vin., 28 feb. 2020 la 17:46, Isla <notifications@github.com> a scris:

**Comment by BABoom12** [comment]
u can help me whit some accounts?

În vin., 28 feb. 2020 la 17:48, XGamer Hasteck <razvanrazvan836@gmail.com>
a scris:

**Comment by BeepIsla** [comment]
No, accounts are out of scope and your own issue. If you want accounts buy them from someone or generate them on a site such as https://accgen.cathook.club/

**Comment by BABoom12** [comment]
hi u have some proxies pls

În vin., 28 feb. 2020 la 17:54, Isla <notifications@github.com> a scris:

**Comment by BABoom12** [comment]
or why i get this error pls help
[image: image.png]

În lun., 9 mar. 2020 la 15:47, XGamer Hasteck <razvanrazvan836@gmail.com> a
scris:

**Comment by BABoom12** [comment]
or this
 [lulibuh] Failed to login and has been marked as invalid (1/15) {
  code: 'ECONNRESET',
  name: 'Error',
  message: 'socket hang up',
  stack: 'Error: socket hang up\n' +
    '    at connResetException (internal/errors.js:559:14)\n' +
    '    at Socket.socketOnEnd (_http_client.js:440:23)\n' +
    '    at Socket.emit (events.js:214:15)\n' +
    '    at endReadableNT (_stream_readable.js:1178:12)\n' +
    '    at processTicksAndRejections
(internal/process/task_queues.js:77:11)'
}
 [maizeecawaii] Failed to login and due to proxy timeout (2/15) {
  name: 'Error',
  message: 'Proxy connection timed out',
  stack: 'Error: Proxy connection timed out\n' +
    '    at ClientRequest.<anonymous>
(C:\\Users\\Acer\\Desktop\\csgo-commend-bot-master\\node_modules\\steam-user\\components\\connection_protocols\\tcp.js:69:28)\n'
+
    '    at ClientRequest.emit (events.js:209:13)\n' +
    '    at Socket.emitRequestTimeout (_http_client.js:687:40)\n' +
    '    at Object.onceWrapper (events.js:297:20)\n' +
    '    at Socket.emit (events.js:209:13)\n' +
    '    at Socket._onTimeout (net.js:434:8)\n' +
    '    at listOnTimeout (internal/timers.js:531:17)\n' +
    '    at processTimers (internal/timers.js:475:7)'
}
events.js:186
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at connResetException (internal/errors.js:559:14)
    at Socket.socketOnEnd (_http_client.js:440:23)
    at Socket.emit (events.js:214:15)
    at endReadableNT (_stream_readable.js:1178:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
Emitted 'error' event on SteamUser instance at:
    at ClientRequest.<anonymous>
(C:\Users\Acer\Desktop\csgo-commend-bot-master\node_modules\steam-user\components\connection_protocols\tcp.js:74:14)
    at ClientRequest.emit (events.js:209:13)
    at Socket.socketOnEnd (_http_client.js:440:9)
    at Socket.emit (events.js:214:15)
    at endReadableNT (_stream_readable.js:1178:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  code: 'E


În lun., 9 mar. 2020 la 16:29, XGamer Hasteck <razvanrazvan836@gmail.com> a
scris:

**Comment by BeepIsla** [comment]
This error comes from not working/blocked proxies.

**Comment by BABoom12** [comment]
ok thx, u can give me some pls?

În lun., 9 mar. 2020 la 16:51, Isla <notifications@github.com> a scris:

**Comment by BABoom12** [comment]
i can pay it

În lun., 9 mar. 2020 la 16:57, XGamer Hasteck <razvanrazvan836@gmail.com> a
scris:

**Comment by BeepIsla** [comment]
No, I don't use proxies. Don't ask about buying proxies on this repository, its not related to the actual bot.
