### ISSUE TITLE
report all failed

### ISSUE THREAD

**Issue by crx9** [BeepIsla/csgo-commend-bot#275]
[sabapathy13] Failed to report (49/50) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\nnnn\\Desktop\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:531:17)\n' +
    '    at processTimers (internal/timers.js:475:7)'
}
 [s88907477] Failed to report (50/50) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\nnn\\Desktop\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:531:17)\n' +
    '    at processTimers (internal/timers.js:475:7)'

**Comment by BeepIsla** [comment]
What server?

**Comment by crx9** [comment]
> What server?

wingman

**Comment by BeepIsla** [comment]
As per [CHANGELOGS](https://github.com/BeepIsla/csgo-commend-bot/blob/master/CHANGELOG.md#261):

> - Fixed commend/report bot
> - - No longer works on Competitive and Wingman
