### ISSUE TITLE
Using server as method?

### ISSUE THREAD

**Issue by OfficialLasse** [BeepIsla/csgo-commend-bot#276]
So how do you use the server method after your new update? I am not using any fetcher account(and you removed that), so how can I do it?
**Config**
```
{
	"commend": {
		"friendly": 250,
		"teaching": 250,
		"leader": 250
	},
	"report": {
		"aimbot": 10,
		"wallhack": 10,
		"speedhack": 10,
		"teamharm": 10,
		"abusive": 10
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/id/something",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"steamWebAPIKey": "xxx",
	"disableUpdateCheck": false
}

```

**Version**
- NodeJS: `12.9.1`
- Script version: `2.7.1`

**Comment by xhujova** [comment]
Didint udnerstand your question fully but ill try :D 

- After this method you dont need to be in any server basiclly you can just run csgo and stay at dasboard and the commends will come i tried it my self over night, but also after you join a random server not wingman or competitive just start your bot, it will automaticlly detect the server ip for you.

**Comment by OfficialLasse** [comment]
> Didint udnerstand your question fully but ill try :D

That was exactly what I meant. I figured it out, but thanks for the reply.

**Comment by BeepIsla** [comment]
You still need to be in a server, you need an auth ticket which you get when joining a server. If you leave the auth ticket stay valid for a bit longer too so during that time you can still commend bot.
