### ISSUE TITLE
Timeout 

### ISSUE THREAD

**Issue by Yaman3131** [BeepIsla/csgo-commend-bot#277]
Failed to log into Steam using account as target Error: GC connection timeout - Hello
    at SteamUser.loggedOn (C:\Users\ESAT\Desktop\csgo-commend-bot-master\helpers\account.js:128:14)

what can ı do ? ı wrote steam web api and target ı try login method.

 If ı try server method : 

name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\ESAT\\Desktop\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:531:17)\n' +
    '    at processTimers (internal/timers.js:475:7)'

**Comment by xSuspect** [comment]
Fixed commend/report bot
No longer works on Competitive and Wingman

**Comment by Yaman3131** [comment]
hm its bad :/

**Comment by Yaman3131** [comment]
'Casual gamemodes such as Deathmatch/Casual/etc continue to work including community servers.'

how can ı that ?
