### ISSUE TITLE
Failed to commend 20/20

### ISSUE THREAD

**Issue by xhujova** [BeepIsla/csgo-commend-bot#278]
So basiclly ive saw some threads like this but the yare using proxies and im not, sometimes i get all of them working 20/20 but sometimes theres is like 20 chunks going 20/20 failed to commend and idk what is causing it https://gyazo.com/e2aa3095734a965138fd2262762beecd

**Comment by BeepIsla** [comment]
Show config

**Comment by xhujova** [comment]
{
	"commend": {
		"friendly": 20,
		"teaching": 20,
		"leader": 20
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/id/tkiit/",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"steamWebAPIKey": "",
	"disableUpdateCheck": false
}

**Comment by BeepIsla** [comment]
And you do this?

1. Join server

2. Put your id in target in the config

3. Run bot

**Comment by xhujova** [comment]
yes

**Comment by BeepIsla** [comment]
What type of server do you join?

**Comment by xhujova** [comment]
any not wingman or competitive

**Comment by BeepIsla** [comment]
I don't know what the cause of this could be, do you have another target you can try it with? Maybe its related to the account being invisible though I could not replicate that, I went invisible on Steam and it kept working.

**Comment by xhujova** [comment]
yeah i tried it on several people same thing sometimes it works sometimes half of the commends goes though and other half just failed to commend

**Comment by BeepIsla** [comment]
Do you use any VPN?

**Comment by xhujova** [comment]
no

**Comment by xhujova** [comment]
after the fix u realeased i mostly get all of the commends but the last one always fails either is 18/20 or 19/20

**Comment by BeepIsla** [comment]
Weird, the update didnt actually change anything regarding your issue.

**Comment by UnMouton** [comment]
I have the exact same issue, I get a timeout error with some chunks while the others are working "perfectly" (same issue, 19/20, the last one times out).

**Comment by BABoom12** [comment]
i have 100/100 isue

**Comment by BeepIsla** [comment]
Closed due to inactivity.
