### ISSUE TITLE
Only sending 20 commends but i have 81 accounts and changed config 

### ISSUE THREAD

**Issue by Tewni** [BeepIsla/csgo-commend-bot#282]
Chunk 1/1 finished with 19 successful commends and 1 failed commend
 Finished all chunks with a total of 19 successful and 1 failed commend

{
	"commend": {
		"friendly": 60,
		"teaching": 60,
		"leader": 60
	},
	"report": {
		"aimbot": 10,
		"wallhack": 10,
		"speedhack": 10,
		"teamharm": 10,
		"abusive": 10
	},
	"account": {
		"username": "Senatorzer",
		"password": "doWhatuLike2",
		"sharedSecret": ""
	},
	"proxy": {
		"enabled": true,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "LOGIN",
	"target": "",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"steamWebAPIKey": "\"XXXXXXXXXX","\",": null,
	"disableUpdateCheck": false
}

Completes with 20 commends only. 1 chunk.
Proxys are working and HQ

**Comment by BeepIsla** [comment]
I can't tell if this is your real password but I hope not.

**Comment by BeepIsla** [comment]
Duplicate config
