### ISSUE TITLE
report bot

### ISSUE THREAD

**Issue by mrflt** [BeepIsla/csgo-commend-bot#286]
hello, i want to send report from report bot but dont send reports why????
<img width="481" alt="rep" src="https://user-images.githubusercontent.com/59624565/75776171-b3a2e300-5d68-11ea-8540-824ec02613e7.png">

**Comment by BeepIsla** [comment]
What type of server are you trying to report on?

**Comment by mrflt** [comment]
i dont have a server but in lastest versions of this program i have a matchid option but in this version i dont have this option what am i do?

**Comment by BeepIsla** [comment]
This is not what I am talking about. What server is your target on? Competitive, Community, Wingman, Local server?

**Comment by mrflt** [comment]
competitive, i dont know this target is online now or not!! this player is played with us and he is cheater i want to report him...what can i do?

**Comment by BeepIsla** [comment]
You cannot commend/report bot on Valve Competitive/Wingman servers.

**Comment by mrflt** [comment]
oh ok thankyou...
