### ISSUE TITLE
Failed to log in within given 60000ms

### ISSUE THREAD

**Issue by Mad02** [BeepIsla/csgo-commend-bot#287]
[19jert51] Failed to login and has been marked as invalid (1/10) {
  name: 'Error',
  message: 'Failed to log in within given 60000ms',
  stack: 'Error: Failed to log in within given 60000ms\n' +
    '    at Timeout._onTimeout (C:\\Users\\knamp\\Desktop\\csgo-commend-bot-master\\helpers\\account.js:51:12)\n' +
    '    at listOnTimeout (internal/timers.js:531:17)\n' +
    '    at processTimers (internal/timers.js:475:7)'
}

Whats the Problem there?

**Comment by BeepIsla** [comment]
Account failed to establish a connection to the CSGO network for 60 seconds.

**Comment by Mad02** [comment]
And why the accounts are workin. I try it out with normaly log in in steam

**Comment by Mad02** [comment]
How can i fix that?

**Comment by BeepIsla** [comment]
I don't know. They just fail to connect to CSGO for some reason. That's all I can say.

**Comment by Mad02** [comment]
I tried it one time with 10 accounts on one steam account it works, with other 10 accounts i tried it again on the same account how before and then came the error code

**Comment by BeepIsla** [comment]
I told you everything I know.

**Comment by Mad02** [comment]
Do you have some accounts they safely works?

**Comment by BeepIsla** [comment]
The only accounts I use have been generated in late 2018 and they all work fine, I do not share accounts. Other users use the bot without any problems too. Make sure [CSGO & Steam are online](http://steamstat.us/) and the account is not banned.

**Comment by Mad02** [comment]
I need only one account to try it out if it is this problem

**Comment by BeepIsla** [comment]
Generate an account at https://accgen.cathook.club/

**Comment by Mad02** [comment]
i will try it with this generated account i write in like 10 minutes if it works

**Comment by Mad02** [comment]
it works xD to they need a level 2 account?

**Comment by BeepIsla** [comment]
No, accounts generated at https://accgen.cathook.club/ are fresh accounts with no level, no playtime, nothing except Steam Guard disabled and CSGO License. Both of which are not related to your problem.

**Comment by Mad02** [comment]
Okay then i need a proxy i think

**Comment by BeepIsla** [comment]
I don't think proxies will help.

**Comment by Mad02** [comment]
For creating accouns there i need proxies

**Comment by BeepIsla** [comment]
Yes because of Steam limitation.

But generating accounts is out of scope for this project and therefore off-topic and not related to the commend bot itself.
