### ISSUE TITLE
Failed to commend: Timeout

### ISSUE THREAD

**Issue by LegendFTW1** [BeepIsla/csgo-commend-bot#289]
**Detailed bug description**
It doesn't send any commends and gives the error below

**Error**
```
 [H6URTtnr1DzO] Failed to commend (30/30) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\XXXX\\OneDrive\\Documents\\CSGO Commend Bot\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
}
```

**Config**
```
{
	"commend": {
		"friendly": 30,
		"teaching": 30,
		"leader": 30
	},
	"report": {
		"aimbot": 10,
		"wallhack": 10,
		"speedhack": 10,
		"teamharm": 10,
		"abusive": 10
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/id/eyad16/",
	"perChunk": 30,
	"betweenChunks": 5000,
	"cooldown": 28800000,
	"steamWebAPIKey": "XXXX",
	"disableUpdateCheck": false
}
```

**Version**
- NodeJS: `v12.16.1`
- Script version: `2.7.1`

**Comment by 45656456kawai** [comment]
the max per chunk should be 20 or less and minimum wait inbetween should be greater than 5 unless using proxy

that's what I'm using no error whatsoever script still running just fine for over 48 hours now.

**Comment by LegendFTW1** [comment]
> the max per chunk should be 20 or less and minimum wait inbetween should be greater than 5 unless using proxy
> 
> that's what I'm using no error whatsoever script still running just fine for over 48 hours now.

tried 15 still doesn't work

**Comment by BeepIsla** [comment]
What type of server is the target on?

**Comment by LegendFTW1** [comment]
> What type of server is the target on?

was trying on deathmatch didn't work so when I did it in community server worked!
