### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by raza-ART** [BeepIsla/csgo-commend-bot#291]
i always get this error as i try to npm install in CMD.please help me

npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\AGA\Desktop\csgo-commend-bot-master\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\AGA\Desktop\csgo-commend-bot-master\package.json'
npm WARN csgo-commend-bot-master No description
npm WARN csgo-commend-bot-master No repository field.
npm WARN csgo-commend-bot-master No README data
npm WARN csgo-commend-bot-master No license field.

up to date in 7.419s
found 0 vulnerabilities

**Comment by BeepIsla** [comment]
Looks like you didn't actually download and extract all the files.

**Comment by raza-ART** [comment]
thnks for your time i figure out my problem and solved it 
sry for disturbing you
