### ISSUE TITLE
IM GETTING THIS ERROR 

### ISSUE THREAD

**Issue by raza-ART** [BeepIsla/csgo-commend-bot#292]
Could not find proxy file "proxies" (C:\Users\AGA\Desktop\csgo-commend-bot-master\csgo-commend-bot-master\proxies)

**Comment by BeepIsla** [comment]
Either disable proxies or put in the name of your proxies file correctly.

**Comment by raza-ART** [comment]
name is correctly entered idk why its giving error

**Comment by BeepIsla** [comment]
Then the file name in your config is missing the file extension

**Comment by raza-ART** [comment]
how can i fix that?

**Comment by BeepIsla** [comment]
Add the file extension... If its just a text file the extension is usually `.txt`.

**Comment by raza-ART** [comment]
i did it still same error

**Comment by raza-ART** [comment]
and one more qus can i use 100account without proxy

**Comment by BeepIsla** [comment]
Just [Enable File Extensions](https://www.wikihow.com/Configure-Your-Computer-to-See-File-Extensions%3famp=1) and write the full filename with extension in the config. Also make sure the file is actually in the same directory.

---

Limit seems to be 20 per one IP.
