### ISSUE TITLE
How do you get the sharedSecret please

### ISSUE THREAD

**Issue by yxw770** [BeepIsla/csgo-commend-bot#293]
How do you get the sharedSecret please

**Comment by BeepIsla** [comment]
The shared secret is used to automatically generate a Mobile Steam Guard Code to log into your Steam account. It does not exist if you have Email Steam Guard or no Steam Guard at all.

You do not need to fill in the `sharedSecret` field, you can just leave it empty and the script will ask you to input your Steam Guard code, just type in the code and press enter.

If you do want to use your shared secret for some reason you have to root your phone, some people don't want this so as I said you can just leave it empty. For more information on how to get access to your shared secret I recommend reading [this](https://github.com/SteamTimeIdler/stidler/wiki/Getting-your-%27shared_secret%27-code-for-use-with-Auto-Restarter-on-Mobile-Authentication).
