### ISSUE TITLE
General Question

### ISSUE THREAD

**Issue by AlexanderQueen** [BeepIsla/csgo-commend-bot#294]
1.Why for example with 47 operational accounts you get only 15 commends? How to get all 47.
2.What is chunks?
3. How to select to commend only the branch what you need( for example only friendly). Not random

**Comment by BeepIsla** [comment]
Read the README, it tells you everything you need. Its very simple.

1. Your `friendly`, `teaching`, and `leader` values in your config determine how many commends are sent.
2. You cannot infinitely commend, you can only send ~20 commends per 5 minutes per IP. Chunks are there to split the required commends into groups of 20's, a group is a chunk, between each chunk it waits 5 minutes.
3. Change `friendly`, `teaching`, and `leader` in your config to the amount you want. You can do 0 friendly and leader but 10 teaching for example.

**Comment by AlexanderQueen** [comment]
I read README, but nothing at subject. I know what im asking.

https://imgur.com/a/qfKa71H

Logic from a group of 20 you should get 20 commends and not 15.

**Comment by BeepIsla** [comment]
Read what I said:

> Your `friendly`, `teaching`, and `leader` values in your config determine how many commends are sent.

Change the actual commend amount you want to send.

**Comment by AlexanderQueen** [comment]
Works good now.
