### ISSUE TITLE
Failed to commend

### ISSUE THREAD

**Issue by boostacc** [BeepIsla/csgo-commend-bot#295]
I often see this error. I use a proxy, and on my real ip ( I observe the delay time)
 get an error on all 20 accounts at once

[0b3qY7Jcfx3z] Failed to commend (20/20) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\new Like bot\\csgo-commend-bot-master-random\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:531:17)\n' +
    '    at processTimers (internal/timers.js:475:7)'
}

**Config**
```
Your "config.json" - Censor your API Key and account details
```
{
	"commend": {
		"friendly": 1000,
		"teaching": 1000,
		"leader": 1000
	},
	"report": {
		"aimbot": 0,
		"wallhack": 0,
		"speedhack": 0,
		"teamharm": 0,
		"abusive": 0
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"proxy": {
		"enabled": true,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/profiles/76561198955934721/",
	"perChunk": 20,
	"betweenChunks": 38000,
	"cooldown": 28800000,
	"steamWebAPIKey": "",
	"disableUpdateCheck": false
**Version**
- NodeJS: `v12.8.0` (You can find this using `node -v`)
- Script version: `2.7.1` (You can find this in **your** `package.json` file under `version`)

**Comment by BeepIsla** [comment]
What server are you trying to commend on?

**Comment by boostacc** [comment]
Local server" created using the - "map dust 2" command ( for example) 
And I get some likes on it , but a lot of errors. Maybe I should work with other servers? And if so, which ones?

**Comment by BeepIsla** [comment]
During development I always just tested it on Valve Deathmatch servers but it should work on all servers except Valve Competitive and Valve Wingman.

---

> Failed to send message: Timeout

Means it tried to send a commend but CSGO didn't respond to it so the commend from the bot didn't get applied. Other errors mean entirely different things many people seemingly assume every error means the same. Its possible you have other errors which are related to your proxies being blocked by Steam for example.

**Comment by boostacc** [comment]
The proxy is not exactly blocked because it sends for example 3 out of 20, or 14 out of 20 ( the rest with this error) This happens with my personal ip address. Is there anything else I can turn my attention to ? For me, what is strange is that it works only partially and not always. If strictly Yes or strictly no, it would be clear what to do and how to decide)

**Comment by BeepIsla** [comment]
This is very weird, I don't know what the cause of this could be. My only idea is that maybe its a problem with the accounts. Do you maybe use banned accounts or something?

You can also try making a backup of your `accounts.sqlite` then delete the original one (Always make sure to keep a backup, it stores all important information not only login details), then just add freshly created/generated accounts and check if that works.

**Comment by boostacc** [comment]
Dummy accounts (autoreg) Without blocking. And the fact that you can not delete accounts.sqlite, I didn't know . how important is it not to do this ? Sorry for my eng

**Comment by boostacc** [comment]
I am surprised that you create and support so many interesting projects and all this for free.... 
You are an incredible enthusiast who probably loves his job very much

**Comment by BeepIsla** [comment]
Thanks, I love doing what I do.

Your `accounts.sqlite` stores bot usernames, passwords, last commend time, and a history of who each bot has commended.

The last part is the most important part, if you for example commend bot a person, and then later do it again you don't want the script to re-use accounts which already commended earlier. You can only commend a player once and never the same player again.

If you would delete your `accounts.sqlite` the script would re-use accounts which have already commended the player, which does not work and results in "Already commended response code 2" (Basically an error) messages. The script will try rebuilding the commend history for every accounts but the process is slow.

Its a big time waste having the script rebuild commend history especially with a lot of accounts and that's why I always say: Never delete your `accounts.sqlite` and maybe even make a backup of it every few weeks if you use it a lot.

**Comment by boostacc** [comment]
Oh, I'll know, thank you very much. It turns out the perfect thing. I boost 100 likes for player x and if I want to boost 100 more likes, the bot will not use the previously used accounts. Brilliant! It's a pity I haven't seen this information before

p. s not knowing about this chip, created a lot of folders with "bot" and split accounts into parts

Thank you again <3

**Comment by BeepIsla** [comment]
Is the issue resolved or do you still have the problem? Have you tried using different accounts?

**Comment by boostacc** [comment]
I'm currently testing, can I unsubscribe later?

Also, the question is , does the program use a proxy list in the order of the queue? 
 For example, I have 10 proxies, which means that the program will use from 1 to 10, and then again the first proxy?

**Comment by boostacc** [comment]
Is it possible that you will ever add a function that the bot will put likes exactly up to the specified value? 

 for example, you need 1000 likes, the bot will use accounts until exactly 1000 likes are sent

Now the bot uses the specified number of accounts, but may not get the desired number of likes

**Comment by BeepIsla** [comment]
> I'm currently testing, can I write later?

Yes. I will also be gone for a few hours anyways.

> Also, the question is , does the program use a proxy list in the order of the queue?

Yes proxy list is used in order and once the end is reached it will wrap back around to first.

> Is it possible that you will ever add a function that the bot will put likes exactly up to the specified value?

No, just look in-game, do the math and enter the values needed.

**Comment by boostacc** [comment]
Everything seems to be working 
Then the last question and close the topic

Do I understand correctly that we have a delay time of 300000ms, but when we use a proxy, for example 10 PCs, then I can set the delay time to 10 times less

**Comment by BeepIsla** [comment]
Yes. One IP/Proxy can do ~20 commends per 5 minutes.
