### ISSUE TITLE
Instead of adding the commends it just subtracts it/decreases it/retains

### ISSUE THREAD

**Issue by K2erdnA** [BeepIsla/csgo-commend-bot#296]
**Detailed question description**
Why does it subtract instead of adding commends?
![1](https://user-images.githubusercontent.com/35741335/76360996-037d3d80-6359-11ea-9dc8-1c1fda5dcada.jpg)
![2](https://user-images.githubusercontent.com/35741335/76361002-05df9780-6359-11ea-82b2-66d25842b552.jpg)

When i do commends like 69 commends it sometimes decreases the commends that i have or retains it.

**Config**
```
{
	"commend": {
		"friendly": 69,
		"teaching": 11,
		"leader": 5
	},
	"report": {
		"aimbot": 10,
		"wallhack": 10,
		"speedhack": 10,
		"teamharm": 10,
		"abusive": 10
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/id/pokeCS",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"steamWebAPIKey": "XXX",
	"disableUpdateCheck": false
}

```

**Version**
- NodeJS: `v12.9.1`
- Script version: `2.7.1`

**Comment by BeepIsla** [comment]
Did you at one point delete your `accounts.sqlite`?

**Comment by K2erdnA** [comment]
> Did you at one point delete your `accounts.sqlite`?

yes, but this is the first time i've used the commend bot again in months....

**Comment by BeepIsla** [comment]
If an account commends you with for example 1/1/1 (Teacher, Leader, Friendly) and then later the same account commends you 0/0/1 (Only Friendly) then your count on Teacher and Leader will go down.

Its possible, if you put in the same accounts into the database again as you did months ago, it did exactly that with some of the accounts.

**Comment by K2erdnA** [comment]
so what do i do to fix it

**Comment by K2erdnA** [comment]
> If an account commends you with for example 1/1/1 (Teacher, Leader, Friendly) and then later the same account commends you 0/0/1 (Only Friendly) then your count on Teacher and Leader will go down.
> 
> Its possible, if you put in the same accounts into the database again as you did months ago, it did exactly that with some of the accounts.

so how do i fix it?

**Comment by BeepIsla** [comment]
2 ways:

- Use different accounts
- Set Teacher, Leader, Friendly all to the same value, that way if a bot has already commended you it will just get a code 2 (Already commended) response. The script will slowly rebuild commend history but it will take a while.

**Comment by K2erdnA** [comment]
> 2 ways:
> 
> * Use different accounts
> * Set Teacher, Leader, Friendly all to the same value, that way if a bot has already commended you it will just get a code 2 (Already commended) response. The script will slowly rebuild commend history but it will take a while.

so i have to dump the 197 accounts that i already have and make new ones? will the commend bot use those accounts again if i add more accounts?

**Comment by BeepIsla** [comment]
The script will use whatever account is available, so if you just add onto it yes it will still re-use the old accounts.

**Comment by K2erdnA** [comment]
> The script will use whatever account is available, so if you just add onto it yes it will still re-use the old accounts.

it works now this thread can now be close
