### ISSUE TITLE
Time Out And skipping lines

### ISSUE THREAD

**Issue by KarateOgd** [BeepIsla/csgo-commend-bot#298]
https://prnt.sc/rez5s7
https://prnt.sc/rez65y
every time i try to send commends say timeout
and skip lines

**Comment by BeepIsla** [comment]
The empty lines are anonymous server authentication, they use the same color as your powershell this is why they appear invisible.

---

What server are you trying to commend on?

**Comment by KarateOgd** [comment]
in competitive match dont work!
closed!
