### ISSUE TITLE
Only send 100 commends per server

### ISSUE THREAD

**Issue by KarateOgd** [BeepIsla/csgo-commend-bot#299]
i just can send 100 commends p/ server
fixes?

**Comment by BeepIsla** [comment]
Please explain more, what do you mean?

**Comment by KarateOgd** [comment]
I send 100 commends, after all accs says TimeOut

**Comment by BeepIsla** [comment]
And if you change server it works again?

**Comment by KarateOgd** [comment]
I dnt tested this
..

**Comment by BeepIsla** [comment]
Try that if possible. Maybe its a server limit which cannot be bypassed.

**Comment by KarateOgd** [comment]
closed
