### ISSUE TITLE
stuck in 394 , 389 , 390 , i tried reseting the commend bot i tried waiting i tried reseting my steamwebApi nothing works pls help

### ISSUE THREAD

**Issue by JamesGordan11** [BeepIsla/csgo-commend-bot#301]
**Detailed question description**
A clear and concise description of your question.

**Config**
```
Your "config.json" - Censor your API Key and account details
```

**Version**
- NodeJS: `vXX.XX.X` (You can find this using `node -v`)
- Script version: `X.X.X` (You can find this in **your** `package.json` file under `version`)

**Comment by BeepIsla** [comment]
Don't put your entire issue in the title. Actually fill out the form. There is so much information missing here.

**Comment by JamesGordan11** [comment]
> Don't put your entire issue in the title. Actually fill out the form. There is so much information missing here.

i am new to github i didn't know how to fill it properly , my question is why my commends are stuck ? even thought i tried changing commend accounts i  tried reseting the database i even tried reseting my apikey nothing works

**Comment by BeepIsla** [comment]
I cant help without seeing your config, without knowing what server you are trying to commend on, etc. This all needs more info.
