### ISSUE TITLE
Stuck in certain number of comments i can't commend more

### ISSUE THREAD

**Issue by JamesGordan11** [BeepIsla/csgo-commend-bot#302]
hello every thing is working propely i have alot of steam account to use them to commend my main 
i managed to commend my main around 350 commends in 3 days ,  when i commend it shows that i 
 received my commends but  commends are stuck on 393 , 389 , 385 , i tried reseting database i tried using a different apikey i even tried another ip , what the problem ?
i tried commending another account it works so the problem is not my commend accounts
did any one encounter this problem before ?
<img width="243" alt="commends" src="https://user-images.githubusercontent.com/62112046/76611320-9dd8af00-651a-11ea-95e4-2c494c79313d.PNG">

**Comment by crx9** [comment]
one bot only can commend ur account once,.resetting the database won't work

**Comment by crx9** [comment]
u can use new bots to commend ur account

**Comment by JamesGordan11** [comment]
> one bot only can commend ur account once,.resetting the database won't work

i tried using another accounts i have over 25k accounts but my commends are still stuck

**Comment by BeepIsla** [comment]
Whats your output on the bot? What does it say? Successfully commend or Already commended?

**Comment by JamesGordan11** [comment]
> Whats your output on the bot? What does it say? Successfully commend or Already commended?

if it shows already commended in red i don't get green notification in game , but the problem is it shows in cmd that it commeneded me and in game it displays congratulation , but commend numbers won't increase

**Comment by BeepIsla** [comment]
I don't know why this happens. I can't do anything against it.

**Comment by Raxana7** [comment]
@JamesGordan11 are u sending multiple persons commend with same web api and same server?

**Comment by BeepIsla** [comment]
No more information about this is available. There is no reason to keep this issue open.
