### ISSUE TITLE
Failed to login and has been marked as invalid

### ISSUE THREAD

**Issue by sohiebdz40** [BeepIsla/csgo-commend-bot#303]
i like 300-400 accounts all of them valid and i get like for most accounts this error
Failed to login and has been marked as invalid

**Comment by BeepIsla** [comment]
Cant help without seeing the error.

**Comment by sohiebdz40** [comment]
![Untitled](https://user-images.githubusercontent.com/61115729/76660361-08b8d300-6579-11ea-8483-f6940f3ddd2b.png)

**Comment by BeepIsla** [comment]
Nothing much I can say here other than Steam/CSGO refuses connection. Best you can do is try using different accounts and see if it works with them. If it doesn't its a problem with your connection/Steam connection ([Make sure Steam is not down](https://steamstat.us/)), if it does work its a problem with the accounts, make sure not to use banned accounts.
