### ISSUE TITLE
Weird commend bot problem.

### ISSUE THREAD

**Issue by unnamed01X** [BeepIsla/csgo-commend-bot#304]
hey, i got the problem, about 2/3days ago, everything was fine, i commend my second account with 100 commends.
Today earlier, i got this problem:
"Finished all chunks with a total of 0 successful and 60 failed commends"

it's just the finished text,  but there was weird things like "logged onto" etc http://prntscr.com/rgorg3

in my config file everything is fine, i promies. any tips? thanks.

**Comment by BeepIsla** [comment]
If you don't want to show your config and just say "I promise is everything fine" then no, I don't have any tips. Use different accounts and see if the issue continues to exist.

**Comment by unnamed01X** [comment]
i said that i promise that everything is fine because im not amatour at this point, im using commendbot since half of year or longer. So i know how it work.
i can show you but you'll see that everything is okay with that.

{
	"commend": {
		"friendly": 60,
		"teaching": 60,
		"leader": 60
	},
	"report": {
		"aimbot": 10,
		"wallhack": 10,
		"speedhack": 10,
		"teamharm": 10,
		"abusive": 10
	},
	"account": {
		"username": "xxxxx",
		"password": "xxxxx",
		"sharedSecret": ""
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/profiles/",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"steamWebAPIKey": "**my api key**",
	"disableUpdateCheck": false
}

**Comment by BeepIsla** [comment]
Its can't hurt to double and quadruple check it.

As I said, try doing it with new freshly created accounts and see if the issue continues.

**Comment by unnamed01X** [comment]
I generated my accounts about half a year ago, I have over 25,000, Do you currently recommend some account generator (to check if the new commandbot will work) because I don't want to do it manually.

**Comment by BeepIsla** [comment]
The only account generator I know is accgen.cathook.club

**Comment by unnamed01X** [comment]
okay, everything works fine, i solve my problem. thank
