### ISSUE TITLE
Timeout on Report Botting

### ISSUE THREAD

**Issue by K2erdnA** [BeepIsla/csgo-commend-bot#305]
Still doesn't work it gives me timeout. First time to use in a week and it still doesn't work. My cooldown settings and perchunk are default but it still doesn't work even in report botting.

**Config**
```
{
	"commend": {
		"friendly": 0,
		"teaching": 0,
		"leader": 0
	},
	"report": {
		"aimbot": 50,
		"wallhack": 50,
		"speedhack": 50,
		"teamharm": 50,
		"abusive": 50
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "REPORT",
	"method": "SERVER",
	"target": "https://steamcommunity.com/profiles/76561198844851243",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"steamWebAPIKey": "xxx",
	"disableUpdateCheck": false
}

```

**Version**
- NodeJS: `v12.9.1`
- Script version: `2.7.1`

**Comment by BeepIsla** [comment]
You cannot report bot on Valve Competitive/Valve Wingman servers.

**Comment by K2erdnA** [comment]
> You cannot report bot on Valve Competitive/Valve Wingman servers.

so i cant report bot someone that i played with on mm?

**Comment by BeepIsla** [comment]
Correct. This has been fixed since the last time Valve patched the bot.

**Comment by K2erdnA** [comment]
> Correct. This has been fixed since the last time Valve patched the bot.

okay thanks
