### ISSUE TITLE
How and Why are some accounts "not working" ?

### ISSUE THREAD

**Issue by K2erdnA** [BeepIsla/csgo-commend-bot#306]
**Detailed question description**
How and why did some of my accounts stopped working? I check DBManager and checked the "List not working accounts" and it displayed 47 accounts. Why did they stop working? I check one of those accounts and they weren't VAC banned on csgo.

**Config**
```
{
	"commend": {
		"friendly": 27,
		"teaching": 27,
		"leader": 27
	},
	"report": {
		"aimbot": 50,
		"wallhack": 50,
		"speedhack": 50,
		"teamharm": 50,
		"abusive": 50
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 5
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/id/pokeCS/",
	"perChunk": 30,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"steamWebAPIKey": "xxxx",
	"disableUpdateCheck": false
}

```

**Version**
- NodeJS: `v12.9.X` (You can find this using `node -v`)
- Script version: `2.7.1` (You can find this in **your** `package.json` file under `version`)

**Comment by BeepIsla** [comment]
Did you previous have an issue which was solved either by updating NodeJS or updating/re-installing the modules?

**Comment by K2erdnA** [comment]
> Did you previous have an issue which was solved either by updating NodeJS or updating/re-installing the modules?

i think so...

**Comment by BeepIsla** [comment]
Then this is likely the reason, if there is an error anywhere while the account is doing its thing the script just assumes its the account's fault and marks them as invalid.

They also get marked as invalid when [Steam and/or CSGO are offline](http://steamstat.us/) or Valve decides to ban your accounts for whatever reason.

**Comment by K2erdnA** [comment]
> Then this is likely the reason, if there is an error anywhere while the account is doing its thing the script just assumes its the account's fault and marks them as invalid.
> 
> They also get marked as invalid when [Steam and/or CSGO are offline](http://steamstat.us/) or Valve decides to ban your accounts for whatever reason.

I managed to fix it by setting them operational in dbmanager.
Suggestion: add a feature which automatically sets non operational accounts as operational?

**Comment by BeepIsla** [comment]
I can add the possibility to separate usernames in the "Set account as operational" by commas so you can more easily set multiple accounts as working at once. Simple and easy solution I think.
