### ISSUE TITLE
Error when Reporting

### ISSUE THREAD

**Issue by MikhaelLauda** [BeepIsla/csgo-commend-bot#31]
node index_report.js https://steamcommunity.com/profiles/76561198839779881/ 5 3325774506517070139

and i got this error

![image](https://user-images.githubusercontent.com/35010997/52079778-e52b0700-25c8-11e9-8378-61281c559027.png)

**Comment by BeepFelix** [comment]
Define an API Key in your config.json

**Comment by MikhaelLauda** [comment]
Yes, i have the API Key already
![image](https://user-images.githubusercontent.com/35010997/52112241-81402700-2638-11e9-8517-557e9b58cbcd.png)

**Comment by BeepFelix** [comment]
Invalid API key

**Comment by MikhaelLauda** [comment]
I revoke old API key and generate new one
Or should i use another account to generate new API key ?

**Comment by BeepFelix** [comment]
Any which has access to the Steam API should work.

**Comment by MikhaelLauda** [comment]
Still, got the same error after 3 accounts (3 Steam API key)

**Comment by MikhaelLauda** [comment]
Okay, problem solved
Thanks
