### ISSUE TITLE
I need help，Please help me.

### ISSUE THREAD

**Issue by asdgsadf** [BeepIsla/csgo-commend-bot#312]
****[PE1BwinXYBCe] Failed to commend (1/3) {
  name: 'Error',****
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\fasg\\Downloads\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:531:17)\n' +
    '    at processTimers (internal/timers.js:475:7)'
}
 [1phjJQg5qcHu] Failed to commend (2/3) {
  name: 'Error',

Config

{
	"commend": {
		"friendly": 3,
		"teaching": 3,
		"leader": 3
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/id/qwert/",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"steamWebAPIKey": "F7B158F8CE98EF5CD480CB647C84C927",
	"disableUpdateCheck": false
}

**Comment by BeepIsla** [comment]
You leaked your API key, it can be used to scam you. Revoke your key and generate a new one.

---

On what server is your target? Valve Competitive? Valve Casual? Community?

**Comment by asdgsadf** [comment]
> 您泄露了您的API密钥，它可以被用来欺骗您。撤销密钥并生成一个新密钥。
> 
> 您的目标是在哪台服务器上？阀门有竞争力吗？气门休闲？社区？

Thank you. I've changed API key.  My target server is Valve Casual and Valve Casual,But none of them can be used

**Comment by asdgsadf** [comment]
I turn off VPN, try again or fail.Who can tell me what to do? Thank you very much

**Comment by BeepIsla** [comment]
Try using different accounts. Something is preventing them from commending, according to your config and what you said it should work fine.

Make sure your target is on a Valve Casual server or community server. **Not** Competitive or Wingman.
