### ISSUE TITLE
Failed to login and has been marked as invalid

### ISSUE THREAD

**Issue by GA1GAN** [BeepIsla/csgo-commend-bot#313]
Checking for new update...
 Up to date!
 Checking protobufs...
 Found protobufs
 Opening database...
 There are a total of 6 operational accounts
 Parsing target account...
 Chunking 6 accounts into groups of 20...
 Logging in on chunk 1/1
 [steambots2020_1] Logging into Steam
 [steambots2020_2] Logging into Steam
 [steambots2020_3] Logging into Steam
 [steambots2020_4] Logging into Steam
 [steambots2020_5] Logging into Steam
 [steambots2020_6] Logging into Steam
 [steambots2020_6] Failed to login and has been marked as invalid (1/6) { eresult: 5,
  name: 'Error',
  message: 'InvalidPassword',
  stack:
   'Error: InvalidPassword\n    at SteamUser.<anonymous> (C:\\Users\\GA1GANmoBamba\\Desktop\\csgo-commend-bot-master\\node_modules\\steam-user\\components\\logon.js:458:16)\n    at handlers.forEach (C:\\Users\\GA1GANmoBamba\\Desktop\\csgo-commend-bot-master\\node_modules\\steam-user\\components\\classes\\HandlerManager.js:37:12)\n    at Array.forEach (<anonymous>)\n    at HandlerManager.emit (C:\\Users\\GA1GANmoBamba\\Desktop\\csgo-commend-bot-master\\node_modules\\steam-user\\components\\classes\\HandlerManager.js:36:12)\n    at SteamUser._handleMessage (C:\\Users\\GA1GANmoBamba\\Desktop\\csgo-commend-bot-master\\node_modules\\steam-user\\components\\messages.js:545:24)\n    at SteamUser.Coordinator.steamUser._handleMessage (C:\\Users\\GA1GANmoBamba\\Desktop\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:43:19)\n    at SteamUser._handleNetMessage (C:\\Users\\GA1GANmoBamba\\Desktop\\csgo-commend-bot-master\\node_modules\\steam-user\\components\\messages.js:480:7)\n    at SteamUser.processMulti (C:\\Users\\GA1GANmoBamba\\Desktop\\csgo-commend-bot-master\\node_modules\\steam-user\\components\\messages.js:572:9)\n    at SteamUser.<anonymous> (C:\\Users\\GA1GANmoBamba\\Desktop\\csgo-commend-bot-master\\node_modules\\steam-user\\components\\messages.js:566:16)\n    at handlers.forEach (C:\\Users\\GA1GANmoBamba\\Desktop\\csgo-commend-bot-master\\node_modules\\steam-user\\components\\classes\\HandlerManager.js:37:12)' }
 [steambots2020_5] Logged onto Steam - GC Time: 2020-3-21 18:38:56
 [steambots2020_5] Authenticated to anonymous server with ticket 4197548653
 [steambots2020_5] Failed to login and has been marked as invalid (2/6) { name: 'TypeError',
  message:
   '[target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function',
  stack:
   'TypeError: [target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function\n    at a.login.then (C:\\Users\\GA1GANmoBamba\\Desktop\\csgo-commend-bot-master\\helpers\\Bots.js:88:7)\n    at process._tickCallback (internal/process/next_tick.js:68:7)' }
 [steambots2020_4] Logged onto Steam - GC Time: 2020-3-21 18:38:58
 [steambots2020_1] Logged onto Steam - GC Time: 2020-3-21 18:38:58
 [steambots2020_4] Authenticated to anonymous server with ticket 805898533
 [steambots2020_4] Failed to login and has been marked as invalid (3/6) { name: 'TypeError',
  message:
   '[target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function',
  stack:
   'TypeError: [target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function\n    at a.login.then (C:\\Users\\GA1GANmoBamba\\Desktop\\csgo-commend-bot-master\\helpers\\Bots.js:88:7)\n    at process._tickCallback (internal/process/next_tick.js:68:7)' }
 [steambots2020_1] Authenticated to anonymous server with ticket 3560841492
 [steambots2020_1] Failed to login and has been marked as invalid (4/6) { name: 'TypeError',
  message:
   '[target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function',
  stack:
   'TypeError: [target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function\n    at a.login.then (C:\\Users\\GA1GANmoBamba\\Desktop\\csgo-commend-bot-master\\helpers\\Bots.js:88:7)\n    at process._tickCallback (internal/process/next_tick.js:68:7)' }
 [steambots2020_3] Logged onto Steam - GC Time: 2020-3-21 18:39:00
 [steambots2020_3] Authenticated to anonymous server with ticket 4236718044
 [steambots2020_3] Failed to login and has been marked as invalid (5/6) { name: 'TypeError',
  message:
   '[target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function',
  stack:
   'TypeError: [target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function\n    at a.login.then (C:\\Users\\GA1GANmoBamba\\Desktop\\csgo-commend-bot-master\\helpers\\Bots.js:88:7)\n    at process._tickCallback (internal/process/next_tick.js:68:7)' }
 [steambots2020_2] Logged onto Steam - GC Time: 2020-3-21 18:39:16
 [steambots2020_2] Authenticated to anonymous server with ticket 3992450377
 [steambots2020_2] Failed to login and has been marked as invalid (6/6) { name: 'TypeError',
  message:
   '[target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function',
  stack:
   'TypeError: [target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function\n    at a.login.then (C:\\Users\\GA1GANmoBamba\\Desktop\\csgo-commend-bot-master\\helpers\\Bots.js:88:7)\n    at process._tickCallback (internal/process/next_tick.js:68:7)' }
 Chunk 1/1 finished with 0 successful commends and 6 failed commends
 Finished all chunks with a total of 0 successful and 6 failed commends

**Comment by BeepIsla** [comment]
Update to NodeJS v12 just like how it says in the README.
