### ISSUE TITLE
i need help 

### ISSUE THREAD

**Issue by Pecus35** [BeepIsla/csgo-commend-bot#314]
![image](https://user-images.githubusercontent.com/50454305/77248803-720da580-6c4d-11ea-90c7-de8e99722467.png)
im getting this error pls help

**Comment by BeepIsla** [comment]
Read the README.

You need an actual API key from Stea.

**Comment by Pecus35** [comment]
![image](https://user-images.githubusercontent.com/50454305/77248940-7dad9c00-6c4e-11ea-92e4-c775892e5ba7.png)
 not it says this sorry my english bad

**Comment by Pecus35** [comment]
for all of the accounts

**Comment by BeepIsla** [comment]
You need NodeJS v12.

Again, the README tells you everything you need to know:

> - [NodeJS v12](https://nodejs.org/dist/v12.9.1/) - You will likely need node-v12.9.1-x64.msi

**Comment by Pecus35** [comment]
Thanks it works now btw. can i send my friend commend without apikey?

**Comment by BeepIsla** [comment]
It does not matter what API key you use, once you have one in your config you never have to change it. Unless the API key gets revoked.

**Comment by Pecus35** [comment]
okay thanks again!

**Comment by Pecus35** [comment]
![image](https://user-images.githubusercontent.com/50454305/77249253-d716ca80-6c50-11ea-9cba-387fe08d205b.png)
![image](https://user-images.githubusercontent.com/50454305/77249257-dda54200-6c50-11ea-915d-24a03a80b3d7.png)
i have one more question it always fails is it because of the accounts or the bot?

**Comment by BeepIsla** [comment]
Likely an issue on the bot account. This seems to happen to accounts randomly and I don't know why. Using new accounts works without problems though.

**Comment by BABoom12** [comment]
> ![image](https://user-images.githubusercontent.com/50454305/77249253-d716ca80-6c50-11ea-9cba-387fe08d205b.png)
> ![image](https://user-images.githubusercontent.com/50454305/77249257-dda54200-6c50-11ea-915d-24a03a80b3d7.png)
> i have one more question it always fails is it because of the accounts or the bot?
when you use the same ip 20 times u need to wait 5mins if not u get this error

**Comment by HyperArda** [comment]
@BABoom12 Its a issue on the bot account. This seems to happen to accounts randomly and WE don't know why. Using new accounts works without problems though.

**Comment by BeepIsla** [comment]
Closed due to inactivity.
