### ISSUE TITLE
Accounts have turned on Steam Guard

### ISSUE THREAD

**Issue by max12383** [BeepIsla/csgo-commend-bot#315]
Accounts have turned on Steam Guard. Did can the script do that? One person said that the script but I don't really believe him. :)

**Comment by BeepIsla** [comment]
If you log into a Steam account (Not via community) then Steam automatically turns on Steam Guard. There is nothing I can do against this.

**Comment by max12383** [comment]
> If you log into a Steam account (Not via community) then Steam automatically turns on Steam Guard. There is nothing I can do against this.

How to understand (Not via community)?

**Comment by max12383** [comment]
> > If you log into a Steam account (Not via community) then Steam automatically turns on Steam Guard. There is nothing I can do against this.
> 
> How to understand (Not via community)?

Just I bought 1000 autoreg accounts from a one seller and he's saying that I'm to blame.

**Comment by BeepIsla** [comment]
Logging in on https://steamcommunity.com/ it does not enable Steam Guard but you also can't play any games.

You have to log in similar to how the real Steam Client logs in, this also **automatically** enables Steam Guard and there is nothing I can do against it.

**Comment by max12383** [comment]
Thanks
