### ISSUE TITLE
Not getting all commends

### ISSUE THREAD

**Issue by Raflake** [BeepIsla/csgo-commend-bot#317]
I have 308 accounts and only got 283 commends, all accounts is working i dont get erros like TimeOut, SteamGuard error, InvalidPassword or VacBan. I tried to switch from server but keep the same. I reseted a lot of times the database idk if is it the problem. When i reset it says "Successfully sent a commend" but im not getting commends.

**Comment by BeepIsla** [comment]
You cannot commend the same person twice.

**Comment by Raflake** [comment]
so where are the commends of the others 25 accounts?

**Comment by BeepIsla** [comment]
The script takes whatever accounts have not commended you yet, if you reset your database that information is lost forever. So it has to rebuild that information using each account again attempting to commend you. Once its once rebuilding that information it can start using unused accounts.

**Comment by Raflake** [comment]
If i not reset this appears, and i keep without 25 commends from 25 accounts
![Screenshot_4](https://user-images.githubusercontent.com/42303962/77424626-5deeb300-6dc9-11ea-8d8d-2e4ac5092c4f.png)

**Comment by BeepIsla** [comment]
Its possible the accounts failed to commend and have been set on cooldown, lower your cooldown value in your config or wait until its over.

Alternatively you can download [SQLite Browser](https://sqlitebrowser.org/) and open up the `accounts.sqlite` file yourself and take a look at the data.

**Comment by Raflake** [comment]
one question, should i put my account here? 
![image](https://user-images.githubusercontent.com/42303962/77425942-6ba53800-6dcb-11ea-941c-f8fdd6915b5c.png)

**Comment by BeepIsla** [comment]
This is only used when you use `LOGIN` method, it is ignored when using `SERVER` method.

**Comment by Raflake** [comment]
i use community server should i delete?

**Comment by BeepIsla** [comment]
Does not matter, it is ignored.

**Comment by Raflake** [comment]
i installed sqlite browser how can i use to see what is happening to 25 accounts?

**Comment by BeepIsla** [comment]
Open the `accounts.sqlite` file with SQLite Browser, go to the Data tab and look at the accounts in the list, check if they are marked as `operational` and the `lastCommend` timestamp is not too far in the past.

As another alternative you can manually remove the 25 accounts and re-add them. This should simply reset only those accounts to default, then just run the script again.

**Comment by Raflake** [comment]
![image](https://user-images.githubusercontent.com/42303962/77426519-8cba5880-6dcc-11ea-8bef-432e856b8c60.png)
![image](https://user-images.githubusercontent.com/42303962/77426556-9a6fde00-6dcc-11ea-9e73-9fb9cbd12640.png)
it says from 308 accounts only 306 have commend but where is the 25?

**Comment by Raflake** [comment]
ok i will try

**Comment by Raflake** [comment]
how to open operational?
![image](https://user-images.githubusercontent.com/42303962/77426695-ea4ea500-6dcc-11ea-8132-2ad4a9e00d2b.png)

**Comment by BeepIsla** [comment]
You don't, you already see in the picture above a column called `operational`, 1 for yes, 0 for no.

**Comment by Raflake** [comment]
so is all good?

**Comment by BeepIsla** [comment]
There are 300+ accounts. I can't see that all and look over it, you have to check yourself. There has never been an issue with the database and I never changed anything with it, I doubt there is a problem now. So if it simply doesn't work just try my other suggestion, remove the 25 accounts then add them again.

**Comment by Raflake** [comment]
how can i know what the name of these 25 accounts if in tab "accounts" has 308 and in "commended" has 306?  Can we go discord?

**Comment by BeepIsla** [comment]
You can also just quickly generate 25 new accounts, it doesn't take any effort at all.

**Comment by Raflake** [comment]
the only generator i know is cathook and it is having some issues, do you know some method to generate accounts?

**Comment by BeepIsla** [comment]
No I do not. Cathook AccGen is working fine for me. Maybe your IP is blocked, you can't generate a lot accounts with one IP.

**Comment by Raflake** [comment]
yesterday i've generated 32 accounts one by one and today is requesting for steam guard, i lost a lot of time 1 by 1 for this. I know i can mass generate but i dont wanna put money in 2 captcha

**Comment by Raflake** [comment]
what sould i do?

> yesterday i've generated 32 accounts one by one and today is requesting for steam guard, i lost a lot of time 1 by 1 for this. I know i can mass generate but i dont wanna put money in 2 captcha

**Comment by BeepIsla** [comment]
Closed due to inactivity and there is nothing more I can say to this.
