### ISSUE TITLE
How do i use Login method

### ISSUE THREAD

**Issue by obrabo** [BeepIsla/csgo-commend-bot#319]
Hi, i`m having some problems in account.js

**Comment by BeepIsla** [comment]
Set method to `LOGIN` and fill in your account details, thats it.

**Comment by obrabo** [comment]
yeah, but where i put my login in account.js

**Comment by BeepIsla** [comment]
Where did you ever read anything about `account.js`? You are not suppose to touch anything except your config.

**Comment by obrabo** [comment]
i dont touch anything, but how do i put my account login?

**Comment by BeepIsla** [comment]
Have you tried looking at the [example config](https://github.com/BeepIsla/csgo-commend-bot/blob/master/config.json.example)?

Your config is suppose to have an account field, put in your account details there.

**Comment by obrabo** [comment]
![image](https://user-images.githubusercontent.com/62652330/77539255-d31cbf80-6e7f-11ea-9624-fdbdfa3a4f4c.png)

**Comment by obrabo** [comment]
ahhh, ok, i going to try

**Comment by obrabo** [comment]
thanks!!
