### ISSUE TITLE
Cannot Commend

### ISSUE THREAD

**Issue by ChickenNerd** [BeepIsla/csgo-commend-bot#320]
After you commend one account with the accounts and it says remaining (2/3) and after you wanna commend another account it won't work till you reset the database and re-add the accounts. Then it works perfectly.

Before removing database, accounts are still available for 2 commends, but it says:
```
 Checking for new update...
 Up to date!
 Checking protobufs...
 Found protobufs
 Opening database...
 There are a total of 11 operational accounts
 Parsing target account...
 Not enough accounts available at the current time, got 0/10
```

After you remove the database and re-add the accounts:
```
Checking for new update...
 Up to date!
 Checking protobufs...
 Found protobufs
 Opening database...
 There are a total of 11 operational accounts
 Parsing target account...
 Chunking 10 accounts into groups of 20...
 Logging in on chunk 1/1
 [********] Logging into Steam...            x10
 [********] Logged onto Steam - GC Time: 2020-3-25 23:23:38...             x10
 [********]  Authenticated to anonymous server with ticket ********     x10
 [********] Successfully sent a commend with response code 1 - Remaining Commends: 1 (1/10).. x10
 Chunk 1/1 finished with 10 successful commends and 0 failed commends.
```

Please fix this and thank you for this amazing program.

**Comment by BeepIsla** [comment]
Likely something wrong in your config or you miss-understood something somewhere. There have never been code changes to account selection and never any problems with it so I doubt it magically broke.

Ensure the accounts are not currently on cooldown and you are commending *another* player.

**Comment by ChickenNerd** [comment]
I am sure that i am commending another player and that the accounts are not on cooldown.
Here is my config:
```
{
	"commend": {
		"friendly": 10,
		"teaching": 10,
		"leader": 10
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/id/*****/",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"steamWebAPIKey": "*************",
	"disableUpdateCheck": false
}
```

**Comment by BeepIsla** [comment]
So you commended a player, then waited 6 hours and then commended another player?

This could be very hard to replicate and fix.

**Comment by ChickenNerd** [comment]
Wait what?
6 hours? I thought 20 commends per 5 minutes.
But why does it work without waiting 6 hours then, i have the commends on all the accounts i commended.
It works normally when i commend with 5 minutes cooldown. the accounts get commends normally.
Anyways, if it's 6 hours then i am very sorry and you can close this.

**Comment by BeepIsla** [comment]
20 commends per IP (Chunks) per 5 minutes.

6 hours to re-use the same accounts again. You can tweak this in your config but make sure not to go over the "3 commends per 24 hours" limit.

**Comment by ChickenNerd** [comment]
How do i exactly change it in the config?
Is it "cooldown"?
It's default is:  28800000, it's in seconds?
Because that value in seconds is 333 days lol

**Comment by BeepIsla** [comment]
Its in milliseconds. And actually 8 hours, not 6.

**Comment by ChickenNerd** [comment]
Ok, thank you very much for your help. I was very confused about this.
