### ISSUE TITLE
Failed to send message: Timeout

### ISSUE THREAD

**Issue by ozkcs** [BeepIsla/csgo-commend-bot#321]
**Detailed bug description**
When I try to commend a target (target in community server and cl_join_advertise 2), result in this error for me, I tried 50 accounts, all the accs happened the same error

**Error**
```
Checking for new update...
 Up to date!
 Checking protobufs...
 Found protobufs
 Opening database...
 There are a total of 23 operational accounts
 Parsing target account...
 Chunking 5 accounts into groups of 20...
 Logging in on chunk 1/1
 [MrPiiDuck] Logging into Steam
 [MrSquiggles92] Logging into Steam
 [MrTigey] Logging into Steam
 [MrUltimate01] Logging into Steam
 [OafishIllLouse05] Logging into Steam
 [MrSquiggles92] Logged onto Steam - GC Time: 2020-3-25 21:05:38
 [MrPiiDuck] Logged onto Steam - GC Time: 2020-3-25 21:05:38
 [MrTigey] Logged onto Steam - GC Time: 2020-3-25 21:05:37
 [MrPiiDuck] Authenticated to anonymous server with ticket 478423451
 [MrSquiggles92] Authenticated to anonymous server with ticket 3300684499
 [MrTigey] Authenticated to anonymous server with ticket 207035272
 [MrUltimate01] Logged onto Steam - GC Time: 2020-3-25 21:05:42
 [OafishIllLouse05] Logged onto Steam - GC Time: 2020-3-25 21:05:42
 [MrUltimate01] Authenticated to anonymous server with ticket 3120468617
 [OafishIllLouse05] Authenticated to anonymous server with ticket 869363189
 [MrPiiDuck] Failed to commend (1/5) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\cerolcs\\Desktop\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:531:17)\n' +
    '    at processTimers (internal/timers.js:475:7)'
}
 [MrSquiggles92] Failed to commend (2/5) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\cerolcs\\Desktop\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:531:17)\n' +
    '    at processTimers (internal/timers.js:475:7)'
}
 [MrTigey] Failed to commend (3/5) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\cerolcs\\Desktop\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:531:17)\n' +
    '    at processTimers (internal/timers.js:475:7)'
}
 [MrUltimate01] Failed to commend (4/5) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\cerolcs\\Desktop\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:531:17)\n' +
    '    at processTimers (internal/timers.js:475:7)'
}
 [OafishIllLouse05] Failed to commend (5/5) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\cerolcs\\Desktop\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:531:17)\n' +
    '    at processTimers (internal/timers.js:475:7)'
}
 Chunk 1/1 finished with 0 successful commends and 5 failed commends
 Finished all chunks with a total of 0 successful and 5 failed commends
```

**Config**
```
{
	"commend": {
		"friendly": 5,
		"teaching": 5,
		"leader": 5
	},
	"report": {
		"aimbot": 10,
		"wallhack": 10,
		"speedhack": 10,
		"teamharm": 10,
		"abusive": 10
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/id/ozkcs",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"steamWebAPIKey": "XXXXX",
	"disableUpdateCheck": false
}
```

**Version**
- NodeJS: `v12.9.0` (You can find this using `node -v`)
- Script version: `2.7.1` (You can find this in **your** `package.json` file under `version`)

**Comment by BeepIsla** [comment]
Backup your `accounts.sqlite` and create a new one with freshly created accounts. Check if they work:

- If yes: Its unrelated to the script and some weird problem with the accounts

- If no: Probably an issue with the

**Comment by alladdicted** [comment]
I get the same error Timeout timers.js:531:17, timers.js:475:7, but only when I try to Report. Commend works.

**Comment by BeepIsla** [comment]
Reporting is more restrictive than Commending. Likely Valve preventing the reports from happening.

**Comment by alladdicted** [comment]
> Reporting is more restrictive than Commending. Likely Valve preventing the reports from happening.

Does the account need Prime status to report? Or why it is not working.

**Comment by BeepIsla** [comment]
Prime does not matter, you cannot report in Matchmaking/Wingman.

**Comment by alladdicted** [comment]
> Prime does not matter, you cannot report in Competitive/Wingman.

So the player I report needs to be in Casual/Deathmatch?

**Comment by BeepIsla** [comment]
Anything which isn't Competitive/Wingman.

**Comment by alladdicted** [comment]
Maybe add error catch if target is not in non competitive/wingman match.

**Comment by BeepIsla** [comment]
That would require a fetcher account like in the last version again, and it slow down the entire process. Its not hard to know if someone is on comp/wingman anyways, literally just ask the person you are botting.

**Comment by alladdicted** [comment]
If I want to report a player I dont know if he in competitive or playing. Fetcher account would be ok to check.

**Comment by BeepIsla** [comment]
Why would you report bot a player you don't know

**Comment by alladdicted** [comment]
Because they cheat

**Comment by BeepIsla** [comment]
Just report them, if it fails they are not on a community/casual mode. If it works then they are, great.

If you want to check beforehand just use any online website you want like [CS:SO Mates](http://csgo-mates.com/#/home/) or others.

I will not implement this into the bot itself.

**Comment by despa1r1337** [comment]
> Because they cheat

reportbot only work when match finished,you can't reportbot player while they still have ongoing match ,you need to wait till match end,otherwise report will ignored and didnt get any response

**Comment by Nico1022-stack** [comment]
guys but the commend bot is dead? in truth I have seen that some still work, but I think they use another, or is there any update to put a new one? do you know something? thank you very much

**Comment by ludicsa** [comment]
I'm with the Time Out error while trying to commend. 07/02

**Comment by ludicsa** [comment]
**This is the error.**


C:\Users\*****\Desktop\csgo-commend-bot>node index.js
 Update check skipped
 Checking protobufs...
 Found protobufs
 Opening database...
 There are a total of 59 operational accounts
 Parsing target account...
 Chunking 10 accounts into groups of 20...
 Parsing server input
 Parsed server input to 85568392923354798
 Logging in on chunk 1/1
 [abbitc2mazzanti990128] Logging into Steam
 [accoons10payne2707636] Logging into Steam
 [adgerb1010093948moore] Logging into Steam
 [alconr10136ciani] Logging into Steam
 [alcont9casey25399493] Logging into Steam
 [almonb9torrini3709878] Logging into Steam
 [almong91671790nakamura] Logging into Steam
 [amarinm9gibbons630171] Logging into Steam
 [amsterh10stephens151] Logging into Steam
 [antengp5pezzati754131] Logging into Steam
 [adgerb1010093948moore] Logged onto Steam - GC Time: 2020-7-2 14:19:24
 [abbitc2mazzanti990128] Logged onto Steam - GC Time: 2020-7-2 14:19:24
 [adgerb1010093948moore] Authenticated with target server with ticket 1665316370
 [abbitc2mazzanti990128] Authenticated with target server with ticket 2572880805
 [alconr10136ciani] Logged onto Steam - GC Time: 2020-7-2 14:19:25
 [almonb9torrini3709878] Logged onto Steam - GC Time: 2020-7-2 14:19:25
 [alconr10136ciani] Authenticated with target server with ticket 3725965097
 [almonb9torrini3709878] Authenticated with target server with ticket 2379463530
 [amarinm9gibbons630171] Logged onto Steam - GC Time: 2020-7-2 14:19:29
 [almong91671790nakamura] Logged onto Steam - GC Time: 2020-7-2 14:19:29
 [amarinm9gibbons630171] Authenticated with target server with ticket 1644142164
 [almong91671790nakamura] Authenticated with target server with ticket 3411018621
 [alcont9casey25399493] Logged onto Steam - GC Time: 2020-7-2 14:19:30
 [amsterh10stephens151] Logged onto Steam - GC Time: 2020-7-2 14:19:30
 [accoons10payne2707636] Logged onto Steam - GC Time: 2020-7-2 14:19:30
 [antengp5pezzati754131] Logged onto Steam - GC Time: 2020-7-2 14:19:30
 [alcont9casey25399493] Authenticated with target server with ticket 4134947445
 [amsterh10stephens151] Authenticated with target server with ticket 399556820
 [accoons10payne2707636] Authenticated with target server with ticket 3259232958
 [antengp5pezzati754131] Authenticated with target server with ticket 382023198
 [adgerb1010093948moore] Failed to commend (1/10) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\lucas\\Desktop\\csgo-commend-bot\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
}
 [abbitc2mazzanti990128] Failed to commend (2/10) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\*****\\Desktop\\csgo-commend-bot\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
}
 [alconr10136ciani] Failed to commend (3/10) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\*****\\Desktop\\csgo-commend-bot\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
}
 [almonb9torrini3709878] Failed to commend (4/10) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\*****\\Desktop\\csgo-commend-bot\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
}
 [amarinm9gibbons630171] Failed to commend (5/10) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\*****\\Desktop\\csgo-commend-bot\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
}
 [almong91671790nakamura] Failed to commend (6/10) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\*****\\Desktop\\csgo-commend-bot\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
}
 [alcont9casey25399493] Failed to commend (7/10) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\*****\\Desktop\\csgo-commend-bot\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
}
 [amsterh10stephens151] Failed to commend (8/10) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\*****\\Desktop\\csgo-commend-bot\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
}
 [accoons10payne2707636] Failed to commend (9/10) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\*****\\Desktop\\csgo-commend-bot\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
}
 [antengp5pezzati754131] Failed to commend (10/10) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\*****\\Desktop\\csgo-commend-bot\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
}
 Chunk 1/1 finished with 0 successful commends and 10 failed commends
 Finished all chunks with a total of 0 successful and 10 failed commends
