### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by Mariano123455** [BeepIsla/csgo-commend-bot#322]
(node:8476) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'k
_EMsgClientAuthList' of undefined
    at C:\Users\maria\Desktop\CSGO COMMENDS\helpers\account.js:257:37
(node:8476) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). To termina
te the node process on unhandled promise rejection, use the CLI flag `--unhandle
d-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejectio
ns_mode). (rejection id: 1)

**Comment by BeepIsla** [comment]
What are you doing for this to happen? Whats your config? What version of the script are you using?

**Comment by Mariano123455** [comment]
The script clones it from github desktop, I am using node js 12.16.1 LTS, and this is my config
![image](https://user-images.githubusercontent.com/42093106/77670349-d6d64200-6f64-11ea-9d1f-75dbe2bc7b94.png)

**Comment by Mariano123455** [comment]
The error appears with each recommendation attempt, that is, with each account.
![image](https://user-images.githubusercontent.com/42093106/77670566-2583dc00-6f65-11ea-96e9-57736bb22967.png)

**Comment by BeepIsla** [comment]
You have leaked your API key, delete it and generate a new one.

---

Try deleting your `protobufs` folder and running the script again.

**Comment by Mariano123455** [comment]
By deleting the protobufs folder it started downloading while running the script and it worked! thanks!
