### ISSUE TITLE
\tbh idk but it says "files broken"

### ISSUE THREAD

**Issue by LAMBRO0** [BeepIsla/csgo-commend-bot#323]
so i did all steps with the bot and the very first time i was soo close to it working but then i got message saying "update available" for bot so got new version from here i restarted cmd now getting these errors
C:\Users\User\Desktop\csgo-commend-bot-master>npm install
audited 405 packages in 6.925s
found 3 low severity vulnerabilities
  run npm audit fix to fix them, or npm audit for details

C:\Users\User\Desktop\csgo-commend-bot-master>
and after
C:\Users\User\Desktop\csgo-commend-bot-master>npm audit fix
up to date in 5.804s
fixed 0 of 3 vulnerabilities in 405 scanned packages
  3 vulnerabilities required manual review and could not be updated
please help me thank you 
-lambro

**Comment by BeepIsla** [comment]
Don't do audit fix. Just do npm install and run the bot like normal.

The vulernable code is not used so it can be ignored
