### ISSUE TITLE
I want to create a programmatic version 

### ISSUE THREAD

**Issue by ha6000** [BeepIsla/csgo-commend-bot#324]
**Detailed question description**
I want to make a module out of this, but is there anything I need to know?

**Config**
```
n/a
```

**Version**
- NodeJS: `v12.14.1` 
- Script version: `2.7.1`

**Comment by BeepIsla** [comment]
You are free to modify the code as long as you follow the license.

At the current moment you shouldn't run it multiple times at once, doing so will likely cause the script to use two accounts at once breaking everything.

Thats it, just look through the ugly code and modify it a bit, shouldn't be hard.
