### ISSUE TITLE
Hi i have a question!

### ISSUE THREAD

**Issue by BABoom12** [BeepIsla/csgo-commend-bot#326]
U can help me whit something? like auto modify the target like "node index.js 76561199004503983"
and make something whit a discord bot i have a proposal for u. dm me BABoom#7330

**Comment by BeepIsla** [comment]
I don't do such things.

**Comment by BABoom12** [comment]
why?

În lun., 30 mar. 2020 la 15:38, Isla <notifications@github.com> a scris:

**Comment by BeepIsla** [comment]
Because I have better things to do. Code is open source, you can always change anything you want yourself.

**Comment by BABoom12** [comment]
but idk i pay u

În lun., 30 mar. 2020 la 15:50, Isla <notifications@github.com> a scris:

**Comment by BeepIsla** [comment]
No, I don't care.
