### ISSUE TITLE
cooldown with proxy

### ISSUE THREAD

**Issue by boostacc** [BeepIsla/csgo-commend-bot#327]
Hello, There was a small question. 

If I use multiple proxies, can I only change "betweenChunks" or can the "cooldown" parameter also be changed?

I know what "betweenChunks" is responsible for, but I don't understand what "cooldown" 28900000 means
Thanks for the answer

**Comment by boostacc** [comment]
And 1 more small question)
I want to switch to using Linux
Should the program work correctly under Linux?

**Comment by BeepIsla** [comment]
Cooldowns are account based and not IP bases. Between chunks is IP based.

It works on every OS which supports NodeJS, so yes any linux distro will work.
