### ISSUE TITLE
Failed to send message: Timeout

### ISSUE THREAD

**Issue by wnorbert85** [BeepIsla/csgo-commend-bot#328]
Failed to commend (14/15) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\wnorb\\Desktop\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'

**Comment by boostacc** [comment]
Enter your error in the search "Timeout" And you will find comprehensive answers to your question =)
