### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by Dansteris** [BeepIsla/csgo-commend-bot#330]
![Snímka](https://user-images.githubusercontent.com/63014211/78388255-f44c8100-75e0-11ea-97f2-1bbf99a203db.PNG)

Please help me, few days ago it was warking fine.

**Comment by BeepIsla** [comment]
That doesn't mean anything. Its too little information to work with.

Config, Server type, did you try other accounts, what are you doing, etc

**Comment by Dansteris** [comment]
{
	"commend": {
		"friendly": 5,
		"teaching": 5,
		"leader": 5
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 2
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/id/profiles/xxxxxxxxxxxxxx",
	"perChunk": 5,
	"betweenChunks": 10000,
	"cooldown": 28800000,
	"steamWebAPIKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	"disableUpdateCheck": false
}

**Comment by Dansteris** [comment]
I tryied other accs, and still dont work.

**Comment by BeepIsla** [comment]
What server, Competitive? Wingman? Community? Casual? Deathmatch?

**Comment by Dansteris** [comment]
Training with bots (Mirage)

**Comment by BeepIsla** [comment]
Try joining an actual server

**Comment by Dansteris** [comment]
On community server?

**Comment by BeepIsla** [comment]
yes

**Comment by BeepIsla** [comment]
That doesn't make any sense. Make sure your target is correct and you edit the correct file if you have multiple conig files.
