### ISSUE TITLE
 Failed to log into Steam using account as target Error: GC connection timeout

### ISSUE THREAD

**Issue by Coffee6969** [BeepIsla/csgo-commend-bot#331]
i get this when i try to use the bot 
C:\Users\Miki\Desktop\csgo-commend-bot-master>node index.js
 Checking for new update...
 Up to date!
 Checking protobufs...
 Found protobufs
 Opening database...
 There are a total of 106 operational accounts
 Logging into target account...
 Failed to log into Steam using account as target Error: GC connection timeout - Hello
    at SteamUser.loggedOn (C:\Users\Miki\Desktop\csgo-commend-bot-master\helpers\account.js:128:14)

**Comment by BeepIsla** [comment]
Whats your config

**Comment by Coffee6969** [comment]
> Whats your config

{
	"commend": {
		"friendly": 100,
		"teaching": 100,
		"leader": 100
	},
	"report": {
		"aimbot": 10,
		"wallhack": 10,
		"speedhack": 10,
		"teamharm": 10,
		"abusive": 10
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "LOGIN",
	"target": "https://steamcommunity.com/profiles/76561198266919486",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"steamWebAPIKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	"disableUpdateCheck": false
}



i have the api key in the config but i removed it now

**Comment by BeepIsla** [comment]
You are using login method without any account in your config. That makes no sense. Read on the README what the LOGIN method does and how it works.

**Comment by Coffee6969** [comment]
sry im retarded ill do that
