### ISSUE TITLE
Error in valid accounts.

### ISSUE THREAD

**Issue by flaviomartil** [BeepIsla/csgo-commend-bot#332]
(node:7616) UnhandledPromiseRejectionWarning: TypeError: serializeError.serializeError is not a function
    at C:\csgobotcommend\csgo-commend-bot-master\helpers\Bots.js:115:28
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:7616) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 15)

A MANY ERROR WITH THIS CASE..

my config .js
{
	"commend": {
		"friendly": 500,
		"teaching": 500,
		"leader": 500
	},
	"report": {
		"aimbot": 10,
		"wallhack": 10,
		"speedhack": 10,
		"teamharm": 10,
		"abusive": 10
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/id/xxxxxx",
	"perChunk": 20,
	"betweenChunks":1000,
	"cooldown": 10000,
	"steamWebAPIKey": "",
	"disableUpdateCheck": false
}

**Comment by BeepIsla** [comment]
This is not account related. This is out-of-date related.

Update your node modules folder, either run `npm update` or delete your `node_modules` folder and run `npm install`

**Comment by flaviomartil** [comment]
fixed thank you
