### ISSUE TITLE
Commend bot problem

### ISSUE THREAD

**Issue by StefanCrisan21** [BeepIsla/csgo-commend-bot#333]
[AbackAmbiguousJackal] Requires a Steam Guard code and has been marked as invalid (20/20) {
  name: 'Error',
  message: 'Steam Guard required',
  stack: 'Error: Steam Guard required\n' +
    '    at SteamUser.steamGuard (C:\\Users\\emanu\\Desktop\\csgo-commend-bot-master\\helpers\\account.js:180:12)\n' +
    '    at SteamUser.emit (events.js:311:20)\n' +
    '    at SteamUser._steamGuardPrompt (C:\\Users\\emanu\\Desktop\\csgo-commend-bot-master\\node_modules\\steam-user\\components\\logon.js:570:8)\n' +
    '    at SteamUser.<anonymous> (C:\\Users\\emanu\\Desktop\\csgo-commend-bot-master\\node_modules\\steam-user\\components\\logon.js:432:9)\n' +
    '    at C:\\Users\\emanu\\Desktop\\csgo-commend-bot-master\\node_modules\\steam-user\\components\\classes\\HandlerManager.js:37:12\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at HandlerManager.emit (C:\\Users\\emanu\\Desktop\\csgo-commend-bot-master\\node_modules\\steam-user\\components\\classes\\HandlerManager.js:36:12)\n' +
    '    at SteamUser._handleMessage (C:\\Users\\emanu\\Desktop\\csgo-commend-bot-master\\node_modules\\steam-user\\components\\messages.js:545:24)\n' +
    '    at SteamUser.Coordinator.steamUser._handleMessage (C:\\Users\\emanu\\Desktop\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:43:19)\n' +
    '    at SteamUser._handleNetMessage (C:\\Users\\emanu\\Desktop\\csgo-commend-bot-master\\node_modules\\steam-user\\components\\messages.js:480:7)'

**Comment by BeepIsla** [comment]
Have you tried reading what it says?

The account has Steam Guard enabled and therefore the script cannot login. Disable Steam Guard yourself and try again.

**Comment by StefanCrisan21** [comment]
@BeepIsla i disable steam guard and not work.. Btw thanks for reponse

**Comment by BeepIsla** [comment]
There is nothing I can do. Steam says Steam Guard is enabled and it doesn't let the script login.

**Comment by StefanCrisan21** [comment]
[AbackAccidentalSquid] Failed to login (20/20) {
  eresult: 84,
  name: 'Error',
  message: 'RateLimitExceeded',
  stack: 'Error: RateLimitExceeded\n' +
    '    at SteamUser.<anonymous> (C:\\Users\\emanu\\Desktop\\csgo-commend-bot-master\\node_modules\\steam-user\\components\\logon.js:458:16)\n' +
    '    at C:\\Users\\emanu\\Desktop\\csgo-commend-bot-master\\node_modules\\steam-user\\components\\classes\\HandlerManager.js:37:12\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at HandlerManager.emit (C:\\Users\\emanu\\Desktop\\csgo-commend-bot-master\\node_modules\\steam-user\\components\\classes\\HandlerManager.js:36:12)\n' +
    '    at SteamUser._handleMessage (C:\\Users\\emanu\\Desktop\\csgo-commend-bot-master\\node_modules\\steam-user\\components\\messages.js:545:24)\n' +
    '    at SteamUser.Coordinator.steamUser._handleMessage (C:\\Users\\emanu\\Desktop\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:43:19)\n' +
    '    at SteamUser._handleNetMessage (C:\\Users\\emanu\\Desktop\\csgo-commend-bot-master\\node_modules\\steam-user\\components\\messages.js:480:7)\n' +
    '    at SteamUser.processMulti (C:\\Users\\emanu\\Desktop\\csgo-commend-bot-master\\node_modules\\steam-user\\components\\messages.js:572:9)\n' +
    '    at SteamUser.<anonymous> (C:\\Users\\emanu\\Desktop\\csgo-commend-bot-master\\node_modules\\steam-user\\components\\messages.js:566:16)\n' +
    '    at C:\\Users\\emanu\\Desktop\\csgo-commend-bot-master\\node_modules\\steam-user\\components\\classes\\HandlerManager.js:37:12'
}
 Chunk 1/5 finished with 0 successful commends and 20 failed commends
 Waiting 300000ms...

**Comment by BeepIsla** [comment]
Steam has blocked you.

You failed to login into too many accounts and you are now blocked for 30 minutes.

Don't do anything with Steam for 30 minutes and then try again. If you try too early it will reset the timer and you have wait 30 minutes again from scratch.

**Comment by StefanCrisan21** [comment]
@BeepIsla thanks for help. Have a nice day.
