### ISSUE TITLE
Proxy commend bot

### ISSUE THREAD

**Issue by StefanCrisan21** [BeepIsla/csgo-commend-bot#334]
How, i can make a proxy config for commend bot?

**Comment by despa1r1337** [comment]
`"proxy": {
		"enabled": false, // true - on , false - off
		"file": "proxies.txt", // The filename you want to load proxies from (With extension like .txt or .json)
		"switchProxyEveryXaccounts": 20 // switchProxyEveryXaccounts Number: One proxy per X accounts
	},`

**Comment by StefanCrisan21** [comment]
How can i find proxy ip?

**Comment by despa1r1337** [comment]
> How can i find proxy ip?

https://free-proxy-list.net/,
 https://hidemy.name/en/proxy-list/, 
http://free-proxy.cz/ru/.

**Comment by Raxana7** [comment]
@despa1r1337 aadon.to proxies are working ?

**Comment by despa1r1337** [comment]
> @despa1r1337 aadon.to proxies are working ?

yes

**Comment by Angel-sudo** [comment]
Every proxy I'm trying to use (HTTP(s) only) are not working, the one I already had, fresh new on sites aswell.
![image](https://user-images.githubusercontent.com/51993047/78585782-b9de2080-783a-11ea-89d2-1e7e690f9b2c.png)

**Comment by Raxana7** [comment]
@Angel-sudo Your proxies are so slowly or accounts password are not true.

**Comment by Angel-sudo** [comment]
My accounts passwords are working, I've made this night without proxies and I got about 1200 each, where can I find fast proxies ?
