### ISSUE TITLE
Commend bot

### ISSUE THREAD

**Issue by StefanCrisan21** [BeepIsla/csgo-commend-bot#336]
Hi, i have a lot of accounts, and 20 commends can send. After 300000ms the commend bot send 0/20 commends.

**Comment by Raxana7** [comment]
Send your details and your issiue ss.

Example :
**Detailed question description**
A clear and concise description of your question.

**Config**
```
Your "config.json" - Censor your API Key and account details
```

**Version**
- NodeJS: `vXX.XX.X` (You can find this using `node -v`)
- Script version: `X.X.X` (You can find this in **your** `package.json` file under `version`)

**Comment by StefanCrisan21** [comment]
![image](https://user-images.githubusercontent.com/63186258/78595036-f9fccd80-7851-11ea-9689-6431a1dbc073.png)

**Comment by Raxana7** [comment]
Backup your accounts.sqlite and remove all files.
Download new files. ( https://codeload.github.com/BeepIsla/csgo-commend-bot/zip/master )
Read README.md

**Comment by Raxana7** [comment]
Use your accounts.sqlite with new files.
