### ISSUE TITLE
Commending my main

### ISSUE THREAD

**Issue by RealBugzy** [BeepIsla/csgo-commend-bot#337]
Hey, not really an issue but i was just wondering.. i'm currently commending myself with over 26.5k accounts and its going to take a few days since i'm not using proxies... if i close out of the console could i continue to commend later on with the remaining accounts or would i need to start from scratch again and have to go through lots of errors because i've already commended myself with 50% of the accounts that i own?

I ask because i wanna let my pc rest for a bit, i've had csgo open for over 48 hours and 10k commends have gone through.

**Comment by BeepIsla** [comment]
The script will remember which accounts were used already. So yes you can exit out of it whenever you want.

If you delete your accounts.sqlite that information is lost though, so never ever delete it.

**Comment by RealBugzy** [comment]
Thanks for the response, i waited a minuted after a chunk has finished like you said and then closed out of the console. Next time i started up the commendbot i ran into this issue, how do i go about fixing it? Thanks. https://i.imgur.com/947pCM0.png

**Comment by BeepIsla** [comment]
Lower `friendly`, `teaching` and `leader` in your config. You want to add 26805 commends to your account but only 26408 are available.

Available in this context means:
- Not on cooldown
- Did not commend the target already

**Comment by RealBugzy** [comment]
Now i'm getting a different error lol **Not enough accounts available at the current time, got 14426/26408**. I reconfigured the friendlies and what not to 14426 and now it works fine, thanks for the help!
