### ISSUE TITLE
Question about LOGIN method

### ISSUE THREAD

**Issue by obrabo** [BeepIsla/csgo-commend-bot#338]
I'm using LOGIN method, and i have a question about the perchunks and betweenchunks, what is the best config.json for fast commends without proxies

**Comment by BeepIsla** [comment]
20 per 5 minutes.

**Comment by obrabo** [comment]
If i put 3 minutes, i gonna get timeout?

**Comment by BeepIsla** [comment]
Yes.

**Comment by obrabo** [comment]
OK, thanks for the help!
