### ISSUE TITLE
2 questions about errors

### ISSUE THREAD

**Issue by kakulaaa** [BeepIsla/csgo-commend-bot#339]
**Detailed question description**
When i'm trying using this commend but usually after 20 commends i'm getting some error , The first one is : '**Failed to log in within given 60000ms**', The second one '**Error: RateLimitExceeded\n**'
Can someone please help me and tell me what can/should i do to fix it and be able to do more commends ? Thank you in advance and best regards
**Config**
```
{
	"commend": {
		"friendly": 57,
		"teaching": 57,
		"leader": 57
	},
	"report": {
		"aimbot": 0,
		"wallhack": 0,
		"speedhack": 0,
		"teamharm": 0,
		"abusive": 0
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"proxy": {
		"enabled": true,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/id/ABCABC,
	"perChunk": 50,
	"betweenChunks": 3000,
	"cooldown": 2880000,
	"steamWebAPIKey": "XYZ",
	"disableUpdateCheck": false
}
```

**Version**
- NodeJS: `v12.16.1`
- Script version: `2.7.1`

**Comment by BeepIsla** [comment]
Your proxies are slow/bad/get blocked and Steam doesn't let you log in.

Repeated failing of logins will cause Steam to ban your IP temporarily for 30 minutes. To get rid of this limit do nothing with Steam for 30 minutes, otherwise the 30 minutes reset and you have wait again.

**Comment by kakulaaa** [comment]
> Your proxies are slow/bad/get blocked and Steam doesn't let you log in.
> 
> Repeated failing of logins will cause Steam to ban your IP temporarily for 30 minutes. To get rid of this limit do nothing with Steam for 30 minutes, otherwise the 30 minutes reset and you have wait again.

2nd one - got 
1st one - i tried use proxy just now , so ealier when i got this error without using proxy it can be something with my internet or ?

**Comment by BeepIsla** [comment]
Internet, or Account, or something. Usually its the account having problems so you have to use different accounts, preferably freshly created accounts.

**Comment by kakulaaa** [comment]
> Internet, or Account, or something. Usually its the account having problems so you have to use different accounts, preferably freshly created accounts.

okay , thank you very much for the Help 
Best regards and stay healthy :)

**Comment by gokhannguneey** [comment]
@kakulaaa Can I learn, where you bought it proxys ?
