### ISSUE TITLE
Failed to log in within given 60000ms

### ISSUE THREAD

**Issue by ZAp220** [BeepIsla/csgo-commend-bot#341]
[5XrIgd3HpcD0] Failed to login and has been marked as invalid (20/20) {
  name: 'Error',
  message: 'Failed to log in within given 60000ms',
  stack: 'Error: Failed to log in within given 60000ms\n' +
    '    at Timeout._onTimeout (E:\\csgo-commend-bot-master\\helpers\\account.js:51:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'

```

{
	"commend": {
		"friendly": 23525,
		"teaching": 23525,
		"leader": 23525
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/id/Davidchiorean/",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"steamWebAPIKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	"disableUpdateCheck": false
```

**Version**
- NodeJS: `v12.16.1` 
- Script version: `2.7.1` 

**Additional information**
It happins a lot especially after the 9th login in the first chunk, we hope that u figure out the problem and a solution for it

**Comment by BeepIsla** [comment]
Does it always happen after a specific amount of time and when you restart it works again?

**Comment by ZAp220** [comment]
It happns after the 12th login on the first chunk and the second chunk too

**Comment by BeepIsla** [comment]
It just seems to randomly happen to some specific accounts, try using different accounts and see if the issue continues.

**Comment by ZAp220** [comment]
I tried to make new accounts and the same problem i get... always...

**Comment by BeepIsla** [comment]
Then there is some connection issue between you and Steam. The bots can't establish **any** connection to Steam.
