### ISSUE TITLE
proxy support

### ISSUE THREAD

**Issue by supergosciu** [BeepIsla/csgo-commend-bot#344]
**Config**
{
	"commend": {
		"friendly": 60,
		"teaching": 60,
		"leader": 60
	},
	"report": {
		"aimbot": 19,
		"wallhack": 9,
		"speedhack": 15,
		"teamharm": 12,
		"abusive": 13
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"proxy": {
		"enabled": true,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/profiles/(steam64)",
	"perChunk": 20,
	"betweenChunks": 10000,
	"cooldown": 28800000,
	"steamWebAPIKey": "(apikey)",
	"disableUpdateCheck": false
}

**Version**
- NodeJS: v12.16.1
- Script version: 2.7.1

i can't use my proxies for commendbot, all of my proxies are working (i'm using private proxy), but after 20 successful commends i can't send anymore because of timeout, there's no way that something is wrong with proxies, i'm also using it for steam account generator and it works well but when i'm starting commendbot it sees these proxies (Got 8 proxies) but it doesn't really gives any effect, i have to wait 5 minutes like without proxies

example:
http://user:pass@193.203.51.206:45785

**Comment by BeepIsla** [comment]
It is possible Valve has been changing things and the commend-limit is no longer IP specific. I don't know, can't test it. I don't use proxies.

Only option is that the bot fails to properly use proxies but I doubt that's the reason, I have tested it.

**Comment by Raxana7** [comment]
@supergosciu Can I learn, where you bought it?

**Comment by supergosciu** [comment]
@Raxana7 https://proxy-seller.com/

**Comment by gokhannguneey** [comment]
@supergosciu do you have discord or something. İf you have pls add me gokhannguneey#6383
