### ISSUE TITLE
Installation got corrupted (accidentally pulled out the power cord

### ISSUE THREAD

**Issue by sa3d3** [BeepIsla/csgo-commend-bot#345]
**Detailed question description**
So I accidentally pulled out the power cord while installing npm, and I can't really get to remove this error no matter what I do. I tried reinstalling it on different directories, delted the folder and made a new one and so on, but the issue is still there.

Picture: 
![image](https://user-images.githubusercontent.com/63414841/78915040-c49bee00-7aa4-11ea-9972-508ed3c79c4f.png)

**Config**
```
Your "config.json" - Censor your API Key and account details
haven't edited yet

**Version**

latest version

**Comment by BeepIsla** [comment]
You need to actually fill out the form. You are not helping at all. Just delete the node_modules and run `npm install` again.

**Comment by sa3d3** [comment]
> 
> 
> You need to actually fill out the form. You are not helping at all. Just delete the node_modules and run `npm install` again.

Oh I"m really sorry. I edited the whole thing now

**Comment by sa3d3** [comment]
I tried npm install again but it shows the same error. Should I share one of the log files too?

**Comment by BeepIsla** [comment]
This is in no way related to shutting down your PC.

You have NodeJS v13 installed but you need v12. Uninstall v13 and install v12. The README says this too.

**Comment by sa3d3** [comment]
My bad. I somehow read that as v12 or later. Thank you.

**Comment by BeepIsla** [comment]
You can only use anything after v12 if you install Build Tools and let NodeGYP compile SQLite automatically. Most people don't know how to do this and it would be too much work to instruct people on how to do it. Therefore I just say to install v12.
