### ISSUE TITLE
 Failed to login and due to proxy timeout (1/1)

### ISSUE THREAD

**Issue by alioan** [BeepIsla/csgo-commend-bot#346]
As I mentioned in the title i constantly get this error ( Failed to login and due to proxy timeout (1/1) ) when trying to use proxies in order to log into the accounts. I tried to use a downloaded list of verified proxies as well as proxyes which I verified myself. The ip of the server/the steam url are both correct.

{
	"commend": {
		"friendly": 2,
		"teaching": 2,
		"leader": 2
	},
	"report": {
		"aimbot": 0,
		"wallhack": 0,
		"speedhack": 0,
		"teamharm": 0,
		"abusive": 0
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"proxy": {
		"enabled": true,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "(steam id)",
	"serverID":"188.12.10.248:27015",
	"perChunk": 1,
	"betweenChunks": 500,
	"cooldown": 28800000,
	"steamWebAPIKey": "(api key)",
	"disableUpdateCheck": false

**Comment by BeepIsla** [comment]
1. serverID doesn't exist anymore.

2. How do you know your proxies work on Steam

**Comment by alioan** [comment]
What do u mean by "server id does not exist anymore"

**Comment by BeepIsla** [comment]
Server went offline. Though the error you mentioned only happens when your proxy can't connect to Steam.

**Comment by alioan** [comment]
That specific server might be offline anyway at the moment when i posted i could connect on it

**Comment by BeepIsla** [comment]
Server doesn't matter with this error anyways. Its your proxies failing to connect to Steam.

**Comment by SpaceR3** [comment]
getting same error
i have 1 rotating proxy: http://wont:show@yesyesyes:20000
