### ISSUE TITLE
Add a feature to use another accounts if failed to send message timeout

### ISSUE THREAD

**Issue by h0ay** [BeepIsla/csgo-commend-bot#347]
I want to know  if there is any code or feature to use another account in the chunk when existing account get's timeout  , i want to know if it's possible or not ?

And i don't know if it happens with others or the majority , while i was commending on my account ,when i went to play compe , my trust factor becomes yellow even without any killing of team mate and the rest

My friend has 3000 commends and his trust factor has turned red , is there any fix for it ?

**Comment by BeepIsla** [comment]
Accounts are never re-used during the same run. If an account gets a timeout they are set on cooldown for `cooldown` (In your config.json) milliseconds (Default 6 hours).

After those 6 hours the account may be re-used if you re-run the program.

**Comment by h0ay** [comment]
> 
> 
> Accounts are never re-used during the same run. If an account gets a timeout they are set on cooldown for `cooldown` (In your config.json) milliseconds (Default 6 hours).
> 
> After those 6 hours the account may be re-used if you re-run the program.

So when i get the timeout , is there anyway to use another account in the chunk in place of the failed account ?

**Comment by BeepIsla** [comment]
You mean retry with another account?

**Comment by h0ay** [comment]
> 
> 
> You mean retry with another account?

yes , it will replace the failed account with another account from the databases so there is no interruption and i receive all the 20 commends in 5 minutes , mine some accounts are vac banned,invalid password and sometimes i  get 20 failed to commends , so is there anyway to use another account in case of failed to message ?

**Comment by BeepIsla** [comment]
Such a feature does not exist and I do not plan to add one. The script will tell you at the end how many failed so simply re-run it yourself with that many accounts.

**Comment by h0ay** [comment]
> 
> 
> Such a feature does not exist and I do not plan to add one. The script will tell you at the end how many failed so simply re-run it yourself with that many accounts.

Than feature will be really helpful and will save a lot of time , i will try to add a feature myself

**Comment by h0ay** [comment]
and another issue 

i don't know if it happens with others or the majority , while i was commending on my account ,when i went to play compe , my trust factor becomes yellow even without any killing of team mate and the rest

My friend has 3000 commends and his trust factor has turned red , is there any fix for it ?

**Comment by BeepIsla** [comment]
Commends do not increase Trust Factor.
