### ISSUE TITLE
A Suggestion About Fails

### ISSUE THREAD

**Issue by emreires** [BeepIsla/csgo-commend-bot#349]
If the bot cant send any commend because of fail issues, already commended, or something else. BOT can add more commends.

For example:
I wanted 20 commends.
Bot could not add 5 commends.
So bot can try send 25 commends.

**Comment by BeepIsla** [comment]
So you want the script to automatically retry with different accounts when it fails? This was already suggested #347. I am not going to add this, the script will output the amount of failed commends, just modify your config yourself and run the script again.

**Comment by Raxana7** [comment]
@emreires Kanka yapmaz bu .... harcadığın süreye değmez burda öneri falan yapma. Bundan bir şey yapmasını isteme. Kendi işini kendin yapmazsan hiç bir zaman olmayacak. Bu keyfi ne isterse onu  yapıyor.
