### ISSUE TITLE
 Parsing target account... { type: 'FORBIDDEN'

### ISSUE THREAD

**Issue by mohanadrk** [BeepIsla/csgo-commend-bot#351]
**Detailed bug description**

**Error**

A full error log or screenshot.
![image](https://user-images.githubusercontent.com/63703835/79309066-fc1df680-7ef9-11ea-9e8b-f82bdf0cc52a.png)

**Config**

![image](https://user-images.githubusercontent.com/63703835/79309137-1c4db580-7efa-11ea-9e31-a8890eb5163f.png)

**Version**
- NodeJS: `v12.9.1` 
- Script version: `2.7.1` 

**Additional information**
It worked at first like for about 20 account while i'm doing it my internet went off so i had message like ping ms 30000 and it stuck at this so  i closed it and tried again and said  type: 'FORBIDDEN'
so i tried new 15 account i got same problem as you see in the screenshot

**Comment by BeepIsla** [comment]
Your API Key is invalid

**Comment by mohanadrk** [comment]
> Your API Key is invalid
Oh thanks i changed it and worked for me 
thanks <3
