### ISSUE TITLE
Error: getaddrinfo ENOENT raw.githubusercontent.com

### ISSUE THREAD

**Issue by yq1022** [BeepIsla/csgo-commend-bot#353]
csgo-commend-bot-master> node index.js
 Checking for new update...
Error: getaddrinfo ENOENT raw.githubusercontent.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:26) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'getaddrinfo',
  hostname: 'raw.githubusercontent.com'
} Promise {
  <rejected> Error: getaddrinfo ENOENT raw.githubusercontent.com
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:26) {
    errno: 'ENOENT',
    code: 'ENOENT',
    syscall: 'getaddrinfo',
    hostname: 'raw.githubusercontent.com'
  }

**Comment by BeepIsla** [comment]
You can't connect to Github for update checks.

**Comment by yq1022** [comment]
How can I solve it？

**Comment by BeepIsla** [comment]
Figure out why "https://raw.githubusercontent.com/BeepIsla/csgo-commend-bot/master/package.json" is inaccessible. Something is blocking the connection.
