### ISSUE TITLE
how to fix this error

### ISSUE THREAD

**Issue by kukucsgo** [BeepIsla/csgo-commend-bot#356]
https://cdn.discordapp.com/attachments/665168655964831747/700722706965856358/unknown.png

i got error on every bot acc

**Comment by BeepIsla** [comment]
Fix your internet connection **or** fix your proxies. They ave having issues.

**Comment by xGodThunder** [comment]
@BeepIsla 
![save](https://user-images.githubusercontent.com/48578610/79682710-0ade1380-8242-11ea-8454-472a869f4210.PNG)
when i try to commend, i get this error!
any idea what would be the problem?

**Comment by BeepIsla** [comment]
1. Don't hijack other peoples threads. Create your own

2. You can't commend on Valve Matchmaking/Wingman servers

3. If 2 doesn't help then just try different accounts

**Comment by xGodThunder** [comment]
@BeepIsla thanks man.
