### ISSUE TITLE
What structure should i use in accounts json file?

### ISSUE THREAD

**Issue by EmanuelBalaban** [BeepIsla/csgo-commend-bot#357]
Everything is working but i want to automate something. What structure should i be using for accounts json file when importing?

**Comment by preyan** [comment]
You can use a simple json template like 
**{ username : password }**
To add multiple accounts just use an array.
**[
   { username1 : password },
   { username2 : password },
   { username3 : password },
]**

**Comment by BeepIsla** [comment]
Only an array of objects will work. The second one @preyan mentioned.

**Comment by EmanuelBalaban** [comment]
Thank you. Still i was wandering if there is any way to save username, password and email in same json file.
Something like this:
[
    {
        "username": "john",
        "password": "********",
        "email": "john@gmail.com"
    }
]

**Comment by BeepIsla** [comment]
Only username, password and sharedSecret (optional) gets imported. Anything extra gets ignored
