### ISSUE TITLE
What is protobufs?

### ISSUE THREAD

**Issue by ha6000** [BeepIsla/csgo-commend-bot#361]
**Detailed question description**
I started on the programmatic version but I quickly ran into a issue. I saw that you were using protobufs, but I have never heard of or used protobufs before. I did do some research on what protobufs are what they do, but I wasn't sure what it has to do with this project. I did look around in the code but I didn't really understand what it was for. If you might explain to me what these protobufs have to do with the project

**Comment by BeepIsla** [comment]
https://developers.google.com/protocol-buffers

Protobufs are just a way to encode data so its smaller. Its what Steam uses to keep network usage at a minimum.

---

Without prior Steam communication knowledge you will probably have a hard time making this from scratch. Just use pre-made libraries (Like I use [Steam-User](https://github.com/DoctorMcKay/node-steam-user/) in this project and there are many equivalents across many languages) and let them handle the actual Steam communication part so you have to do bare minimum work.
