### ISSUE TITLE
"SERVER" method idea

### ISSUE THREAD

**Issue by Vejas04** [BeepIsla/csgo-commend-bot#362]
Hello,
not an issue but a quick idea which would be awesome to add to your Commend Bot.
Is it possible to write or rewrite the script, to commend bot someone with the "SERVER" method without being "in CS:GO" basically, to save up CPU usage? To join a deathmatch or other kind of server in which you can get commend bottet and also stay there afk. If kicked, to reconnect. Just let me know if something like that would interest you and if it's even working ;)
Regards

**Comment by BeepIsla** [comment]
Get access to the targets account details and use LOGIN method. Only way.
