### ISSUE TITLE
Failed to reportbot with script

### ISSUE THREAD

**Issue by Nico1022-stack** [BeepIsla/csgo-commend-bot#364]
Hello everyone! I recently downloaded the script, yesterday I tried to report button a person, but when I start the script it gives me with all 16 accounts this error. 
how is it possible to solve? thank you very much!:

[jessieblank1987] Failed to report (16/16) {  name: 'Error',  message: 'Failed to send message: Timeout',  stack: 'Error: Failed to send message: Timeout\n'
Chunk 1/1 finished with 0 successful reports and 16 failed reports
all give this error
at Timeout._onTimeout (C:\\Users\\nico\\Desktop\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:124:12)\n' +    '    at listOnTimeout (internal/timers.js:549:17)\n' +    '    at processTimers (internal/timers.js:492:7)'

**Comment by BeepIsla** [comment]
What server? Valve Matchmaking? Valve Wingman? Valve Casual? Community Servers?

**Comment by Nico1022-stack** [comment]
did a competitive one. then he left the game. at the competitive end after a few minutes I tried to make the report

**Comment by BeepIsla** [comment]
Not in-game = Can't report/commend.

**Comment by Nico1022-stack** [comment]
if it had been in game would it have been possible to report?

**Comment by Nico1022-stack** [comment]
because I think it would have given me the same mistake. but yesterday was the first time, I should try a second one and see, in case I write it here, in the meantime thank you very much for the support and your availability! :)

**Comment by BeepIsla** [comment]
1. Player has to be in the match

2. Has to be at the match-end screen

**Comment by Nico1022-stack** [comment]
but then the report should be done when the player is in competition? at the end of the competition is already no longer possible?

**Comment by BeepIsla** [comment]
You cannot report while the match is on-going but as soon as the match ends and your team reaches 16 wins you can send reports/commends.

You just have to hope your target doesn't leave before the bots login and send their report/commend.

That's all I know.

**Comment by Nico1022-stack** [comment]
so at the competitive end since I arrive in the 16th round can I make the report? if you exit the competitive round 16 and stay in the home of cs can you always report? and if he goes out and goes to play other modes is it possible or not valid?

**Comment by BeepIsla** [comment]
> so at the competitive end since I arrive in the 16th round can I make the report?

Yes

> if you exit the competitive round 16 and stay in the home of cs can you always report?

Maybe?

> and if he goes out and goes to play other modes is it possible or not valid?

Yes, not possible.

**Comment by Nico1022-stack** [comment]
therefore you can report it only if he leaves the comp and remains in the game home. if you close it or go in other ways is not possible?

**Comment by BeepIsla** [comment]
If he doesn't leave and stays at the end of the match you can report too.

**Comment by Nico1022-stack** [comment]
yes but if you get to the 16th round and maybe he leaves the round before the game, and stays with the game open, you can still do (?)

**Comment by BeepIsla** [comment]
Maybe, most likely not.

**Comment by Nico1022-stack** [comment]
it is practically impossible to implement a reportbot, commendation is only possible

**Comment by ra3er** [comment]
@BeepIsla maybe u will do reportbot with discord comamnds? :D 
Also report bot with matchid!

**Comment by BeepIsla** [comment]
No

**Comment by ra3er** [comment]
@BeepIsla what are you working on now, because your things are impressive.
