### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by inbroso** [BeepIsla/csgo-commend-bot#365]
i actually dont know what it is, just 

https://i.imgur.com/8WLpeyz.png

**Config**
```
{
	"commend": {
		"friendly": 20,
		"teaching": 20,
		"leader": 20
	},
	"report": {
		"aimbot": 10,
		"wallhack": 10,
		"speedhack": 10,
		"teamharm": 10,
		"abusive": 10
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"proxy": {
		"enabled": true,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/id/******",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"steamWebAPIKey": "****",
	"disableUpdateCheck": false
}


**Version**
- NodeJS: `v12.9.1` (You can find this using `node -v`)
- Script version: `2.7.1` (You can find this in **your** `package.json` file under `version`)

**Comment by BeepIsla** [comment]
Please verify that your `protobufs` folder structure looks like this:

- `<root>/protobufs/csgo/cstrike15_gcmessages.proto`
- `<root>/protobufs/steam/steammessages_clientserver.proto`

**Comment by inbroso** [comment]
yeah the protobufs folder structure looks like that

**Comment by BeepIsla** [comment]
Does this file also exist `<root>/protobufs/steam/enums_clientserver.proto`? Its the file which it seems to be unable to load.

You can try entirely deleting your `protobufs` folder, the program should automatically re-download.

**Comment by inbroso** [comment]
nope didnt exist, i now deleted the protobufs folder and now there is this error: 
https://i.imgur.com/mcoXFqF.png

**Comment by BeepIsla** [comment]
Apologies, this happened in one of the latest pull requests. I have fixed this. Please re-download and try again.

**Comment by inbroso** [comment]
now it works, thanks!
