### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Szarak2004** [BeepIsla/csgo-commend-bot#366]
TypeError: Cannot read property 'k_EMsgGCClientHello' of undefined
    at SteamUser.loggedOn (C:\Users\czarq\Desktop\csgo-commend-bot-master\csgo-commend-bot-master\helpers\account.js:113:50)
    at process._tickCallback (internal/process/next_tick.js:68:7) Promise {
  <rejected> TypeError: Cannot read property 'k_EMsgGCClientHello' of undefined
      at SteamUser.loggedOn (C:\Users\czarq\Desktop\csgo-commend-bot-master\csgo-commend-bot-master\helpers\account.js:113:50)
      at process._tickCallback (internal/process/next_tick.js:68:7) }

I just get this help

**Comment by BeepIsla** [comment]
Delete your `protobufs` folder and retry.

**Comment by Szarak2004** [comment]
Failed to log into Steam using account as target Error: GC connection timeout - Hello
    at SteamUser.loggedOn (C:\Users\czarq\Desktop\csgo-commend-bot-master\csgo-commend-bot-master\helpers\account.js:128:14)

This happens now, tried several times to do node index.js

**Comment by BeepIsla** [comment]
Whats your config?

**Comment by Szarak2004** [comment]
{
	"commend": {
		"friendly": 10,
		"teaching": 10,
		"leader": 10
	},
	"report": {
		"aimbot": 10,
		"wallhack": 10,
		"speedhack": 10,
		"teamharm": 10,
		"abusive": 10
	},
	"account": {
		"username": "rudzicka472b",
		"password": "**l******e*1****",
		"sharedSecret": ""
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "LOGIN",
	"target": "https://steamcommunity.com/id/raze04",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 120000,
	"steamWebAPIKey": "86D57E605A*************541078F",
	"disableUpdateCheck": false
}


the API key and Password IS vaild

**Comment by BeepIsla** [comment]
Does it happen on a chunk or at the very beginning?

**Comment by Szarak2004** [comment]
Checking for new update...
 Up to date!
 Checking protobufs...
 Found protobufs
 Opening database...
 There are a total of 10 operational accounts
 Logging into target account...
 Failed to log into Steam using account as target Error: GC connection timeout - Hello
    at SteamUser.loggedOn (C:\Users\czarq\Desktop\csgo-commend-bot-master\csgo-commend-bot-master\helpers\account.js:128:14)

On logging in

**Comment by BeepIsla** [comment]
It can't establish connection to CSGO. Make sure to not have CSGO open yourself.

**Comment by Szarak2004** [comment]
{ name: 'TypeError',
  message:
   '[target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function',
  stack:
   'TypeError: [target,(...(intermediate value)(intermediate value)(intermediate value))].flat is not a function\n    at a.login.then (C:\\Users\\czarq\\Desktop\\csgo-commend-bot-master\\csgo-commend-bot-master\\helpers\\Bots.js:88:7)\n    at process._tickCallback (internal/process/next_tick.js:68:7)' }


This happens on every account

**Comment by Szarak2004** [comment]
Oh sorry it was me being dumb, nevermind because I changed config pass and API key

**Comment by BeepIsla** [comment]
That error comes from not having NodeJS v12 installed. You have to install it.

**Comment by Szarak2004** [comment]
It's working! Thank you!
