### ISSUE TITLE
Why do I get this error and how can I fix it?

### ISSUE THREAD

**Issue by AbbeLabben** [BeepIsla/csgo-commend-bot#367]
PS C:\WINDOWS\system32> node index.js
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module 'C:\WINDOWS\system32\index.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:862:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)[39m
[90m    at internal/main/run_main_module.js:18:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}
PS C:\WINDOWS\system32>

**Comment by BeepIsla** [comment]
You are in the wrong folder. Search "How to open a command prompt in a folder".
