### ISSUE TITLE
getting stuck in chunks again...

### ISSUE THREAD

**Issue by ZAp220** [BeepIsla/csgo-commend-bot#368]
Getting stuck on every chunk...i have to press space on the windows PowerShell to continue

**Config**
{
	"commend": {
		"friendly": 15615,
		"teaching": 15615,
		"leader": 15615
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/id/Davidchiorean/",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"steamWebAPIKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxx",
	"disableUpdateCheck": false
}

Your "config.json" - Censor your API Key and account details
```

**Version**
- NodeJS: `v12.16.2` 
- Script version: latest version
and one more thing...

[P2mpt6qkm07w] Failed to commend (20/20) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (E:\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
}
 I get this message on the last account login on every chunk...i don't think that I have a problem with that account cuz I tried to login manually and I commended myself from that account...so it must be a problem with the bot or sth like  that.

**Comment by BeepIsla** [comment]
Last of chunk fails often, I don't know why.

The script never waits for your input. It makes no sense that you have to press space to continue.

Try using a command prompt instead of powershell.
