### ISSUE TITLE
RateLimitExceeded Explanation

### ISSUE THREAD

**Issue by sayhitomepls** [BeepIsla/csgo-commend-bot#372]
name: 'Error',
  message: 'RateLimitExceeded',
  stack: 'Error: RateLimitExceeded\n' +

I want the explanation of this error
P.S.I'm a newbie

**Comment by BeepIsla** [comment]
You had too many failed login attempts. Valve is now blocking your IP from logging into Steam for the next 30 minutes. Trying to login anyways will result in that timer to be reset and you have to wait 30 minutes again.
