### ISSUE TITLE
#373

### ISSUE THREAD

**Issue by smurfsmfc** [BeepIsla/csgo-commend-bot#376]
**Detailed bug description**
Sir same error as that of #373 please help
Thanks in advance

**Error**
```
A full error log or screenshot.
```

**Config**
```
Your "config.json" - Censor your API Key and account details
```

**Version**
- NodeJS: `vXX.XX.X` (You can find this using `node -v`)
- Script version: `X.X.X` (You can find this in **your** `package.json` file under `version`)

**Additional information**
Add any other potentially useful information about your issue here.

**Comment by BeepIsla** [comment]
If you already know you have the same error then read the response I made to it.
