### ISSUE TITLE
Wont get commends although bot says successfully

### ISSUE THREAD

**Issue by slative** [BeepIsla/csgo-commend-bot#377]
Hey, first of all i want to say that is happing for me, i dont know if this is a public issue or not.
I allready used the bot to commend me and everything worked fine.

First i mad like 450 commends, 1 week later i made 100 commends.
Now i want to make like 500 commends. Currently i have 464 commends.

I tried a lot of ways, like method: SERVER on Casual or Community Servers, 
or method:LOGIN. It says successfully commended and in CS:GO too, but i dont receive them.
The bot says always like 50 successfully commends, but i got like 1-3 or sometimes no single commend.

I tried to reinstall the bot, reseted the database, use proxies (tried with and without), diffrent settings, diffrent steam api keys.

Is there a max limit for getting commended per week or i dont know.

Please help me, thank you

**Comment by BeepIsla** [comment]
The only limit I know that exists is 20 per 5 minutes per IP. Though things could change at any time, I don't know.

What you are experiencing is a known issue and I do not know why this happens, it seems to just be randomly.

**Comment by slative** [comment]
Okay, thank you for the quick answer. 
Do you have some ideas what i can do? Like should i use proxies? and some recommended settings (perChunk, chunkTime, cooldown)

**Comment by amx22** [comment]
modem restart new ip after try work

**Comment by BeepIsla** [comment]
No more information about this is available. There is no reason to keep this issue open.
