### ISSUE TITLE
Cannot read property 'k_EMsgClientAuthList'

### ISSUE THREAD

**Issue by IICRAZYII** [BeepIsla/csgo-commend-bot#378]
I am currently having this error when trying to send commends:

(node: 7980) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'k_EMsgClientAuthList' of undefined
     at C: \ Administrator \ Desktop \ csgo-commend-bot \ helpers \ account.js: 257: 37
(node: 7980) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch (). (rejection id: 1)

**Comment by BeepIsla** [comment]
Delete your protobufs folder and try again

**Comment by IICRAZYII** [comment]
thanks, this I solve
