### ISSUE TITLE
Csgo comment bot not enough accounts available at the current time issue how to fix? 

### ISSUE THREAD

**Issue by HyperN0va1** [BeepIsla/csgo-commend-bot#379]
Idk why when I left my account for overnight to receive mass commend my net went off and then I got disconnected, it reconnected but only commend bot was working and each commend was getting failed because I was not in a server. 

When I got up in the morning, I restarted power shell and started giving commends again, this time I got an error saying only 6.5k accounts out of 10k were available but I got 2k commends at night, rest got failed due to no connection.

What to do? how to fix them? I hope my accounts are safe.

**Comment by BeepIsla** [comment]
If you have 10K accounts and 2K commends were sent that means 8K are available for your account. But you said only 6.5K are available, so this likely means the other 1.5K are on cooldown. Wait until it ends or change your `cooldown` setting in your config. Its also possible a few handful ones failed to login due to the mentioned connection issue and that likely caused some accounts to be marked as invalid.

**Comment by HyperN0va1** [comment]
> If you have 10K accounts and 2K commends were sent that means 8K are available for your account. But you said only 6.5K are available, so this likely means the other 1.5K are on cooldown. Wait until it ends or change your `cooldown` setting in your config. Its also possible a few handful ones failed to login due to the mentioned connection issue and that likely caused some accounts to be marked as invalid.

I guess my csgo account stayed disconnected for 8 hours(I was sleeping) but after net came back the bot started giving commends and failed, what's cooldown? I'm very new to this, are you in discord?

**Comment by BeepIsla** [comment]
Default cooldown is 8 hours, you can see it all described in the README and and in your config.

If you have issues you can simply create an issue here. It helps others who might have a similar issue too.

**Comment by HyperN0va1** [comment]
> Default cooldown is 8 hours, you can see it all described in the README and and in your config.
> 
> If you have issues you can simply create an issue here. It helps others who might have a similar issue too.

what does cooldown basically means? does this prevents bans or it is just set for sake? If I change it my account will be safe?

**Comment by BeepIsla** [comment]
You can give out 3 commends per 24 hours per account. 24 / 3 is 8. 1 commend per 8 hours is the same as 3 commends per 24 hours.

You can change anything in your config and it won't impact your accounts. If you are *super* concerned about it just create a backup of the `accounts.sqlite` file. It stores everything related to bot-accounts and commend-history.

**Comment by HyperN0va1** [comment]
> You can give out 3 commends per 24 hours per account. 24 / 3 is 8. 1 commend per 8 hours is the same as 3 commends per 24 hours.
> 
> You can change anything in your config and it won't impact your accounts. If you are _super_ concerned about it just create a backup of the `accounts.sqlite` file. It stores everything related to bot-accounts and commend-history.

tysm, I understood that even the accounts which failed are also having the cooldown, tysm, btw if I have another doubt, should I ask here or create a new issue? thanks for help

**Comment by BeepIsla** [comment]
Doesn't really matter. I recommend if its related to this question just re-open and commend here. If its something entirely different create a new one.

**Comment by HyperN0va1** [comment]
> Doesn't really matter. I recommend if its related to this question just re-open and commend here. If its something entirely different create a new one.

well it's different but very small issue, like if I have already commended like 3-4k accounts from the list of 10k accounts, is there any way to skip them? cuz 4k/20= 200,200*5=1000, so 1000 minutes will be wasted.

**Comment by BeepIsla** [comment]
Unless you reset your database and commend-history is lost the script will not re-use already used accounts.

**Comment by HyperN0va1** [comment]
> Unless you reset your database and commend-history is lost the script will not re-use already used accounts.

tysm man +rep
