### ISSUE TITLE
How to pause giving commends, is there any list from where I can see all the functions?

### ISSUE THREAD

**Issue by HyperN0va1** [BeepIsla/csgo-commend-bot#380]
Question is the title, thanks for help

**Comment by BeepIsla** [comment]
You cannot pause. Just terminate the script using CTRL + C.

The only thing you need to know as a simply user is how to adjust the config.

How the entire thing works internally you can simply read the code for.

**Comment by HyperN0va1** [comment]
> You cannot pause. Just terminate the script using CTRL + C.
> 
> The only thing you need to know as a simply user is how to adjust the config.
> 
> How the entire thing works internally you can simply read the code for.

Thank you once again
