### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by zipwq** [BeepIsla/csgo-commend-bot#381]
I tried to give someone commends on a stream but when i run the index.js the account logged onto steam and the empty lines between the connection information line (blue lines). I have waited some time and then i got the error with Timeout!

**Comment by BeepIsla** [comment]
Use a commend prompt instead of a powershell. Blue text on blue background doesn't look good.

What server was your target on?

**Comment by zipwq** [comment]
On a workshop map the bot works perfectly but on a competitive valve doesn't work.

**Comment by BeepIsla** [comment]
I don't know why it failed, I just assume offline with bots doesn't work but I don't know for sure.

**Comment by zipwq** [comment]
It's there a method that I can give commends to a player while he is playing matchmaking (competitive/wingman/deathmatch)? Or maybe on FACEIT / ESEA servers?

**Comment by BeepIsla** [comment]
Valve Comoetitive and Valve Wingman do not work and there is no workaround.

**Comment by zipwq** [comment]
That's my config for FACEIT, is it ok?

    {
	"commend": {
		"friendly": 350,
		"teaching": 350,
		"leader": 350
	},
	"report": {
		"aimbot": 10,
		"wallhack": 10,
		"speedhack": 10,
		"teamharm": 10,
		"abusive": 10
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "his profile",
	"perChunk": 20,
	"betweenChunks": 305000,
	"cooldown": 28800000,
	"steamWebAPIKey": "my steam api key",
	"disableUpdateCheck": false
}

**Comment by BeepIsla** [comment]
There are no special settings needed. This should be fine. Unless FACEIT has some Valve authentication or there is a server-command I don't know about.

**Comment by zipwq** [comment]
Ok, thanks!
