### ISSUE TITLE
I used proxy but my internet connection has ping

### ISSUE THREAD

**Issue by drairox** [BeepIsla/csgo-commend-bot#382]
Hello dear Beeplslsa i used bot with proxy but my internet have ping why is it? it is normal or not?

**Comment by BeepIsla** [comment]
What does this mean?

**Comment by drairox** [comment]
I use the bot with proxy but my internet is very lag why?

**Comment by drairox** [comment]
sorry my bad english :(

**Comment by BeepIsla** [comment]
Depending on your config over 20 connections to Steam are established at once. Its possible this is simply too much for your internet connection.

Proxies still use your internet connection, so that doesn't matter.

**Comment by drairox** [comment]
ok thanks for helping
