### ISSUE TITLE
Proxy error

### ISSUE THREAD

**Issue by drairox** [BeepIsla/csgo-commend-bot#383]
**Detailed bug description**

**Error**
```
A full error log or screenshot.
```
https://prnt.sc/s6ehxy
**Config**
```
Your "config.json" - Censor your API Key and account details
```
{
  "commend": {
    "friendly": 100,
    "teaching": 100,
    "leader": 100
  },
  "report": {
    "aimbot": 0,
    "wallhack": 0,
    "speedhack": 0,
    "teamharm": 0,
    "abusive": 0
  },
  "account": {
    "username": "",
    "password": "",
    "sharedSecret": ""
  },
  "proxy": {
    "enabled": true,
    "file": "proxies.txt",
    "switchProxyEveryXaccounts": 20
  },
  "type": "COMMEND",
  "method": "SERVER",
  "target": "https://steamcommunity.com/profiles/76561199033895512/",
  "perChunk": 20,
  "betweenChunks": 5,
  "cooldown": 100500,
  "steamWebAPIKey": "",
  "disableUpdateCheck": false
}
**Version**
- NodeJS: `v12.16.2` (You can find this using `node -v`)
- Script version: `2.7.1` (You can find this in **your** `package.json` file under `version`)

**Additional information**
Add any other potentially useful information about your issue here.

**Comment by BeepIsla** [comment]
What are your proxies, something is broken. Seens like you have invalid charactere in the url.

**Comment by drairox** [comment]
https proxies sir

**Comment by BeepIsla** [comment]
I don't think that would cause such errors, I think there are extra characters on the proxies which are not suppose to be there. Make sure its a valid URL.

Also HTTPS proxies are not support, only HTTP.

As per README:

> **ONLY HTTP proxies are supported**

**Comment by drairox** [comment]
When I used the old http proxies, there was no such error. Can there be a problem with my proxies?

**Comment by BeepIsla** [comment]
As I said: Your `proxies.txt` has invalid characters which can't be processed. Fix your `proxies.txt` file.

**Comment by drairox** [comment]
I use https proxy, I was scraping them with the program, but I think I bought new ones from other sites, I think they should be

**Comment by drairox** [comment]
sir i scraped new proxy but the problem still continues
proxy is http

**Comment by BeepIsla** [comment]
Show your `proxies.txt`

**Comment by drairox** [comment]
https://prnt.sc/s6n14i

**Comment by BeepIsla** [comment]
Download `Notepad++` and edit your `proxies.txt`, select `UTF-8` from the `Encoding` tab and save it. Then try again.

**Comment by drairox** [comment]
they working sir i sorry for this thank you for helping.
