### ISSUE TITLE
If accounts get vacced, are commends removed??

### ISSUE THREAD

**Issue by HyperN0va1** [BeepIsla/csgo-commend-bot#384]
And can I split accounts and use multiple devices with different api keys to give commends faster?

**Comment by BeepIsla** [comment]
> Are commends removed when the account is banned?

No.

> Can you split accounts and use multiple devices with different API keys to give commends faster?

As far as I know as long as they have different IP's yes. API keys do not matter at all, you can use the same one for everything.

**Comment by HyperN0va1** [comment]
Fastest response man, ty
