### ISSUE TITLE
Proxy removing suggestion

### ISSUE THREAD

**Issue by deluxanN** [BeepIsla/csgo-commend-bot#385]
Hello! This can be marked as a suggestion. I had this idea on my mind about the invalid proxies. What about removing them on specific errors? Would it be hard to implement? Just wanted to ask. Nevertheless, great work! Love using the script.
Have a great day!

**Comment by BeepIsla** [comment]
Possible but I don't want to modify the proxies file. Also the script supports different proxy file formats, so modifying it is a bit harder and not a simply "Remove Proxy & Write file".

The biggest issue is what if proxies **do** work but you either reached your usage limit for the day, your own internet connection cut out, the proxy temporarily went offline or Steam is having connection issues.

All these things and probably more I didn't think of make it not that easy to implement a system which removes bad proxies. I rather just leave it to the user to remove bad proxies themselves.

**Comment by deluxanN** [comment]
Oh, okay. Could you please specify what type of proxies should be used? Or just HTTP(S) proxies? I had many of them and just barely some work.

**Comment by BeepIsla** [comment]
As per README:

> **ONLY HTTP proxies are supported**

**Comment by deluxanN** [comment]
Oh well, okay.
Thank you so much.
Closing this thread
