### ISSUE TITLE
Proxy Error

### ISSUE THREAD

**Issue by TyLinfoot** [BeepIsla/csgo-commend-bot#386]
Hey. 

So i'm running the accounts on some HTTP proxies that I checked with a premium tool checker, I use the working ones only but I get this error;

` [gary1994mann] Failed to login and due to proxy timeout (15/15) {
  name: 'Error',
  message: 'HTTP CONNECT 403 Forbidden',
  stack: 'Error: HTTP CONNECT 403 Forbidden\n' +
    '    at ClientRequest.<anonymous> (C:\\Users\\tinfo\\Desktop\\Commends\\csgo-commend-bot-master\\node_modules\\steam-user\\components\\connection_protocols\\tcp.js:59:29)\n' +
    '    at ClientRequest.emit (events.js:315:20)\n' +
    '    at Socket.socketOnData (_http_client.js:517:11)\n' +
    '    at Socket.emit (events.js:315:20)\n' +
    '    at addChunk (_stream_readable.js:297:12)\n' +
    '    at readableAddChunk (_stream_readable.js:273:9)\n' +
    '    at Socket.Readable.push (_stream_readable.js:214:10)\n' +
    '    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)'
}`

I'm going to assume its because of dead proxies even though they should be working but I just want to check as I might be doing something wrong.

Proxies file is in this format;

ip:port
ip:port

(.txt)

and the config:

	"proxy": {
		"enabled": true,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 15
	},

**Comment by BeepIsla** [comment]
Proxies which might work on the Steam websites don't necessarily work when logging in too.

Logins have much stricter proxy restrictions than the website.

**Comment by TyLinfoot** [comment]
Alright. Just to confirm that's basically saying the proxy is dead (for steam)?

**Comment by BeepIsla** [comment]
Either proxy or steam returned `HTTP CONNECT 403 Forbidden`, and just like it says just means you're not allowed to access this.

Either the proxy requires authentication or Steam is blocking it.
