### ISSUE TITLE
ACCOUNTS with VAC

### ISSUE THREAD

**Issue by zipwq** [BeepIsla/csgo-commend-bot#387]
Hi! Why can't i use accounts with VAC?

Config:
    {
	"commend": {
		"friendly": 1000,
		"teaching": 1000,
		"leader": 1000
	},
	"report": {
		"aimbot": 10,
		"wallhack": 10,
		"speedhack": 10,
		"teamharm": 10,
		"abusive": 10
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/id/zipwq/",
	"perChunk": 20,
	"betweenChunks": 305000,
	"cooldown": 28800000,
	"steamWebAPIKey": "my api",
	"disableUpdateCheck": false
}

Version:
- NodeJS: v12.16.2
- Script version: 2.7.1

**Comment by BeepIsla** [comment]
Because as far as I know you cannot commend others if you are banned. So why would I allow VAC banned accounts.

**Comment by zipwq** [comment]
As far as I know, VAC accounts can give commends

**Comment by BeepIsla** [comment]
Try it out, log into a VAC banned account, give a commend on an insecure server, show before after picture of their commend count

**Comment by zipwq** [comment]
I dont have an VAC account, thank you for support
