### ISSUE TITLE
Request error

### ISSUE THREAD

**Issue by bandiron** [BeepIsla/csgo-commend-bot#388]
Hello. I have some sort of error. How to fix it? 
![Скриншот 29-04-2020 165842](https://user-images.githubusercontent.com/41580521/80604713-be14ec80-8a3a-11ea-8f50-159ba9f02c38.png)

**Comment by BeepIsla** [comment]
Just like the linked website tells you:

> The server is currently unable to handle the request due to a temporary overload or scheduled maintenance, which will likely be alleviated after some delay.

Github was temporarily inaccessible for you, just retry in a few minutes.
