### ISSUE TITLE
why cant i commend myself thrice with the same bots??

### ISSUE THREAD

**Issue by ryanlawrence742** [BeepIsla/csgo-commend-bot#391]
**Detailed question description**
A clear and concise description of your question.

**Config**
```
Your "config.json" - Censor your API Key and account details
```

**Version**
- NodeJS: `vXX.XX.X` (You can find this using `node -v`)
- Script version: `X.X.X` (You can find this in **your** `package.json` file under `version`)

**Comment by BeepIsla** [comment]
Go in-game and commend someone. Now try to commend them again.

Spoiler: It doesn't work, that's why.
