### ISSUE TITLE
Set account operational

### ISSUE THREAD

**Issue by Kasoar** [BeepIsla/csgo-commend-bot#392]
**Detailed question description**
Hey what is the option "Set account operational" doing? Because everytime I write something in there it says "Failed to set operational status of "..." to True - Username not found.".

**Comment by BeepIsla** [comment]
When accounts fail to login they are marked as "Non-Operational" and will never be used again by the system. If you want to change this you can use the "Set account operational" option with the account name to set it as "Operational" again so the account is considered usable again.
