### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by AN9GRY** [BeepIsla/csgo-commend-bot#393]
i was trying to setup the commend bot and i get this error everytime
![Przechwytywanie](https://user-images.githubusercontent.com/64664396/80841536-ed288b00-8bff-11ea-85c6-17ed49c4747e.PNG)

**Comment by BeepIsla** [comment]
Something is preventing the script from connecting to the CSGO backend. Make sure you aren't already logged into the account.

**Comment by AN9GRY** [comment]
another error appears
![Przechwytywanie](https://user-images.githubusercontent.com/64664396/80842078-0251e980-8c01-11ea-9f43-3adb70007e39.PNG)

**Comment by BeepIsla** [comment]
Your proxy is bad, blocked by Steam or has general issues.

**Comment by AN9GRY** [comment]
i have a diffrent error now
![Przechwytywanie](https://user-images.githubusercontent.com/64664396/80845277-0e41a980-8c09-11ea-893e-838d82fb4cd4.PNG)

**Comment by BeepIsla** [comment]
Read the error, the proxy needs authentication to be used.
