### ISSUE TITLE
How to remove not working accounts?

### ISSUE THREAD

**Issue by Andriuxas** [BeepIsla/csgo-commend-bot#394]
When i try to remove accounts it just exports to notworking.txt but not removes. How do i need remove not working accounts then?

**Comment by BeepIsla** [comment]
You don't have to do this, it doesn't have any impact on the bot.

Just select `Remove all not working accounts` in the database manager and then select `No`. It will remove all non-working accounts.

**Comment by Andriuxas** [comment]
Awww okay

**Comment by Andriuxas** [comment]
Ur answering so fast 👯
