### ISSUE TITLE
Still cant remove not working accounts.

### ISSUE THREAD

**Issue by Andriuxas** [BeepIsla/csgo-commend-bot#396]
Cant remove not working accounts i select no and then there is in txt of my accounts same ammount of accounts.

**Comment by BeepIsla** [comment]
Then you are doing something wrong. You can [read the code](https://github.com/BeepIsla/csgo-commend-bot/blob/master/databaseManager.js#L89) yourself.

> `DELETE FROM accounts WHERE operational = 0`

It deletes all accounts which marked as not-operational. Are you sure the accounts are not operational and not just on-cooldown?

**Comment by Andriuxas** [comment]
There was alot of steam guard enabled accounts.

**Comment by Andriuxas** [comment]
Can u help me on discord? i will screenshare 2 mins of ur time.

**Comment by BeepIsla** [comment]
You can look yourself and try to run it manually. Download [SQLite Browser](https://sqlitebrowser.org/) and open up your `accounts.sqlite` with it. In the run menu enter `DELETE FROM accounts WHERE operational = 0;` and click execute, see what it outputs.

> Can u help me on discord? i will screenshare 2 mins of ur time.

No. Just make a screenshot and post it here.

**Comment by Andriuxas** [comment]
Okay

**Comment by Andriuxas** [comment]
![image](https://user-images.githubusercontent.com/64680439/80862480-30294380-8c7e-11ea-9950-ec93a6d2d27c.png)

**Comment by Andriuxas** [comment]
here?

**Comment by BeepIsla** [comment]
Yes

**Comment by Andriuxas** [comment]
![image](https://user-images.githubusercontent.com/64680439/80862525-88f8dc00-8c7e-11ea-90ae-5a99c1f774fe.png)

**Comment by BeepIsla** [comment]
All non-operational accounts are already removed.

**Comment by Andriuxas** [comment]
But still there is same amount of accounts in txt file.

**Comment by Andriuxas** [comment]
I don't understand. 
![image](https://user-images.githubusercontent.com/64680439/80862603-f86ecb80-8c7e-11ea-9187-6416f3d35234.png)

**Comment by Andriuxas** [comment]
Maybe cuz i didnt this? 
![image](https://user-images.githubusercontent.com/64680439/80862629-205e2f00-8c7f-11ea-83ff-5994388dc6b3.png)

**Comment by BeepIsla** [comment]
There are no accounts which are marked as non-operational.

There is nothing more I can say to this, just run the bot again and see what happens. All accounts are marked as working.

**Comment by Andriuxas** [comment]
![image](https://user-images.githubusercontent.com/64680439/80862669-8b0f6a80-8c7f-11ea-8f90-7a6f00ffc94e.png)

**Comment by BeepIsla** [comment]
Click on "Write" in SQLite Browser to close the database.

**Comment by Andriuxas** [comment]
Write changes yah?

**Comment by BeepIsla** [comment]
Yes

**Comment by Andriuxas** [comment]
Yah and what to do now?

**Comment by BeepIsla** [comment]
Just try importing again

**Comment by Andriuxas** [comment]
Yah?

**Comment by Andriuxas** [comment]
and then ? :D

**Comment by BeepIsla** [comment]
Yeah just use the bot....

**Comment by Andriuxas** [comment]
but when these accounts will be deleted from txt?

**Comment by Andriuxas** [comment]
im braindead today..

**Comment by BeepIsla** [comment]
There are no accounts which need to be deleted, all accounts are working according to the database. So there is nothing you can do, just run it and wait for errors.

**Comment by Andriuxas** [comment]
Yah and then when i commend all of these with errors then i click remove all not working accounts and  they will dissapear in accounts txt?

**Comment by BeepIsla** [comment]
The bot will never touch your accounts.txt

It is impossible for accounts to fail and then not be marked as non-operational.

Screenshot the output when you use the bot, the error.

**Comment by Andriuxas** [comment]
![image](https://user-images.githubusercontent.com/64680439/80862904-3967df80-8c81-11ea-8e4d-4eaa30fc147e.png)
i need reset database? cuz i had 143 accounts cant add them.

**Comment by BeepIsla** [comment]
Resetting your database won't change anything and will just make things worse. Resetting your database deletes everything stored in it including commend-history. No commend history = Bots which already commended you try to do it again.

All accounts from the `accounts_1 N` file are already in the database and there are no non-working accounts.

---

What even is the problem you are having?

> Not enough accounts available at the current time, got 16/143

Is this your problem? Because that just means you want to use 143 accounts but only 16 are available, why? Because all the others are on cooldown. So wait until the cooldown is over or change the cooldown value in your config.

**Comment by Andriuxas** [comment]
Okay i know that im braindead today xD

**Comment by BeepIsla** [comment]
Is your issue resolved/explained?

**Comment by Andriuxas** [comment]
I will try..

**Comment by Andriuxas** [comment]
![image](https://user-images.githubusercontent.com/64680439/80863326-20acf900-8c84-11ea-8b8c-6e8ac59d6735.png)

**Comment by Andriuxas** [comment]
And now i need to select remove accounts?

**Comment by BeepIsla** [comment]
Wait for it to finish, and at the end try just removing accounts the normal way using the database manager and select "Yes", then look how many accounts are in the file.

**Comment by Andriuxas** [comment]
But i have 2k accounts but i imported only 100 so when 100 done i can do this yah?

**Comment by BeepIsla** [comment]
Yes

**Comment by Andriuxas** [comment]
So next time it wont commend with these not working accounts?

**Comment by BeepIsla** [comment]
Yes. Accounts which are marked as non-operational will never be used again.

**Comment by Andriuxas** [comment]
But bro when i give other other commends and then click remove not working accounts its just replaces another accounts not working,..

**Comment by Andriuxas** [comment]
It justs removes old not working accounts.. And adding news.

**Comment by BeepIsla** [comment]
You can't commend with the same person twice unless you have more accounts. Accounts are likely on cooldown at the moment.

Deleting non-operational accounts doesn't delete their commend history, so if you re-add them they won't try to commend the same person again.

You can just leave the accounts in the database, they don't do any harm. Why do you want to remove then?

**Comment by Andriuxas** [comment]
Bro u dont understand when i commended yah myself like 200 commends i clicked remove not working accounts then not working accounts was pasted into notworking.txt but when i imported other 300 accounts and tried to commend it was fine also but when i selected remove not working accounts it just replaced into notworking.txt and removed old not working accounts. My english sucks..

**Comment by Andriuxas** [comment]
cuz i have like 8 txt files with accounts like 10k and there is alot of notworking accounts..

**Comment by Andriuxas** [comment]
When i commended my self from first .txt and then i clicked remove not working accounts there was in that txt 50 not working accounts yah. But when i commended with other txt file and i clicked remove not working accounts there was 20+ not working accounts bullshiet. It removes old not working accounts.

**Comment by Andriuxas** [comment]
Thats just example that i wrote..

**Comment by BeepIsla** [comment]
Just import all text files at once and then commend yourself. Removing non-operational accounts is useless. It does nothing useful for you in this case.

**Comment by Andriuxas** [comment]
Okay

**Comment by Andriuxas** [comment]
so when i commend like per day 2k yah?

**Comment by Andriuxas** [comment]
Also i have my own commend service. Alot of members.

**Comment by Andriuxas** [comment]
And there is alot of not working accounts like 40% of my accounts

**Comment by BeepIsla** [comment]
Doesn't matter, accounts marked as non-operational will never be used again unless you modify it. They are simply ignored.

**Comment by Andriuxas** [comment]
Okay thanks

**Comment by Andriuxas** [comment]
So if i reset database it wont remove commend history? It wont commend with same accounts same person?

**Comment by Andriuxas** [comment]
????????????????????

**Comment by BeepIsla** [comment]
If you reset the database everything is deleted, including commend history.

**Comment by Andriuxas** [comment]
There is nothing more commend history is important. Cuz i have tons of not working accounts. And i will check with bruteforcer not working accounts.

**Comment by Andriuxas** [comment]
So it wont commend still with the same accounts that has been already commended?

**Comment by BeepIsla** [comment]
If you remove an account commend history for that account is deleted, if you reset your database commend history for all accounts are deleted.

Without commend history it will re-use old accounts.

**Comment by Andriuxas** [comment]
Shiet
