### ISSUE TITLE
I get an "Failed to commend" error

### ISSUE THREAD

**Issue by noman00000** [BeepIsla/csgo-commend-bot#398]
hi some one help me cmd bot working for 12 hour and Suddenly show all accounts failed to commend 
what can i do ?????

**Comment by noman00000** [comment]
[16wddF7txTFK] Failed to commend (3/11) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\World\\Desktop\\CAC\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:531:17)\n' +
    '    at processTimers (internal/timers.js:475:7)'
}
 [3bMKV5tvgHow] Failed to commend (4/11) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\World\\Desktop\\CAC\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:531:17)\n' +
    '    at processTimers (internal/timers.js:475:7)'
}
 [1TGvrHN5TZon] Failed to commend (5/11) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\World\\Desktop\\CAC\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:531:17)\n' +
    '    at processTimers (internal/timers.js:475:7)'
this is

**Comment by noman00000** [comment]
i want to test rep bot it failed to after that cmd bot not working

**Comment by BeepIsla** [comment]
What server

**Comment by noman00000** [comment]
deathmach 
i fix it :/ with delete all thing
