### ISSUE TITLE
Error: Cannot find module 'inquirer'

### ISSUE THREAD

**Issue by malik7420** [BeepIsla/csgo-commend-bot#399]
**Detailed question description**
I am facing this Error: Cannot find module 'inquirer',
Can you please guide how can I fix this error,

**Version**
- NodeJS: `v6.10.2` 
- Script version: `v2.7.1`

**Comment by BeepIsla** [comment]
Did you follow the README and do `npm install`?

**Comment by malik7420** [comment]
yap I already install v6.10.2

**Comment by BeepIsla** [comment]
1. Update NodeJS, v6 is **old**. Install v12

2. `npm install` is a command you need to enter in a command prompt

**Comment by malik7420** [comment]
bro I was trying to install npm but facing this error
![Screenshot_151](https://user-images.githubusercontent.com/64732517/80921304-0a3f9400-8d8f-11ea-99fc-0712413187ed.png)

**Comment by BeepIsla** [comment]
There is no error here. Warnings are irrelevant.

**Comment by malik7420** [comment]
thank you bro problem solve all thank you so much for help
