### ISSUE TITLE
commend "timeout"

### ISSUE THREAD

**Issue by xiaowuap** [BeepIsla/csgo-commend-bot#402]
**Detailed bug description**
using that will see a timeout
**Error**
```
A full error log or screenshot.
```
![image](https://user-images.githubusercontent.com/44547885/80985404-c4073500-8e61-11ea-897e-6b836c28cadd.png)

**Config**
```{
	"commend": {
		"friendly": 20,
		"teaching": 20,
		"leader": 20
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "xxxxx",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"steamWebAPIKey": "xxxxxxx",
	"disableUpdateCheck": false
}

Your "config.json" - Censor your API Key and account details
```

**Version**
- NodeJS: `v12.9.1` (You can find this using `node -v`)
- Script version: `2.7.1` (You can find this in **your** `package.json` file under `version`)

**Additional information**
Add any other potentially useful information about your issue here.

**Comment by BeepIsla** [comment]
What server are you using? Valve Competitive? Wingman? Casual? Community?

**Comment by xiaowuap** [comment]
im using valve casual deathmatch

**Comment by xiaowuap** [comment]
valve casual

**Comment by xiaowuap** [comment]
im using valve casual

**Comment by BeepIsla** [comment]
I don't know why this happens
