### ISSUE TITLE
Idk

### ISSUE THREAD

**Issue by xyzzv** [BeepIsla/csgo-commend-bot#403]
Error: Cannot find module 'C:\Users\Win10User\Desktop\zarabianie\csgo-commend-bot\index.json'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:677:27)[39m
[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)[39m
[90m    at internal/main/run_main_module.js:17:11[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []

**Comment by BeepIsla** [comment]
`index.json` does not exist. It is `index.js`.
