### ISSUE TITLE
??

### ISSUE THREAD

**Issue by xyzzv** [BeepIsla/csgo-commend-bot#404]
(node:5612) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'k_EMsgClientAuthList' of undefined
    at C:\Users\Win10User\Desktop\pochwały\csgo-commend-bot\helpers\account.js:257:37
(node:5612) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
 [dsadsadsadsas] Logged onto Steam - GC Time: 2020-5-5 13:41:30
 [dsfdfsdsfdsfdsfd] Logged onto Steam - GC Time: 2020-5-5 13:41:30
(node:5612) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'k_EMsgClientAuthList' of undefined
    at C:\Users\Win10User\Desktop\pochwały\csgo-commend-bot\helpers\account.js:257:37
(node:5612) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
(node:5612) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'k_EMsgClientAuthList' of undefined
    at C:\Users\Win10User\Desktop\pochwały\csgo-commend-bot\helpers\account.js:257:37
(node:5612) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)

**Comment by BeepIsla** [comment]
Delete your `protobufs` folder and retry.

**Comment by xyzzv** [comment]
Failed to find protobufs, downloading and extracting...
Error: connect ECONNREFUSED 127.0.0.1:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 443
} Promise {
  <rejected> Error: connect ECONNREFUSED 127.0.0.1:443
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14) {
    errno: 'ECONNREFUSED',
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 443
  }

**Comment by BeepIsla** [comment]
Something is blocking you from downloading the required protobufs. You have 2 options:

1. Figure out what is causing the problem and fix it. I assume its something in your `hosts` file redirecting `github.com` to `127.0.0.1`, find the problem and fix it yourself.

2. Manually download [the protobufs](https://github.com/SteamDatabase/Protobufs/archive/master.zip) and extract them so the folder structure looks like this:
    - `csgo-commend-bot/protobufs`
        - `csgo-commend-bot/protobufs/csgo`
        - `csgo-commend-bot/protobufs/steam`
        - etc...

**Comment by xyzzv** [comment]
I can't download protobufs

**Comment by BeepIsla** [comment]
Sorry, I can't help you. Something on your system or connection is blocking connection, maybe a firewall, anti virus or something else.

**Comment by xyzzv** [comment]
how can i solve this problem with hosts?

**Comment by BeepIsla** [comment]
[Google...](https://www.wikihow.com/Edit-the-Hosts-File-on-Windows) Find something with "Github" inside of it and remove it. 

This is just a theory I **do not know** what the problem is.

**Comment by xyzzv** [comment]
this problem is not caused by the hosts, is there any other reason?

**Comment by BeepIsla** [comment]
I don't know.

**Comment by xyzzv** [comment]
shit...

**Comment by xyzzv** [comment]
pls help me....

**Comment by BeepIsla** [comment]
I can't help you.
