### ISSUE TITLE
TypeError: Cannot read property 'k_EMsgClientAuthList' of undefined

### ISSUE THREAD

**Issue by Razy-DE** [BeepIsla/csgo-commend-bot#406]
**Detailed bug description**
I am getting this error after it logs into the bot accounts.

**Error**
 Checking for new update...
 Up to date!
 Checking protobufs...
 Found protobufs
 Opening database...
 There are a total of 2 operational accounts
 Parsing target account...
 Chunking 2 accounts into groups of 2...
 Logging in on chunk 1/1
 [censored] Logging into Steam
 [censored] Logging into Steam
 [censored] Logged onto Steam - GC Time: 5/6/2020, 2:16:00 PM
(node:3120) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'k_EMsgClientAuthList' of undefined
    at /home/csgocommend/helpers/account.js:257:37
(node:3120) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3120) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 [censored] Logged onto Steam - GC Time: 5/6/2020, 2:16:04 PM
(node:3120) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'k_EMsgClientAuthList' of undefined
    at /home/csgocommend/helpers/account.js:257:37
(node:3120) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

**Config**
{
	"commend": {
		"friendly": 2,
		"teaching": 2,
		"leader": 2
	},
	"report": {
		"aimbot": 10,
		"wallhack": 10,
		"speedhack": 10,
		"teamharm": 10,
		"abusive": 10
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "censored",
	"perChunk": 2,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"steamWebAPIKey": "censored",
	"disableUpdateCheck": false
}

**Version**
- NodeJS: `v12.9.1` (You can find this using `node -v`)
- Script version: `2.7.1` (You can find this in **your** `package.json` file under `version`)

**Comment by BeepIsla** [comment]
Delete your protobufs folder and try again

**Comment by Razy-DE** [comment]
worked thanks
