### ISSUE TITLE
Error at manage commendbot

### ISSUE THREAD

**Issue by AndreYus112** [BeepIsla/csgo-commend-bot#407]
**Detailed bug description**

**Error**
```
https://imgur.com/a/CsRh3te
```

**Config**
```
Your "config.json" - Censor your API Key and account details
```

**Version**
- NodeJS: `vXX.XX.X` (You can find this using `node -v`)
- Script version: `X.X.X` (You can find this in **your** `package.json` file under `version`)

**Additional information**
Add any other potentially useful information about your issue here.

**Comment by BeepIsla** [comment]
You have a form in-front of you and you decide to not fill it out at all.

Regardless, as per README:

> # Requirements
> 
> - [NodeJS v12](https://nodejs.org/)

You have v13, uninstall it.

**Comment by AndreYus112** [comment]
and a another problem look what it says?https://imgur.com/a/foElLh7

**Comment by BeepIsla** [comment]
None of this is an error
