### ISSUE TITLE
error" falied to send massage: time out

### ISSUE THREAD

**Issue by langyichen** [BeepIsla/csgo-commend-bot#412]
Checking for new update...
 Up to date!
 Checking protobufs...
 Found protobufs
 Opening database...
 There are a total of 15 operational accounts
 Parsing target account...
 Chunking 10 accounts into groups of 20...
 Logging in on chunk 1/1
 [abbitsf177vogel] Logging into Steam
 [accoondogj76353766bou] Logging into Steam
 [aglee443631970paolini] Logging into Steam
 [atj0vanderhulst153] Logging into Steam
 [fricanbuffalov2edward] Logging into Steam
 [heav5oliva69599704] Logging into Steam
 [igeonl0mele75234620] Logging into Steam
 [ionv8jarvis6] Logging into Steam
 [itb10desimone116] Logging into Steam
 [luefishn351072271lecl] Logging into Steam
 [fricanbuffalov2edward] Logged onto Steam - GC Time: 2020-5-8 0:22:43
 [fricanbuffalov2edward] Authenticated to anonymous server with ticket 508696398
 [abbitsf177vogel] Logged onto Steam - GC Time: 2020-5-8 0:22:48
 [luefishn351072271lecl] Logged onto Steam - GC Time: 2020-5-8 0:22:48
 [heav5oliva69599704] Logged onto Steam - GC Time: 2020-5-8 0:22:48
 [atj0vanderhulst153] Logged onto Steam - GC Time: 2020-5-8 0:22:49
 [itb10desimone116] Logged onto Steam - GC Time: 2020-5-8 0:22:48
 [accoondogj76353766bou] Logged onto Steam - GC Time: 2020-5-8 0:22:48
 [igeonl0mele75234620] Logged onto Steam - GC Time: 2020-5-8 0:22:48
 [abbitsf177vogel] Authenticated to anonymous server with ticket 3517729755
 [aglee443631970paolini] Logged onto Steam - GC Time: 2020-5-8 0:22:48
 [luefishn351072271lecl] Authenticated to anonymous server with ticket 2412082919
 [heav5oliva69599704] Authenticated to anonymous server with ticket 216394926
 [accoondogj76353766bou] Authenticated to anonymous server with ticket 4101505178
 [atj0vanderhulst153] Authenticated to anonymous server with ticket 980760737
 [ionv8jarvis6] Logged onto Steam - GC Time: 2020-5-8 0:22:49
 [itb10desimone116] Authenticated to anonymous server with ticket 4107596012
 [aglee443631970paolini] Authenticated to anonymous server with ticket 389119045
 [igeonl0mele75234620] Authenticated to anonymous server with ticket 3381825102
 [ionv8jarvis6] Authenticated to anonymous server with ticket 1161577779
 [fricanbuffalov2edward] Failed to commend (1/10) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\langy\\Desktop\\lll\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
}
 [abbitsf177vogel] Failed to commend (2/10) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\langy\\Desktop\\lll\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
}
 [luefishn351072271lecl] Failed to commend (3/10) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\langy\\Desktop\\lll\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
}
 [heav5oliva69599704] Failed to commend (4/10) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\langy\\Desktop\\lll\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
}
 [accoondogj76353766bou] Failed to commend (5/10) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\langy\\Desktop\\lll\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
}
 [atj0vanderhulst153] Failed to commend (6/10) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\langy\\Desktop\\lll\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
}
 [itb10desimone116] Failed to commend (7/10) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\langy\\Desktop\\lll\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
}
 [aglee443631970paolini] Failed to commend (8/10) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\langy\\Desktop\\lll\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
}
 [igeonl0mele75234620] Failed to commend (9/10) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\langy\\Desktop\\lll\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
}
 [ionv8jarvis6] Failed to commend (10/10) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\langy\\Desktop\\lll\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
}
 Chunk 1/1 finished with 0 successful commends and 10 failed commends
 Finished all chunks with a total of 0 successful and 10 failed commends

**Comment by langyichen** [comment]
calling superman!

**Comment by BeepIsla** [comment]
What server are you trying to commend on? What is your config? Many open questions.

**Comment by langyichen** [comment]
I tryed deathmatch and casual. config : type commend method sever.  I just adjusted the url and apikey to my own one .

**Comment by BeepIsla** [comment]
I don't know why this happens.

**Comment by langyichen** [comment]
the bots have successfully logged in, but failed to send messages.

**Comment by BeepIsla** [comment]
I can see this, I am stupid. I told you everything I know. Just try different accounts.

**Comment by omidonrails** [comment]
i have same problem after csgo update please help!
