### ISSUE TITLE
HELPE "Error: SQLITE_ERROR: near "qf": syntax error"

### ISSUE THREAD

**Issue by Falghere** [BeepIsla/csgo-commend-bot#414]
**Detailed question description**
![image](https://user-images.githubusercontent.com/16209066/81425045-3c554b00-912d-11ea-83f8-04f576c4da46.png)

I'm trying to add the accounts to the database, but it doesn't work, what did I do wrong?

**Config**
![image](https://user-images.githubusercontent.com/16209066/81424775-da94e100-912c-11ea-8e28-1388eeaf373b.png)

**Version**
- NodeJS: `v12.16.3` (You can find this using `node -v`)
- Script version: `2.7.1` (You can find this in **your** `package.json` file under `version`)

**Comment by BeepIsla** [comment]
Does any of your account's passwords have a quotation mark `"` or special characters as password such as `!§$%&/()=?'*#~` or others?

**Comment by Falghere** [comment]
Yes, most passwords are generated randomly from google

**Comment by Falghere** [comment]
Is there no way to make them read these characters? because I will lose a lot of account (impossible to change the password of all)

**Comment by BeepIsla** [comment]
I will try and figure out a way, maybe not today but I'll come back to this tomorrow.

**Comment by Falghere** [comment]
ok thx alot <3

**Comment by BeepIsla** [comment]
I've made some changes (bc196eae3231b3a36752fe1bce7a53a76b12f207), please re-download and try again. It should properly work now, hopefully.
