### ISSUE TITLE
I can send commends

### ISSUE THREAD

**Issue by Noxw0w** [BeepIsla/csgo-commend-bot#415]
**Detailed bug description**

**Error**
```
A full error log or screenshot.
https://imgur.com/a/eCVLcW2
**Config**
```
Your "config.json" - Censor your API Key and account details
```

**Version**
- NodeJS: `vXX.XX.X` (You can find this using `node -v`)
- Script version: `X.X.X` (You can find this in **your** `package.json` file under `version`)

**Additional information**
Add any other potentially useful information about your issue here.

**Comment by BeepIsla** [comment]
You have a template but don't fill it out?

What is your config?

**Comment by Noxw0w** [comment]
{
  "commend": {
    "friendly": 20,
    "teaching": 20,
    "leader": 20
  },
  "report": {
    "aimbot": 10,
    "wallhack": 10,
    "speedhack": 10,
    "teamharm": 10,
    "abusive": 10
  },
  "account": {
    "username": "",
    "password": "",
    "sharedSecret": ""
  },
  "proxy": {
    "enabled": false,
    "file": "proxies.txt",
    "switchProxyEveryXaccounts": 20
  },
  "type": "COMMEND",
  "method": "SERVER",
  "target": "https://steamcommunity.com/id/noxw0w1947",
  "perChunk": 20,
  "betweenChunks": 300000,
  "cooldown": 28800000,
  "disableUpdateCheck": false
}

**Comment by BeepIsla** [comment]
Do you have a `steamWebAPIKey` in your config?

**Comment by Noxw0w** [comment]
no, i delete him for 2 days and work without steamwebapikey and now it s a bug but i don t know why

**Comment by BeepIsla** [comment]
That's not a bug. Without an API key it can't figure out who `noxw0w1947` is. It works if you use the SteamID but not with the custom URL.
