### ISSUE TITLE
ReportBot Again PAtched 09.05.2020

### ISSUE THREAD

**Issue by amx22** [BeepIsla/csgo-commend-bot#418]
Report/Commend bot again Patched...
does not work anymore and seems to not work for a long time

nice Valve wtf. RIP....

**Comment by crx9** [comment]
Commend bot worked but report can't work(i can't report in casual/deathmatch now,in game, i don't know why)

**Comment by amx22** [comment]
i tested commend and reportbot doesnt work.. u wrong commend doesnt work.

because patched. so it doesn't work.

**Comment by crx9** [comment]
> i tested commend and reportbot doesnt work.. u wrong commend doesnt work.
> 
> because patched. so it doesn't work.

I just used commend bot, I can get commendation,but report doesn't work

**Comment by amx22** [comment]
yes you are right i guess i tried now comment report is working, but Reportbot doesnt work timeout .. very interesting I think it blocked the valve server method,

**Comment by amx22** [comment]
If we remove the server number and report it only to the match number and profile number after the match, the problem will be fixed.... ??  i think valve patched server number method...!

**Comment by crx9** [comment]
Now u can't get report response code in casual&deathmatch&after competitive/wingman on scorecard today.

**Comment by amx22** [comment]
yes unfortunately, reportbot no longer reports successfully,

**Comment by amx22** [comment]
Report Bot Doesnt Work Because Valve Fixed > reportbot .. logic and method..If you report from your own account, you can not see the report is gone in the game in green text below.
I think reporting system logic has changed completely VALVE.

**Comment by amx22** [comment]
> Commend bot worked but report can't work(i can't report in casual/deathmatch now,in game, i don't know why)

yes because Valve reporting system removed > casual/deatmatch ...

**Comment by despa1r1337** [comment]
the reporting system is disabled in the game itself :/ if you try to report, you will not see a successful report message.

**Comment by amx22** [comment]
> the reporting system is disabled in the game itself :/ if you try to report, you will not see a successful report message.
> 
> In console:
> 
> ```
> Don't yet support elliptical arc  rendering
> Don't yet support elliptical arc  rendering
> Don't yet support elliptical arc  rendering
> Don't yet support elliptical arc  rendering
> ```

no competitive server normal report done own account i tested. but deathmatc/casual servers removed report system...

**Comment by BeepIsla** [comment]
Move to #428
