### ISSUE TITLE
Dear BeepIsla

### ISSUE THREAD

**Issue by Raxana7** [BeepIsla/csgo-commend-bot#421]
![image](https://user-images.githubusercontent.com/48220802/81496260-237c9f00-92bf-11ea-8fa9-5137918a00c7.png)

Can you explain in detail why this error is caused?
I'm asking this question because I have to show someone your answer as evidence.

**Comment by BeepIsla** [comment]
As per [SteamErrors.com](https://steamerrors.com/), response code `2` simply means `Generic failure`.

In commending context and based on testing done far before Valve fixed any commend bot related things this means `Already commended`. Its surely possibly this has changed over the years but I never had this error happen myself except when the target was already commended.

So I assume everything is still the same:
- `1`: Success
- `2`: Already commended
- *No response*: Something went wrong
