### ISSUE TITLE
databasemanager.js

### ISSUE THREAD

**Issue by BySivasli** [BeepIsla/csgo-commend-bot#422]
(node:9280) UnhandledPromiseRejectionWarning: TypeError: chunk.map(...).flat is not a function
    at askInput (C:\Users\Canberk\Desktop\csgo-commend-bot-master\databaseManager.js:215:222)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:9280) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9280) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by BeepIsla** [comment]
As per README:

> # REQUIREMENTS
> - [NodeJS v12](https://nodejs.org/)
