### ISSUE TITLE
help pls

### ISSUE THREAD

**Issue by xyzzv** [BeepIsla/csgo-commend-bot#426]
[yJQg1WBioo1G] Failed to commend (12/15) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\Win10User\\Desktop\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:531:17)\n' +
    '    at processTimers (internal/timers.js:475:7)'

**Comment by Xedoo** [comment]
Same to me.

**Comment by Xedoo** [comment]
On every account, i tried proxy, vpn, same error, i tried to add commend on different accounts, same problem, and the accounts for commend all new...

**Comment by BeepIsla** [comment]
Config? What server are you using?

**Comment by Xedoo** [comment]
> 
> 
> Config? What server are you using?

My config is standard now without proxies, 3 days worked, tonight stoped working. I used only in deathmatch official servers. I tried on comunity server but didnt work. So on 3 accounts worked only in deathmatch official.

**Comment by crx9** [comment]
only can commend 3 times every 5 minutes

**Comment by crx9** [comment]
> Config? What server are you using?
only can commend 3 times every 5 minutes

**Comment by crx9** [comment]
> Config? What server are you using?

only can commend 3 times every 5 minutes

**Comment by BeepIsla** [comment]
3 times per 24 hours, not 5 minutes.

**Comment by crx9** [comment]
> 3 times per 24 hours, not 5 minutes.

can u fix ?

**Comment by BeepIsla** [comment]
No
