### ISSUE TITLE
Timeout?

### ISSUE THREAD

**Issue by Noxw0w** [BeepIsla/csgo-commend-bot#429]
**Detailed bug description**

**Error**
```
https://imgur.com/a/KTSsO1O
```

**Config**
```
Your "config.json" - Censor your API Key and account details
```

**Version**
- NodeJS: `vXX.XX.X` (You can find this using `node -v`)
- Script version: `X.X.X` (You can find this in **your** `package.json` file under `version`)

**Additional information**
Add any other potentially useful information about your issue here.

**Comment by BeepIsla** [comment]
Look through already existing issues prior to creating a new one. Duplicate #428.
