### ISSUE TITLE
Why i have that error?

### ISSUE THREAD

**Issue by MrDumox** [BeepIsla/csgo-commend-bot#430]
![image](https://user-images.githubusercontent.com/57267520/81842682-b54d0c00-954c-11ea-8012-033af0180c88.png)

What i must do to repair that

**Comment by boostacc** [comment]
Before you write, and make pictures. Have YOU tried reading the last huge post?

**Comment by MrDumox** [comment]
yea

**Comment by MrDumox** [comment]
nothing work

**Comment by boostacc** [comment]
Wow, Did you read it?I doubt it if you post this sh*t

**Comment by MrDumox** [comment]
why do I trace time for such children?

**Comment by boostacc** [comment]
you are a selfish child who can't read at least the coder response before scribbling your tearful post "Oh mom, the program doesn't work, help me"

This is free software and you have to kiss the coder's heels for his work, instead, you waste his time

**Comment by bg1337** [comment]
Dumox lil kid...please read here..

https://github.com/BeepIsla/csgo-commend-bot/issues/428

**Comment by MrDumox** [comment]
🤣🤣🤣

**Comment by MrDumox** [comment]
ok, sry
