### ISSUE TITLE
TypeError: Cannot read property 'k_EMsgGCClientHello' of undefined

### ISSUE THREAD

**Issue by simplehard** [BeepIsla/csgo-commend-bot#432]
help me pls.

**Comment by BeepIsla** [comment]
I already told you want to do [here](https://github.com/BeepIsla/csgo-commend-bot/issues/431#issuecomment-628408277).

**Comment by simplehard** [comment]
i have tried this, it continues with the same error.

**Comment by BeepIsla** [comment]
Did you delete the entire `protobufs` folder? Including the content and the folder it self?

If that doesn't work download [this](https://github.com/SteamDatabase/Protobufs) and extract it into your folder, so the structure looks like this:

- `csgo-commend-bot`
  - `config.json`
  - `index.js`
  - [...]
  - `protobufs`
    - `csgo`
    - `steam`
    - [...]

**Comment by simplehard** [comment]
got it. i was using version 12.16.3 of the node.
but now, i have another problem:

 [0hqj3ry39] Failed to commend (20/20) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\Matheus Henriques\\Documents\\Coding\\Outros\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:531:17)\n' +
    '    at processTimers (internal/timers.js:475:7)'

///

Chunk 1/25 finished with 15 successful commends and 5 failed commends
5 errors.

**Comment by BeepIsla** [comment]
And now read this #428
