### ISSUE TITLE
Failed to send message: Timeout

### ISSUE THREAD

**Issue by 9mkkM65l5jp3** [BeepIsla/csgo-commend-bot#440]
Error photo: https://i.imgur.com/vFC9jAU.png
NodeJS Version: node-v12.9.1-x64
Version BOT: 2.7.1
config.json photo: https://i.imgur.com/k6oo9Yc.png

THE ACCOUNT HAVE STEAM GUARD DISABLED.

**Comment by puuska** [comment]
#428
