### ISSUE TITLE
Little question of a stuff

### ISSUE THREAD

**Issue by lightbgs** [BeepIsla/csgo-commend-bot#441]
![image](https://user-images.githubusercontent.com/31590513/82353210-7cda8180-99d5-11ea-9e1f-60001f6c61aa.png)
Is there a way of providing steamGuard at config.json? i tried some stuffs, but i'm getting some errors...

**Comment by lightbgs** [comment]
![image](https://user-images.githubusercontent.com/31590513/82353363-b90de200-99d5-11ea-9698-513afb4e5ed5.png)
i know that the login info is parsed here:

**Comment by BeepIsla** [comment]
Root your phone and get the `sharedSecret` out of the Steam Guard App, then put it in the config.

**Comment by lightbgs** [comment]
> Root your phone and get the `sharedSecret` out of the Steam Guard App, then put it in the config.

isn't a way of providing the code during the script? with a variable?

**Comment by BeepIsla** [comment]
There is no way to do this, if you edit the code and create a script to automatically fill in your Steam Guard code maybe. Biggest problem is the Steam Guard Code changes every 30 seconds.

**Comment by lightbgs** [comment]
> There is no way to do this, if you edit the code and create a script to automatically fill in your Steam Guard code maybe. Biggest problem is the Steam Guard Code changes every 30 seconds.

i'm trying to automatize this login process by a discord bot... steam guard changes does not affect my wanting... i just want to provide it to your script using a variable.

**Comment by BeepIsla** [comment]
Aside from editing the code it self or providing a Shared Secret there is no way to provide a Steam Guard Code.

**Comment by lightbgs** [comment]
since you're using steam-user module, if i provide authcode, do you think it will work?
ps.: thanks for fast answer, and sorry for wasting ur time :S

![image](https://user-images.githubusercontent.com/31590513/82354767-a4cae480-99d7-11ea-9907-a79f27538af2.png)

**Comment by lightbgs** [comment]
As you are using steam-user module to login, I will try to talk at their issues, ty anyway, if you have any idea how to provide it to steam-user pls tell me, then I can test it...

**Comment by BeepIsla** [comment]
What you linked [here](https://github.com/BeepIsla/csgo-commend-bot/issues/441#issuecomment-630938713) is literally where the Steam Guard Code gets put in, `twoFactorCode` **is** the Steam Guard Code.

**Comment by lightbgs** [comment]
> What you linked [here](https://github.com/BeepIsla/csgo-commend-bot/issues/441#issuecomment-630938713) is literally where the Steam Guard Code gets put in, `twoFactorCode` **is** the Steam Guard Code.

ohh, okay, it worked xD, thanks
