### ISSUE TITLE
HTTP Proxies

### ISSUE THREAD

**Issue by cassiompf** [BeepIsla/csgo-commend-bot#442]
I want to know: 
What configuration of proxies should I use to work correctly?
What level of security does it need to work? 
Does it need to be classified as: Elite, Anonymous or Transparent? Does it need SSL? 
Does the proxy port necessarily have to be 80?

**Config**
```
{
	"commend": {
		"friendly": 21,
		"teaching": 21,
		"leader": 21
	},
	"report": {
		"aimbot": 10,
		"wallhack": 10,
		"speedhack": 10,
		"teamharm": 10,
		"abusive": 10
	},
	"account": {
		"username": ""****",
		"password": ""****",
		"sharedSecret": "****"
	},
	"proxy": {
		"enabled": true,
		"file": "http_proxies.txt",
		"switchProxyEveryXaccounts": 1
	},
	"type": "COMMEND",
	"method": "LOGIN",
	"target": "http://steamcommunity.com/profiles/*******",
	"perChunk": 20,
	"betweenChunks": 2000,
	"cooldown": 5000,
	"steamWebAPIKey": "******",
	"disableUpdateCheck": false
}
```

**Version**
- NodeJS: `v12.9.1` 
- Script version: `2.7.1`

**Comment by BeepIsla** [comment]
Any HTTP proxy not blocked by Steam.

A proxy may work on store.steampowered.com or steamcommunity.com but that **does not** mean it works for logging in. Logins have stricter proxy restrictions.

**Comment by cassiompf** [comment]
do you have any proxy list that works to send me?

**Comment by BeepIsla** [comment]
No
