### ISSUE TITLE
I have this error. Error: Failed to send commend: Timeout at Timeout.setTimeout [as _onTimeout] (csgo-commend-bot-master\helpers\account.js:137:12) at ontimeout (timers.js:498:11) at tryOnTimeout (timers.js:323:5) at Timer.listOnTimeout (timers.js:290:5).  What should we do?

### ISSUE THREAD

**Issue by Musa31** [BeepIsla/csgo-commend-bot#443]
**Detailed bug description**

**Error**
```
A full error log or screenshot.
```

**Config**
```
Your "config.json" - Censor your API Key and account details
```

**Version**
- NodeJS: `vXX.XX.X` (You can find this using `node -v`)
- Script version: `X.X.X` (You can find this in **your** `package.json` file under `version`)

**Additional information**
Add any other potentially useful information about your issue here.

**Comment by CONBlaze** [comment]
There is a template for a reason my dude

**Comment by BeepIsla** [comment]
Duplicate #428

**Comment by Musa31** [comment]
Sorry i dint get how to resolve it.
