### ISSUE TITLE
Help please!

### ISSUE THREAD

**Issue by delfin420** [BeepIsla/csgo-commend-bot#444]
name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\Marcin\\Desktop\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:531:17)\n' +
    '    at processTimers (internal/timers.js:475:7)'

**Comment by UnbreakCode** [comment]
Please do not create new issue tickets when there is already a ticket!

Please refer to: https://github.com/BeepIsla/csgo-commend-bot/issues/428

@BeepIsla **Close!**

**Comment by BeepIsla** [comment]
As mentioned: Duplicate
