### ISSUE TITLE
Not enough accounts available at this time

### ISSUE THREAD

**Issue by Sacred-Lotus** [BeepIsla/csgo-commend-bot#446]
Using the LOGIN method, enter steam guard code, then I get this error:
`node index.js
 Checking for new update... 
 Up to date! 
 Checking protobufs... 
 Found protobufs 
 Opening database... 
 There are a total of 15 operational accounts 
 Logging into target account... 
Steam Guard App Code: CODE
 Not enough accounts available at the current time, got 1/15`

**Comment by BeepIsla** [comment]
Accounts are on cooldown

**Comment by Sacred-Lotus** [comment]
Oh fair, got it working now, thank you :)
