### ISSUE TITLE
Time out everytime I start the bot

### ISSUE THREAD

**Issue by z1nnyo** [BeepIsla/csgo-commend-bot#447]
**Detailed bug description**
Details below.

**Error**
```
https://prnt.sc/sr3t3v
```

**Config**
```
{
	"commend": {
		"friendly": 200,
		"teaching": 200,
		"leader": 200
	},

	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "xaxa",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"steamWebAPIKey": "xaxa",
	"disableUpdateCheck": false
}

```

**Version**
- NodeJS: `v12.16.3`
- Script version: `2.7.1`

**Additional information**
I get no commends, everytime I get time out and sometimes, I get `RateLimitExceeded` or something like that, hope you can help me!

**Comment by BeepIsla** [comment]
Duplicate #428

**Comment by z1nnyo** [comment]
Not finding something that can help me, could you help me?
