### ISSUE TITLE
Error: GC connection timeout - Hello

### ISSUE THREAD

**Issue by ramboi234** [BeepIsla/csgo-commend-bot#450]
**Detailed bug description**
since steam update today, I always receive gc connection timeout
how to fix that?

**Error**
```
https://i.imgur.com/R7hJypi.png
```

**Config**
```
{
	"commend": {
		"friendly": 45,
		"teaching": 40,
		"leader": 45
	},
	"report": {
		"aimbot": 10,
		"wallhack": 10,
		"speedhack": 10,
		"teamharm": 10,
		"abusive": 10
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"fetcher": {
		"username": "XXX",
		"password": "XXX",
		"sharedSecret": "",
		"maxTries": 10,
		"tryDelay": 2500,
		"askSteamGuard": true
	},
	"proxy": {
		"enabled": true,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/id/XXX",
	"serverID": "auto",
	"matchID": "0",
	"perChunk": 20,
	"betweenChunks": 309000,
	"cooldown": 28800000,
	"switchServerAfterChunks": 5,
	"steamWebAPIKey": "XXXX",
	"disableUpdateCheck": false
}

```

**Version**
node version 12.18.0

**Additional information**
m

**Comment by BeepIsla** [comment]
Make sure you have CSGO closed.

**Comment by pu5h3r** [comment]
Why have you add fetcher ?

**Comment by BeepIsla** [comment]
Just try using a different account for fetcher.

**Comment by pu5h3r** [comment]
Does "timeout error" fixed?

**Comment by BeepIsla** [comment]
Timeout error is entirely unrelated, for help look at this #428 issue.

**Comment by ramboi234** [comment]
Is this only happend to me or to other too?

I already try
-close csgo and steam
-change steam account 10 times still timeout in row
-change Ip

still get <rejected> Error: GC connection timeout

**Comment by BeepIsla** [comment]
"GC connection timeout" means the bot failed to connect to the CSGO network but successfully logged into the account. The only times this happens is when [Steam is offline](https://steamstat.us/) or you already have CSGO running on another account.

That's all I know and all I can tell you.

**Comment by ramboi234** [comment]
thanks @BeepIsla  now work again, after I restart my computer

**Comment by pu5h3r** [comment]
I am getting 
Failed to decode Steam rich presence keyvalues
Failed to receive Valve csgo server information

**Comment by BeepIsla** [comment]
Then they are not on an accessible server. Just fill in ServerID manually, its not hard.

**Comment by pu5h3r** [comment]
This happened when it trying to fetch target.
And to enter server id manually i should be in csgo server from the id which i am trying to boost.,right?

**Comment by BeepIsla** [comment]
Yes, Server ID or Server IP
