### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by TrickyhubYT** [BeepIsla/csgo-commend-bot#451]
config.target = ${config.target}${process.argv[2]};

this is not a function and when i open it in visual studio it just comes with 

config.target = $;{config.target}$;{process.argv[2]};
this solution 

please help

**Comment by BeepIsla** [comment]
What does any of this mean?

What version are you using?

What are you trying to do?

What is the actual error you are getting ?

Did you modify the bot yourself?

**Comment by TrickyhubYT** [comment]
i am fixing like i have fixed one error then other one showed up it says {  response {}   }
in red and right after found target in server

**Comment by BeepIsla** [comment]
> { response {} }

Probably means the server could not be verified

**Comment by TrickyhubYT** [comment]
so what should i do?

**Comment by BeepIsla** [comment]
I don't know, try using a different server. Preferably a community server.

**Comment by TrickyhubYT** [comment]
trying

**Comment by TrickyhubYT** [comment]
did not worked

**Comment by BeepIsla** [comment]
Then I do not know
