### ISSUE TITLE
getaddrinfo ENOTFOUND wqx1eg

### ISSUE THREAD

**Issue by mikelobam** [BeepIsla/csgo-commend-bot#452]
why does this give error?
```
[31m [account] Failed to login and has been marked as invalid (10/10) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'wqx1eg',
  proxyConnecting: true,
  state: 1,
  name: 'Error',
  message: 'getaddrinfo ENOTFOUND wqx1eg',
  stack: 'Error: getaddrinfo ENOTFOUND wqx1eg\n' +
    '    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)'
}
```

**Comment by BeepIsla** [comment]
Config?

**Comment by mikelobam** [comment]
> Config?

`{
	"commend": {
		"friendly": 100,
		"teaching": 100,
		"leader": 100
	},
	"report": {
		"aimbot": 10,
		"wallhack": 10,
		"speedhack": 10,
		"teamharm": 10,
		"abusive": 10
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"fetcher": {
		"username": "Account",
		"password": "Password",
		"sharedSecret": "",
		"maxTries": 10,
		"tryDelay": 2500,
		"askSteamGuard": true
	},
	"proxy": {
		"enabled": true,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 10
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "xxxxxx",
	"serverID": "xxxxx",
	"matchID": "0",
	"perChunk": 10,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"switchServerAfterChunks": 999,
	"steamWebAPIKey": "xxxxx",
	"disableUpdateCheck": false
}
`

**Comment by BeepIsla** [comment]
`getaddrinfo ENOTFOUND` is a DNS error, I just assume your proxy is not properly working.

**Comment by mikelobam** [comment]
> `getaddrinfo ENOTFOUND` is a DNS error, I just assume your proxy is not properly working.

yes the problem originates from proxy, thank you for your interest.

**Comment by pu5h3r** [comment]
Is 31m means 31 million accounts😳

**Comment by BeepIsla** [comment]
No that's a color.

**Comment by pu5h3r** [comment]
Not getting the commends.
In the cmd and even in-game i am getting a message of commend received but its bot showing on profile,i mean the count is not increasing.
