### ISSUE TITLE
can u add a function show user's "tooltip_friendly,tooltip_leader,tooltip_teaching"

### ISSUE THREAD

**Issue by crx9** [BeepIsla/csgo-commend-bot#453]
i see owbot  has get rank and wins,i think it also can get commends,but i dont know how to write that code

https://raw.githubusercontent.com/SteamDatabase/GameTracking-CSGO/master/csgo/resource/csgo_english.txt

"tooltip_permissions_group"		"• <b>Steam Group:</b> {s:group}"
		
		"tooltip_friendly"				"Number of unique commendations received for being <b>Friendly</b>"
		"tooltip_leader"				"Number of unique commendations received for being a <b>Leader</b>"
		"tooltip_teaching"				"Number of unique commendations received for being a <b>Teacher</b>"

**Comment by crx9** [comment]
show this  before start commend.

**Comment by ixfit** [comment]
Beepisla does not work on this project anymore so any help requests will be denied, he wont change anything in the project u just gotta code it urself or find someone who can

**Comment by crx9** [comment]
It's solved.
let commendation=mmHello.commendation;
	console.log(commendation);
show this:
{ cmd_friendly: 18039, cmd_teaching: 18039, cmd_leader: 18040 }

**Comment by crx9** [comment]
but how to add it in cbot, I tried but faild..

**Comment by BeepIsla** [comment]
I currently focus on other more important things and I don't even know which version is currently being used as fix and how it needs to be configured.

**Comment by crimwind** [comment]
A begger is asking someone to help him free. Why not just learn English well before you ask stupid questions?

**Comment by cassiompf** [comment]
Estou usando a versão mais recente com o método "LOGIN" and it is currently working

**Comment by BeepIsla** [comment]
Added in 2.8.1 (d6b336989e02e346b88fe56b695d379bc2bd8afb)
