### ISSUE TITLE
Bots are timeouting

### ISSUE THREAD

**Issue by GlaubeKeinemDev** [BeepIsla/csgo-commend-bot#455]
Hey,

I want to start give me commends in csgo. I have a account list with 170 accounts importet my API Key is working my target Steam Account for the commends is working. When I start the Bot it is succesful logging in into Steam accounts and it tells "Authenticated to anonymous server with ticket xxxxx". After that and a little bit time it says "Failed to send message: Timeout", GameCoordinator.js:124:12.

`{
	"commend": {
		"friendly": 50,
		"teaching": 50,
		"leader": 50
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/id/luchsencsgo",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"steamWebAPIKey": "BBC6B293077C1090E0CABE7CAEBF4440",
	"disableUpdateCheck": false
}`

That is my config.json

**Comment by BeepIsla** [comment]
Delete your API key and generate a new one. You just leaked it to everyone viewing this

This is a duplicate, read the pinned issue (#428)
