### ISSUE TITLE
Steam guard entered but commend failed.

### ISSUE THREAD

**Issue by Avi-141** [BeepIsla/csgo-commend-bot#456]
**Chunking 1 account into groups of 20...
 Successfully authenticated to anonymous server with ticket 1729979270
 Logging in on chunk 1/1
 [Accname] Logging into Steam**

**Requires a Steam Guard code and has been marked as invalid (1/1) {
  name: 'Error',
  message: 'Steam Guard required',
  stack: 'Error: Steam Guard required\n' +**
    '    at SteamUser.steamGuard (D:\\csgo-commend-bot\\helpers\\account.js:180:12)\n' +
    '    at SteamUser.emit (events.js:209:13)\n' +
    '    at SteamUser._steamGuardPrompt (D:\\csgo-commend-bot\\node_modules\\steam-user\\components\\logon.js:570:8)\n' +
    '    at SteamUser.<anonymous> (D:\\csgo-commend-bot\\node_modules\\steam-user\\components\\logon.js:432:9)\n' +
    '    at D:\\csgo-commend-bot\\node_modules\\steam-user\\components\\classes\\HandlerManager.js:37:12\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at HandlerManager.emit (D:\\csgo-commend-bot\\node_modules\\steam-user\\components\\classes\\HandlerManager.js:36:12)\n' +
    '    at SteamUser._handleMessage (D:\\csgo-commend-bot\\node_modules\\steam-user\\components\\messages.js:545:24)\n' +
    '    at SteamUser.Coordinator.steamUser._handleMessage (D:\\csgo-commend-bot\\helpers\\GameCoordinator.js:43:19)\n' +
    '    at SteamUser._handleNetMessage (D:\\csgo-commend-bot\\node_modules\\steam-user\\components\\messages.js:480:7)'
}
 **Chunk 1/1 finished with 0 successful commends and 1 failed commend
 Finished all chunks with a total of 0 successful and 1 failed commend**

**Comment by BeepIsla** [comment]
You can only enter a Steam Guard code for your target account in LOGIN method. You cannot enter a Steam Guard code for bot accounts.

**Comment by Avi-141** [comment]
I did enter steam guard for my target account.
Can you guide me further?

**Comment by BeepIsla** [comment]
Read the error and when it happens, then read what I wrote.

The error is related to your bot account having Steam Guard enabled not your target account.

**Comment by Avi-141** [comment]
Ok i realised. But valve isnt allowing me to get an API key. I have CSGO as 1 game, but it says 
"You will be granted access to Steam Web API keys when you have games in your Steam account."

**Comment by BeepIsla** [comment]
Free games do not count

**Comment by Avi-141** [comment]
I used an API key mentioned in one of the issues opened , since you said any API key would work. 
Now i have timeout issues ( which is an issue faced by people before as well, but i cant get my head around it).
Thanks

**Comment by BeepIsla** [comment]
For possible timeout solutions look through here #428
