### ISSUE TITLE
Bot work on server method ?

### ISSUE THREAD

**Issue by lagger1111** [BeepIsla/csgo-commend-bot#457]
**Detailed question description**
A clear and concise description of your question.

**Config**
```
Your "config.json" - Censor your API Key and account details
```

**Version**
- NodeJS: `vXX.XX.X` (You can find this using `node -v`)
- Script version: `X.X.X` (You can find this in **your** `package.json` file under `version`)

**Comment by BeepIsla** [comment]
Try it out. Anything else regarding the bot not working is likely related to #428
