### ISSUE TITLE
Proxy Type

### ISSUE THREAD

**Issue by SpaceR3** [BeepIsla/csgo-commend-bot#460]
Hello, so I bought HQ proxies which I used to generate steam accounts. I have them in 2 formats 1: http://username:password@server:port and server:port:username:password Wich format I have to use? When I tried the first one i just got 403 FORBIDDEN. Steam does not block the login with the proxy since I checked it manually

**Comment by SpaceR3** [comment]
http://Username:Paswsord@gw.rainproxy.io:5959

Looks like this

**Comment by BeepIsla** [comment]
As per [NodeJS Documentation](https://nodejs.org/api/url.html#url_url_strings_and_url_objects):

    ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
    │                                              href                                              │
    ├──────────┬──┬─────────────────────┬────────────────────────┬───────────────────────────┬───────┤
    │ protocol │  │        auth         │          host          │           path            │ hash  │
    │          │  │                     ├─────────────────┬──────┼──────────┬────────────────┤       │
    │          │  │                     │    hostname     │ port │ pathname │     search     │       │
    │          │  │                     │                 │      │          ├─┬──────────────┤       │
    │          │  │                     │                 │      │          │ │    query     │       │
    "  https:   //    user   :   pass   @ sub.example.com : 8080   /p/a/t/h  ?  query=string   #hash "
    │          │  │          │          │    hostname     │ port │          │                │       │
    │          │  │          │          ├─────────────────┴──────┤          │                │       │
    │ protocol │  │ username │ password │          host          │          │                │       │
    ├──────────┴──┼──────────┴──────────┼────────────────────────┤          │                │       │
    │   origin    │                     │         origin         │ pathname │     search     │ hash  │
    ├─────────────┴─────────────────────┴────────────────────────┴──────────┴────────────────┴───────┤
    │                                              href                                              │
    └────────────────────────────────────────────────────────────────────────────────────────────────┘
    (All spaces in the "" line should be ignored. They are purely for formatting.)

So this `http://username:password@gw.rainproxy.io:5959` should be correct, if it does not work then its blocked by Steam.

**Comment by SpaceR3** [comment]
Hello, that is the format, I tested manually. I used the proxy and i could log in. + I generated steam accounts with the proxy aswell

**Comment by SpaceR3** [comment]
hey, your commend bot does not support proxy auth?? I tested with free proxies and it worked. The paid proxy works when using other checkers, http://username:password@gw.rainproxy.io:5959 Is not the right format obv

**Comment by BeepIsla** [comment]
Others have used proxies with auth before just fine

**Comment by SpaceR3** [comment]
ip:port:username:password is the right format
