### ISSUE TITLE
Failed to commend

### ISSUE THREAD

**Issue by HackerGeo-sp1ne** [BeepIsla/csgo-commend-bot#463]
name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (F:\\Backups\\desktop-2020\\HackerG\\CommendsCSGO\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'

**Comment by HackerGeo-sp1ne** [comment]
how i fix this?

**Comment by BeepIsla** [comment]
#428
