### ISSUE TITLE
TypeError: Cannot read property 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by XclusivVv** [BeepIsla/csgo-commend-bot#466]
Hi, I noticed you updated this from Marc's pull request about 15 minutes ago.

Since the update, whenever you try and run this, the following error comes up:

TypeError: Cannot read property 'toUpperCase' of undefined

It also mentions:

  <rejected> TypeError: Cannot read property 'toUpperCase' of undefined
      at C:\csgo-commend-bot-master\index.js:277:23

**Comment by BeepIsla** [comment]
Fix your config, there is a variable missing. Even better just delete your config and make a new one from the example.
