### ISSUE TITLE
Script installation - Problem with opening databaseManager.js

### ISSUE THREAD

**Issue by 7eb0xdd** [BeepIsla/csgo-commend-bot#467]
Hello.

I was trying to install the new version of the script on my VPS and as well on my desktop and I am having a problem to open databaseManager.js. Can someone try new installation of te script and tell me, if the problem is on my side?

![image](https://user-images.githubusercontent.com/65721795/85805382-6e0d8a00-b74c-11ea-832a-81554bf51c2c.png)

Thank you.

**Comment by BeepIsla** [comment]
What happens? What is the error? *Any* information?

**Comment by 7eb0xdd** [comment]
*edited

**Comment by 7eb0xdd** [comment]
When I type to console **node databaseManager.js** it wont open the table

**Comment by BeepIsla** [comment]
Fixed in 2.8.2 (091cd436e585de972958412b75603a119cbe8c62)
