### ISSUE TITLE
end of chunk commend count wrong

### ISSUE THREAD

**Issue by mikelobam** [BeepIsla/csgo-commend-bot#468]
end of chunk commend count wrong example;

"Chunk 20 finished with 15/20

actually 19 is successful send commend

I think there is an error in the commend count.

**Comment by BeepIsla** [comment]
Is this in pre-load or not?

**Comment by mikelobam** [comment]
> Is this during preload or not?

Yeah so so

**Comment by RadicalRedemption** [comment]
When you list commends for user from the database manager, it shows 2x the amount of commends sent. :)

**Comment by BeepIsla** [comment]
@RadicalRedemption next time please open your own issue as its unrelated to this one.

Both of these issues have now been fixed in 2.8.3
