### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by Seteziin** [BeepIsla/csgo-commend-bot#470]
![image](https://user-images.githubusercontent.com/67118259/85880320-2faab600-b7b2-11ea-98c6-eba7474b45e2.png)

**Version**
NodeJS: v12.16.3
Script version: 2.8.1

**Comment by BeepIsla** [comment]
Config?

**Comment by Seteziin** [comment]
{
	"commend": {
		"friendly": 10000,
		"teaching": 10000,
		"leader": 10000
	},
	"report": {
		"aimbot": 10,
		"wallhack": 10,
		"speedhack": 10,
		"teamharm": 10,
		"abusive": 10
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"fetcher": {
		"username": "",
		"password": "",
		"sharedSecret": "",
		"maxTries": 10,
		"tryDelay": 2500,
		"askSteamGuard": true
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/id/******",
	"serverID": "auto",
	"matchID": "0",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"showCommends": false,
	"switchServerAfterChunks": 5,
	"steamWebAPIKey": "*******",
	"disableUpdateCheck": false
}

**Comment by BeepIsla** [comment]
Read the README, it explains everything.

You need to put in an account in the fetcher section, it doesn't matter what account, just generate some random account and put it in there.
