### ISSUE TITLE
Bug trying to connect

### ISSUE THREAD

**Issue by xSuspect** [BeepIsla/csgo-commend-bot#471]
**Detailed bug description**
when I give "node index" instead of receiving on the server, trying to connect by logging
I installed  twice

**Config**
```
![Screenshot_1](https://user-images.githubusercontent.com/45514952/85921883-27bd4580-b888-11ea-9386-c0a05f326053.png)
![Screenshot_2](https://user-images.githubusercontent.com/45514952/85921884-2855dc00-b888-11ea-8f87-c1ac92f9c74e.png)

```

**Version**
- NodeJS: `v12.16.3.
- Script version: `2.8.2` 

**Additional information**
Add any other potentially useful information about your issue here.

**Comment by BeepIsla** [comment]
Read what the fetcher does, the bot needs extra information to be usable, the fetcher will get it. Just put in some random bot account into the "fetcher" section of the config.

Alternatively disable `showCommends` and remove all `AUTO`'s

**Comment by xSuspect** [comment]
> Citiți ce face fetcher-ul, bot-ul are nevoie de informații suplimentare pentru a putea fi utilizat, căutătorul îl va primi. Trebuie doar să introduceți un cont bot aleatoriu în secțiunea „căutător” din configurare.
> 
> Alternativ , Dezactivați `showCommends`și eliminați toate `AUTO`„s

yes but i don't want by the account method(fetcher ),  I want by the server method,  and automatically  moves to fetcher

**Comment by xSuspect** [comment]
> Read what the fetcher does, the bot needs extra information to be usable, the fetcher will get it. Just put in some random bot account into the "fetcher" section of the config.
> 
> Alternatively disable `showCommends` and remove all `AUTO`'s

yes but i don't want by the account method(fetcher ), I want by the server method, and automatically moves to fetcher

**Comment by BeepIsla** [comment]
Read what I said, if you don't want to use fetcher the disable `showCommends` and manually fill out all `AUTO`'s with their correct value. The easiest is to just generate a random account and put it in as fetcher.

**Comment by xSuspect** [comment]
yes it works thanks
