### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by ReFa151** [BeepIsla/csgo-commend-bot#474]
![Screenshot_1](https://user-images.githubusercontent.com/67507371/85923203-74555080-b889-11ea-829e-6e8e0a127ef6.png)

**Comment by BeepIsla** [comment]
Config? Anything?

**Comment by ReFa151** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/67507371/85923246-f47bb600-b889-11ea-9282-82cc2f32e608.png)

**Comment by BeepIsla** [comment]
Is the account in `fetcher` a bot account or your own account?

**Comment by ReFa151** [comment]
In fetcher is my main acc

**Comment by ReFa151** [comment]
I'm going to record and send a video okay?

**Comment by BeepIsla** [comment]
You're doing it wrong then, generate an account and put it in as `fetcher`.

**Comment by ReFa151** [comment]
Okey thank you

**Comment by ReFa151** [comment]
![image](https://user-images.githubusercontent.com/67507371/85924183-d49bc080-b890-11ea-9d44-c600bc77d799.png)

**Comment by BeepIsla** [comment]
Read the error, you are logging in too often and have been blocked by Steam, wait 30-60 minutes and then try again.

**Comment by ReFa151** [comment]
Thank you
