### ISSUE TITLE
Login method error at 5 chunk

### ISSUE THREAD

**Issue by rabell69** [BeepIsla/csgo-commend-bot#477]
Chunk 5/35 finished with 18 successful commends and 2 failed commends
 Waiting 300000ms...
 Getting an available server after 5 chunks
 Failed to fetch new server, continuing with old server 90136606982152196
TypeError: targetAcc.setGamesPlayed is not a function
    at C:\Users\user\Desktop\working\csgo\csgo-commend-bot-master\index.js:395:14 Promise {
  <rejected> TypeError: targetAcc.setGamesPlayed is not a function
      at C:\Users\user\Desktop\working\csgo\csgo-commend-bot-master\index.js:395:14

I've tried this method several times and every time at 5 chunk there's this mess.
This error also occurs on the version 2.8.2

**Comment by BeepIsla** [comment]
Config?

**Comment by rabell69** [comment]
{
	"commend": {
		"friendly": 700,
		"teaching": 700,
		"leader": 700
	},
	"report": {
		"aimbot": 10,
		"wallhack": 10,
		"speedhack": 10,
		"teamharm": 10,
		"abusive": 10
	},
	"account": {
		"username": "xxx",
		"password": "xxx",
		"sharedSecret": ""
	},
	"fetcher": {
		"username": "",
		"password": "",
		"sharedSecret": "",
		"maxTries": 10,
		"tryDelay": 2500,
		"askSteamGuard": true
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "LOGIN",
	"target": "",
	"serverID": "auto",
	"matchID": "0",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"showCommends": false,
	"switchServerAfterChunks": 5,
	"steamWebAPIKey": "xxxx",
	"disableUpdateCheck": false
}
