### ISSUE TITLE
Is it possibe

### ISSUE THREAD

**Issue by renodog123** [BeepIsla/csgo-commend-bot#478]
Hello. I wanted to ask is it possible to commend 2 or more accounts in the same time.
I've Have like a 100k combo list working. So Because I can't load them all at 1 time I need to them like 500 or 1000.
After I've received those commends I would like to continue from 1000 not to start all over from chunk 1 takes so much to get to 1000 again and wait addional 1000 for example.
I also think of gettings HTTP proxies and lower the time between chunks since I will be using proxy every 20 accounts.According to me that makes it possible to spam fast commends with decent amount of proxies.

**Comment by BeepIsla** [comment]
No

**Comment by renodog123** [comment]
Well actually it is I found a way out but ok

**Comment by Jaeger33211Sec** [comment]
> Well actually it is I found a way out but ok

Ye lock accounts. Every other way is sloppy. And Beepisla is right his project in its current state can max. commend/report 1 player.
