### ISSUE TITLE
 Failed to decode Steam rich presence keyvalues :  Failed to receive Valve CSGO Server information

### ISSUE THREAD

**Issue by MrMuyV2** [BeepIsla/csgo-commend-bot#480]
**Detailed bug description**

**Error**
```
https://prnt.sc/t7nkse.
```

**Config**
```
Same
```

**Version**
Same

**Additional information**
I am lost xDD

**Comment by BeepIsla** [comment]
This happens when `cl_join_advertise` is **not** set to `2` or you are not on a official Valve Matchmaking server. Other things which may cause this are a private profile or a full server.

**Comment by MrMuyV2** [comment]
Okey so i need to start cs:go and go on a offical valve server?

**Comment by MrMuyV2** [comment]
ah got it mate danke dir biste eine ehrenbruder!
