### ISSUE TITLE
Acc

### ISSUE THREAD

**Issue by ReFa151** [BeepIsla/csgo-commend-bot#481]
The question is do you have a bot that does acc or?

**Comment by BeepIsla** [comment]
What

**Comment by ReFa151** [comment]
I can't find profiles for commend bot. Is there any page that makes a lot of acco or is there something else?

**Comment by BeepIsla** [comment]
This is unrelated to the commend bot itself. Just Google for any Steam Account Generator, something like [accgen.cathook.club](https://accgen.cathook.club/)
