### ISSUE TITLE
Error: GC connection timeout - Hello

### ISSUE THREAD

**Issue by vandalizexx** [BeepIsla/csgo-commend-bot#482]
when i write node index.js , it says it is logging but then it says this
Error: GC connection timeout - Hello
    at SteamUser.loggedOn (C:\aadas\helpers\account.js:129:14) Promise {
  <rejected> Error: GC connection timeout - Hello
      at SteamUser.loggedOn (C:\aadas\helpers\account.js:129:14)
how do i fix?

**Comment by rabell69** [comment]
the same problem

**Comment by BeepIsla** [comment]
Post your configs people you are not helping

**Comment by BananasToaster** [comment]
oh hey i have the same problem here

{
	"commend": {
		"friendly": 300,
		"teaching": 300,
		"leader": 300

	},
	"report": {
		"aimbot": 0,
		"wallhack": 0,
		"speedhack": 0,
		"teamharm": 0,
		"abusive": 0
	},
	"account": {
		"username": "secret",
		"password": "secrettttt",
		"sharedSecret": ""
	},
	"fetcher": {
		"username": "",
		"password": "",
		"sharedSecret": "",
		"maxTries": 10,
		"tryDelay": 2500,
		"askSteamGuard": false
	},
	"proxy": {
		"enabled": false,
		"file": "http_proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/profiles/secretheheheheeh/",
	"serverID": "auto",
	"matchID": "auto",
	"perChunk": 15,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"switchServerAfterChunks": 5,
	"steamWebAPIKey": "yeahigotidhere",
	"disableUpdateCheck": false
}

**Comment by BeepIsla** [comment]
Stop using `auto` without a fetcher. READ. If you use auto you NEED a fetcher.
