### ISSUE TITLE
Loggin into fetcher account failed

### ISSUE THREAD

**Issue by Wyleee** [BeepIsla/csgo-commend-bot#484]
**Detailed question description**
I filled in a robot account at the “fetcher”,but the following error occurred

 Logging into fetcher account...
Error: Failed to log in within given 60000ms
    at Timeout._onTimeout (C:\Users\123\Desktop\csgo-commend-bot-master\helpers\account.js:52:12)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) Promise {
  <rejected> Error: Failed to log in within given 60000ms
      at Timeout._onTimeout (C:\Users\123\Desktop\csgo-commend-bot-master\helpers\account.js:52:12)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)
}

Sorry my English is not very good (ಥ_ಥ) 

**Config**
```
{
	"commend": {
		"friendly": 15,
		"teaching": 15,
		"leader": 15
	},
	"report": {
		"aimbot": 10,
		"wallhack": 10,
		"speedhack": 10,
		"teamharm": 10,
		"abusive": 10
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"fetcher": {
		"username": "ornbills6pampaloni886",
		"password": "R5CERTHHZBXZ024",
		"sharedSecret": "",
		"maxTries": 10,
		"tryDelay": 2500,
		"askSteamGuard": true
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/profiles/xxxxxxxxxxx/",
	"serverID": "auto",
	"matchID": "0",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"switchServerAfterChunks": 5,
	"steamWebAPIKey": "xxxxxxxxxxxxxxxxxxxxxxx",
	"disableUpdateCheck": true
}

```

**Version**
- NodeJS: 12.9.1
- Script version: 2.8.4

**Comment by BeepIsla** [comment]
Just try a different account

**Comment by Wyleee** [comment]
tks，let me try
