### ISSUE TITLE
Failed to send messsage: Timeout

### ISSUE THREAD

**Issue by BotDeTeste** [BeepIsla/csgo-commend-bot#486]
[FaithfulEminentHerring] Failed to commend (50/50) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\Nickolas\\Desktop\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
}
 Chunk 5/20 finished with 20 successful commends and 30 failed commends

**Comment by 7eb0xdd** [comment]
Use 20 accounts per chunk, not 50.

**Comment by BeepIsla** [comment]
As stated above
