### ISSUE TITLE
What is the Fetcher account

### ISSUE THREAD

**Issue by FagBoiJJ** [BeepIsla/csgo-commend-bot#487]
I can't seem to find an answer, I prob just don't know how to use google properly XD, Can somebody please tell me what the "fetcher account" is and do I put the account in that I am trying to use the commend bot on or do I put a random account in there?

if somebody can just give me a description of what the fetcher account is that would be awesome!

**Comment by FagBoiJJ** [comment]
And each time I put an account in the fetcher account that isn't the account I commend boting it says the csgo server is offline or is full, neither is true, I put the account I am trying to commend bot it says GC connection timeout

**Comment by BeepIsla** [comment]
The fetcher automatically gets information like ServerID and MatchID so you don't have to do it yourself. You put in a bot account and forget about it, that simple.

It only works under certain conditions, either the target is on a Valve server or is using `cl_join_advertise 2` on a non-full community server.
