### ISSUE TITLE
Error pls help

### ISSUE THREAD

**Issue by Alex1274** [BeepIsla/csgo-commend-bot#488]
![plsssss](https://user-images.githubusercontent.com/67577678/85984128-615d9000-b9f1-11ea-82ae-b6676bbb100f.png)
help me please

**Comment by BeepIsla** [comment]
Try running `npm ci`

**Comment by Alex1274** [comment]
I wrote so

**Comment by BeepIsla** [comment]
Does the same error still happen after running `npm ci`?

**Comment by Alex1274** [comment]
No
![plss2](https://user-images.githubusercontent.com/67577678/85984486-ee084e00-b9f1-11ea-870d-a4b41f3b2f1b.png)

**Comment by BeepIsla** [comment]
I don't care about the output of `npm ci`, you're suppose to run `node databaseManager.js` again.

**Comment by Alex1274** [comment]
The same error does not work

**Comment by BeepIsla** [comment]
What NodeJS version are you using (`node -v`)

**Comment by Alex1274** [comment]
v13.6.0

**Comment by BeepIsla** [comment]
Read the README. It says:

> # Requirements
> - [NodeJS v12](https://nodejs.org/en/)

Uninstall v13 and install v12.

**Comment by Alex1274** [comment]
ok

**Comment by Alex1274** [comment]
Thx :)
