### ISSUE TITLE
db not updating

### ISSUE THREAD

**Issue by pelasta** [BeepIsla/csgo-commend-bot#490]
The db is not updating the used accounts even after the cooldown is passed,

I have set the cooldown in my config to 2000 just to test it and still giving me "not available accounts" message even after waiting more than 5 min.

{
	"commend": {
		"friendly": 5,
		"teaching": 10,
		"leader": 15
	},
	"report": {
		"aimbot": 5,
		"wallhack": 5,
		"speedhack": 5,
		"teamharm": 5,
		"abusive": 5
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"fetcher": {
		"username": "00000",
		"password": "000000",
		"sharedSecret": "",
		"maxTries": 10,
		"tryDelay": 2500,
		"askSteamGuard": true
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/profiles/00000/",
	"serverID": "auto",
	"matchID": "0",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 20000,
	"showCommends": false,
	"switchServerAfterChunks": 5,
	"steamWebAPIKey": "00000000000",
	"disableUpdateCheck": false
}

**Comment by BeepIsla** [comment]
You cannot commend the same account twice with the same bot. Go in-game and try to commend someone, you can only do it once and then never again. Same applies to bots.

**Comment by pelasta** [comment]
I'm not trying to commend the same account twice, I need to be able to commend two ppl without resetting the db each time, for ex:

I have a db with 5 accounts and I used them to commend "x" player
now I need to commend "y" player, the script won't let me as there won't be any account available...

**Comment by BeepIsla** [comment]
This should not happen and I never had anyone report such an issue, selecting accounts from the database has never changed since the introduction of it in 2.0.0. How long do you wait? You can try simply changing the cooldown in your config to `1` for one millisecond. If it still doesn't work I suggest you try commending a random person on a Deathmatch server to see if the error still happens.

If nothing works and you still run into this issue something is definitely wrong.

**Comment by pelasta** [comment]
Already tried that with 2.6.1 & 2.8.4 Versions

no matter what the cooldown is, it will keep showing "**Not enough accounts available, got 0/5**"
can someone try and confirm pls..

**Comment by BeepIsla** [comment]
I will test it out in a few hours

**Comment by BeepIsla** [comment]
I cannot replicate this.

## Finished commending first player

    Chunk 1/1 finished with 5 successful commends and 0 failed commends
    Logging into fetcher account for commend count...
    Current target commends: F7 T6 L7
    Change:
    - F +5
    - T +5
    - L +5
    Finished all chunks with a total of 5 successful and 0 failed commends

## Trying to commend second player

    Checking for new update...
    Up to date!
    Checking protobufs...
    Found protobufs
    Opening database...
    There are a total of 5 operational accounts
    Parsing target account...
    Not enough accounts available, got 0/5

## Still trying to commend second player

    Checking for new update...
    Up to date!
    Checking protobufs...
    Found protobufs
    Opening database...
    There are a total of 5 operational accounts
    Parsing target account...
    Not enough accounts available, got 4/5

## Start of commending second player

    Checking for new update...
    Up to date!
    Checking protobufs...
    Found protobufs
    Opening database...
    There are a total of 5 operational accounts
    Parsing target account...
    Chunking 5 accounts into groups of 20...
    Parsing server input

Make sure you are actually changing the target in your config, make sure you are editing the correct config file if you have multiple, make sure it is named correctly, make sure you aren't replacing the fetcher account, etc. Check if you change the commend amount if the `Not enough accounts available, got 0/5` message changes accordingly to the amount of commends you entered. This is an issue on your side and not with the script.
