### ISSUE TITLE
Suggestion: Removing all accounts out of database

### ISSUE THREAD

**Issue by inbroso** [BeepIsla/csgo-commend-bot#491]
Hey,
in my opinion it would be cool if there would be a little feature of removing all accounts without the commend history in the database. Otherwise when resetting the database and later adding the accounts back, the account gets commended again with the same accounts and that would be a timewaste :P

**Comment by BeepIsla** [comment]
But why? Just don't remove accounts from the DB?

**Comment by BeepIsla** [comment]
No response but I guess it can't harm to have it...
