### ISSUE TITLE
Report bot

### ISSUE THREAD

**Issue by FagBoiJJ** [BeepIsla/csgo-commend-bot#492]
I try report botting this blatant hacker in prime but all i get is "timeout"

CFG here!

{
	"commend": {
		"friendly": 0,
		"teaching": 0,
		"leader": 0
	},
	"report": {
		"aimbot": 113,
		"wallhack": 113,
		"speedhack": 113,
		"teamharm": 0,
		"abusive": 0
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"fetcher": {
		"username": "XXXXXXXXXXXXXXXXXXX",
		"password": "XXXXXXXXXXXXXXXXXXX",
		"sharedSecret": "",
		"maxTries": 10,
		"tryDelay": 2500,
		"askSteamGuard": true
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "REPORT",
	"method": "SERVER",
	"target": "https://steamcommunity.com/id/ImDeadInsideRN/",
	"serverID": "auto",
	"matchID": "0",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"showCommends": false,
	"switchServerAfterChunks": 5,
	"steamWebAPIKey": "",
	"disableUpdateCheck": false
}

**Comment by BeepIsla** [comment]
You cannot report in a live Competitive/Wingman match.

**Comment by FagBoiJJ** [comment]
So then how would i know when to report him?

**Comment by BeepIsla** [comment]
You don't. Apparently you can report between right when the match ends and when you get automatically kicked out of the match, but you need to be fast for it to work and hope they don't leave.

Otherwise you are out of luck.
