### ISSUE TITLE
LOGIN method giving error

### ISSUE THREAD

**Issue by FPSGuilherme** [BeepIsla/csgo-commend-bot#494]
**Detailed bug description**
When I put it in the login method, to leave it on a vps during the night, I am encountering this problem that is in the print 1
In addition, the method of changing servers every 5 games is giving this error (print 2)

**Error**
```
print 1 https://prnt.sc/t9fxns
print 2 https://prnt.sc/t9g20j
```

**Config**
```
https://prnt.sc/t9g0h7
```

**Version**
- NodeJS: `v12.18.1`
- Script version: `2.8.4`

**Comment by BeepIsla** [comment]
I assume your VPS lost connection to Steam and the bot never reconnected

**Comment by FPSGuilherme** [comment]
> I assume your VPS lost connection to Steam and the bot never reconnected

Got it, what about changing the server after 5 chunks?

**Comment by BeepIsla** [comment]
Does that error happen every time when changing server?

**Comment by FPSGuilherme** [comment]
OK thank you
