### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by ShukanGOD** [BeepIsla/csgo-commend-bot#495]
TypeError: Cannot read property 'toUpperCase' of undefined
    at C:\Users\suaby\Desktop\bot\csgo-commend-bot-master\index.js:276:23 Promise {
  <rejected> TypeError: Cannot read property 'toUpperCase' of undefined
      at C:\Users\suaby\Desktop\bot\csgo-commend-bot-master\index.js:276:23

**Comment by BeepIsla** [comment]
Fix your config, do not delete anything from it. Look at the example config for all required values.
