### ISSUE TITLE
UnhandledPromiseRejection during commending 

### ISSUE THREAD

**Issue by ypc123** [BeepIsla/csgo-commend-bot#496]
**Node:1508 eror**
Usually an error occurs in the middle of 20 in the login method

**Error**
```
![IYFEyx](https://user-images.githubusercontent.com/10389186/86213732-cf858c80-bb82-11ea-955b-7348a05011c2.png)

```

**Config**
```
{
	"commend": {
		"friendly": 1100,
		"teaching": 1100,
		"leader": 1100
	},
	"report": {
		"aimbot": 10,
		"wallhack": 10,
		"speedhack": 10,
		"teamharm": 10,
		"abusive": 10
	},
	"account": {
		"username": "******",
		"password": "*****",
		"sharedSecret": ""
	},
	"fetcher": {
		"username": "Account",
		"password": "Password",
		"sharedSecret": "",
		"maxTries": 10,
		"tryDelay": 2500,
		"askSteamGuard": true
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "LOGIN",
	"target": "https://steamcommunity.com/profiles/*******",
	"serverID": "95.173.***:27015",
	"matchID": "0",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"showCommends": false,
	"switchServerAfterChunks": 5,
	"steamWebAPIKey": "*****************************",
	"disableUpdateCheck": false
}
```

**Version**
- NodeJS: `v12.9.1 
- Script version: `2.8.4`

**Comment by ypc123** [comment]
![IYFEyx](https://user-images.githubusercontent.com/10389186/86213824-f3e16900-bb82-11ea-9713-84a47db272ea.png)

**Comment by ypc123** [comment]
a new eror
![eror2](https://user-images.githubusercontent.com/10389186/86218405-62c1c080-bb89-11ea-88a7-2e532b79d26d.png)

**Comment by crx9** [comment]
same problem


(node:19424) UnhandledPromiseRejectionWarning: Error: Request timed out
    at Timeout._onTimeout (C:\Users\nmy\Desktop\csgo-commend-bot-master\csgo-commend-bot-master\node_modules\steam-user\node_modules\@doctormckay\stdlib\components\promises.js:17:12)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
(node:19424) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19424) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by BeepIsla** [comment]
This might be fixed? If not please re-open or create a new issue.
