### ISSUE TITLE
Commend bot stopping, freezing when commending..

### ISSUE THREAD

**Issue by Andriuxas** [BeepIsla/csgo-commend-bot#497]
So ya my commend bot stops and not commends its really annoying. And its like after some chunks or some time..
![image](https://user-images.githubusercontent.com/64680439/86244036-03c37200-bbb0-11ea-89be-c777e18ffcdc.png)

**Comment by ypc123** [comment]
I'm having the same problem, login method?

**Comment by Andriuxas** [comment]
Nope server method

**Comment by BeepIsla** [comment]
This is related to #496
