### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by MrMuyV2** [BeepIsla/csgo-commend-bot#498]
**Detailed bug description**

**Error**
```
https://prnt.sc/t9ui61
```

**Config**
```
same
```

**Version**
same

**Additional information**
Add any other potentially useful information about your issue here.

**Comment by ypc123** [comment]
you get module error

cmd: npm install or npm install inquirer

**Comment by MrMuyV2** [comment]
Okey i will do :)

**Comment by MrMuyV2** [comment]
https://prnt.sc/t9v9qn

**Comment by ypc123** [comment]
try this, npm install sqlite3 and npm install sqlite

**Comment by MrMuyV2** [comment]
https://prnt.sc/t9ve1c

**Comment by ypc123** [comment]
"npm install" Did you try?

**Comment by MrMuyV2** [comment]
ye

**Comment by MrMuyV2** [comment]
https://prnt.sc/t9vgut

**Comment by ypc123** [comment]
Node version?

**Comment by MrMuyV2** [comment]
14

**Comment by MrMuyV2** [comment]
https://prnt.sc/t9vtlk

**Comment by ypc123** [comment]
use 12.9.1
![image](https://user-images.githubusercontent.com/10389186/86261810-b2bf7800-bbc7-11ea-8f7b-e8e5fa8d83a3.png)

**Comment by MrMuyV2** [comment]
ye its now working all fine

**Comment by MrMuyV2** [comment]
#closed

**Comment by BeepIsla** [comment]
Always use `npm ci` rather than `npm install`
