### ISSUE TITLE
?

### ISSUE THREAD

**Issue by ReFa151** [BeepIsla/csgo-commend-bot#500]
![Screenshot_1](https://user-images.githubusercontent.com/67507371/86325362-32892900-bc40-11ea-8a7a-fb2593fbf0d9.png)

**Comment by ReFa151** [comment]
How fix this?

**Comment by BeepIsla** [comment]
Play on a Valve server or use `cl_join_advertise 2` on a Community server

**Comment by ReFa151** [comment]
I'm getting into a deadmatch

**Comment by ReFa151** [comment]
It will be the same again ...

**Comment by BeepIsla** [comment]
Make sure the server is **not** full.

**Comment by ReFa151** [comment]
Okay, I fixed it
