### ISSUE TITLE
Getting InvalidPassword

### ISSUE THREAD

**Issue by lipedm** [BeepIsla/csgo-commend-bot#502]
I bought a list with 100 steam acc, logging into somes to test if work, yeah i can log into them.

**Error**

[EDIT] im using the user:password format into account.txt, already tried to insert manually into database and still not working.
But when using  the commend-bot i've got the message:

![image](https://user-images.githubusercontent.com/57644779/86413290-2ed4c100-bc97-11ea-95c9-074f3bccfbc8.png)

there is my config.json without my api and profile:

`{
	"commend": {
		"friendly": 1,
		"teaching": 1,
		"leader": 1
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"fetcher": {
		"username": "Account",
		"password": "Password",
		"sharedSecret": "",
		"maxTries": 10,
		"tryDelay": 2500,
		"askSteamGuard": true
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "",
	"serverID": "131.196.199.240:27100",
	"matchID": "0",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"showCommends": false,
	"switchServerAfterChunks": 5,
	"steamWebAPIKey": "",
	"disableUpdateCheck": false
}
`

**Version**
- NodeJS: `vXX.XX.X` (You can find this using `node -v`)
- Script version: `X.X.X` (You can find this in **your** `package.json` file under `version`)
![image](https://user-images.githubusercontent.com/57644779/86413200-0056e600-bc97-11ea-8fbb-24b6e262c9a6.png)

**Comment by BeepIsla** [comment]
Well, Steam says the password is wrong. There isn't much I can say to this, make sure there are no spaces or anything in the username & password when adding them. If you really want to verify its all correct download [SQLite Browser](https://sqlitebrowser.org/) and open up the `accounts.sqlite` file, navigate to `Browse Data` and look at the accounts list.

**Comment by lipedm** [comment]
well, i oppened with sqlite browser and insert manually the data and it works. thx
