### ISSUE TITLE
RateLimitExceeded

### ISSUE THREAD

**Issue by kmko1337** [BeepIsla/csgo-commend-bot#506]
**Detailed bug description**
Then i commend i get error RateLimitExceeded, from 20 i receive 2 commends

**Error**
```
https://prnt.sc/tbr49g
```

**Config**
```
default
```

**Version**
- NodeJS: `v12.18.2`
- Script version: `2.8.2` 

**Additional information**
If i try with different target i get same problem.

**Comment by BeepIsla** [comment]
`RateLimitExceeded` means just what it reads as. You logged into too many accounts in a too short amount of time, this mostly happens with failed logins, successful logins almost never rate limit you can but it can happen.

Either use **good** proxies which are hard to find or wait 30 minutes. While waiting **do not** try to login again, if you do the timer will reset and you have to wait all over again.

**Comment by kmko1337** [comment]
Do you know max amount of login tries? or succesfully logged ?

**Comment by kmko1337** [comment]
Also a good idea is to do a steam accounts check (if login succes save, if failed delete)

**Comment by BeepIsla** [comment]
> Do you know max amount of login tries? or succesfully logged ?

No.

> Also a good idea is to do a steam accounts check (if login succes save, if failed delete)

If an account fails to login it will not be used ever again unless you mess with the database.
