### ISSUE TITLE
Maybe useless question

### ISSUE THREAD

**Issue by kmko1337** [BeepIsla/csgo-commend-bot#507]
**Detailed question description**
Can i stop a commend bot session from another terminal? I mean, i start a commend bot session and then type !stop <steamid64> from another terminal, i tried to do that but idk how to find the right session (if there is 2 working in the same time).

If you can help me, or just give an idea will be good, thanks

**Version**
- Script version: `2.8.2`

**Comment by BeepIsla** [comment]
You can kill the process whenever you want, it really doesn't matter

**Comment by kmko1337** [comment]
yes but i want to kill it with a command, to find the right session and kill it, i tried to rename process name with steamid64 and kill the process but didn't worked to rename process name with process.title = `${process.argv[4]}`; // process.argv[4] = steamid64

**Comment by BeepIsla** [comment]
That's not really related to the bot it self, so I don't really know. I assume you could just give it another launch-argument as identifier then you read what arguments the process started with to choose which one to kill and which one to keep alive

**Comment by kmko1337** [comment]
i tried to do that, when commend bot start create a file with steamid64 name, then every chunk check if file exist, if i do !stop <Steamid64> it delete the file, and next chunk it check if file exist, if it doesn't exist script stop, but didn't worked *mby wrong coded not sure* (shit code and idea)
