### ISSUE TITLE
connect timeout

### ISSUE THREAD

**Issue by RetiredQQ** [BeepIsla/csgo-commend-bot#508]
**ETimeout**
Connecting to 184.26.194.101 timeout

**Config**
```
{
	"commend": {
		"friendly": 200,
		"teaching": 200,
		"leader": 200
	},
	"report": {
		"aimbot": 0,
		"wallhack": 0,
		"speedhack": 0,
		"teamharm": 0,
		"abusive": 0
	},
	"account": {
		"username": "CENSORED",
		"password": "CENSORED",
		"sharedSecret": ""
	},
	"fetcher": {
		"username": "CENSORED",
		"password": "CENSORED",
		"sharedSecret": "",
		"maxTries": 10,
		"tryDelay": 2500,
		"askSteamGuard": true
	},
	"proxy": {
		"enabled": true,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "LOGIN",
	"target": "https://steamcommunity.com/id/gaben",
	"serverID": "auto",
	"matchID": "0",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"showCommends": true,
	"autoReportOnMatchEnd": false,
	"switchServerAfterChunks": 5,
	"steamWebAPIKey": "CENSORED",
	"disableUpdateCheck": false
}

```

**Version**
- NodeJS: `v12.9.1` (You can find this using `node -v`)
- Script version: `2.9.0` (You can find this in **your** `package.json` file under `version`)

![Capture](https://user-images.githubusercontent.com/13232132/86523444-1931e800-be9f-11ea-8f78-af1da6df99e0.PNG)

**Comment by BeepIsla** [comment]
Something on your end is blocking connection to Steam/Akamai

**Comment by RetiredQQ** [comment]
Okay that issue already fixed but now I'm getting this error `Failed to login and has been marked as invalid` I already verify that the login is working but still get that error.
