### ISSUE TITLE
set different number of commendation

### ISSUE THREAD

**Issue by crx9** [BeepIsla/csgo-commend-bot#510]
fill these in config
"commend": {
"friendly": 80,
"teaching": 400,
"leader": 80
},
if process has 20 failures ,friendly only increased 60 ，so failures are also counted?
I think if set different numbers,failures with a fewer number of settings should not be counted

**Comment by BeepIsla** [comment]
What does this mean

**Comment by crx9** [comment]
set  f80 t100 l80  , if only  faild 20, friendly  increases 60 instead of 80    . f+60  t+80 l+60,why not  80/80/80？

**Comment by BeepIsla** [comment]
I assume this is the known "Commended but did not increase" problem. It says successful but the number did not increase for some reason.
