### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by renerteee** [BeepIsla/csgo-commend-bot#512]
![image](https://user-images.githubusercontent.com/67871718/86537742-0f899e00-befa-11ea-81cd-a0c1c98884e6.png)
![image](https://user-images.githubusercontent.com/67871718/86537786-4a8bd180-befa-11ea-84d3-9954dba7e36a.png)

please help, it doesn't working :c

**Comment by BeepIsla** [comment]
Please download [this `Helper.zip` file](https://github.com/BeepIsla/csgo-commend-bot/files/4875315/Helper.zip), extract it and put the `Helper.js` file in the `helpers` folder, replace it with the old one.

**Comment by renerteee** [comment]
> Please download [this `Helper.zip` file](https://github.com/BeepIsla/csgo-commend-bot/files/4875315/Helper.zip), extract it and put the `Helper.js` file in the `helpers` folder, replace it with the old one.
> 
> Then try again, does it work?

![image](https://user-images.githubusercontent.com/67871718/86624041-53000d00-bfcb-11ea-87ac-e4312f7c7397.png)
No, it isn't :c

**Comment by BeepIsla** [comment]
Something is blocking access to https://raw.githubusercontent.com/BeepIsla/csgo-commend-bot/master/package.json This seems to be an issue on your side and I cannot help you to resolve it.

One thing you can do is set `disableUpdateCheck` to`true` so it no longer checks for updates but then you will no longer be notified when this gets project updated.
