### ISSUE TITLE
TypeError: Cannot read property 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by nikhilkharade** [BeepIsla/csgo-commend-bot#513]
**Detailed bug description**

**Error**
TypeError: Cannot read property 'toUpperCase' of undefined
A full error log or screenshot.
```
![image](https://user-images.githubusercontent.com/55026038/86539024-4b7f2c00-bf17-11ea-92d1-e3d339755b84.png)

**Config**
```
{
	"commend": {
		"friendly": 1,
		"teaching": 2,
		"leader": 1
	},
	
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/id/painf",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"steamWebAPIKey": "06C2896781776D2CF2AA43649A5360BB",
	"disableUpdateCheck": false
}

```

**Version**
- NodeJS: `v12.18.0` (You can find this using `node -v`)
- Script version: `X.X.X` (You can find this in **your** `package.json` file under `version`)
{
  "name": "csgo-commend-bot",
  "version": "2.9.0",
  "description": "CSGO Commend Bot Rewrite",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "github.com/BeepIsla",
  "license": "AGPL-3.0",
  "repository": {
    "type": "git",
    "url": "https://github.com/BeepIsla/csgo-commend-bot.git"
  },
  "dependencies": {
    "@doctormckay/stdlib": "^1.10.2",
    "bytebuffer": "^5.0.1",
    "inquirer": "^6.3.1",
    "protobufjs": "^6.9.0",
    "request": "^2.88.2",
    "serialize-error": "^4.1.0",
    "sqlite": "^4.0.11",
    "sqlite3": "^4.2.0",
    "steam-totp": "^2.1.0",
    "steam-user": "^4.16.2",
    "steamid": "^1.1.0",
    "unquirer": "^1.0.0",
    "unzipper": "^0.10.11"
  }
}

**Additional information**
Add any other potentially useful information about your issue here.

**Comment by BeepIsla** [comment]
Fix your config, you removed something that you shouldn't have removed. Read the README, look at the example config.
