### ISSUE TITLE
What's going on?

### ISSUE THREAD

**Issue by ricardosxx** [BeepIsla/csgo-commend-bot#514]
I think it's a bug 
can you help me?
![捕获](https://user-images.githubusercontent.com/62421009/86561060-50cd8c80-bf92-11ea-924f-a586d2a55dfc.PNG)

**Comment by BeepIsla** [comment]
Something is blocking your access to [this](https://raw.githubusercontent.com/BeepIsla/csgo-commend-bot/master/package.json) file. Fix it, I can't help you with that, its an issue on your side.
