### ISSUE TITLE
Timeout when using reportbot

### ISSUE THREAD

**Issue by BananasToaster** [BeepIsla/csgo-commend-bot#515]
So uh today i was trying to report someone thats cheating hard in csgo, after waiting for him joinin into a competitive, i started my reportbot and then i got tons of timeout errors, and it said failed to report, is that because hes in a valve competitive server?

**Config**
```
{
	"commend": {
		"friendly": 20,
		"teaching": 20,
		"leader": 20

	},
	"report": {
		"aimbot": 202,
		"wallhack": 0,
		"speedhack": 20,
		"teamharm": 20,
		"abusive": 20
	},
	"account": {
		"username": "######",
		"password": "#####",
		"sharedSecret": ""
	},
	"fetcher": {
		"username": "#####",
		"password": "#####",
		"sharedSecret": "",
		"maxTries": 10,
		"tryDelay": 2500,
		"askSteamGuard": true
	},
	"proxy": {
		"enabled": false,
		"file": "http_proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "REPORT",
	"method": "SERVER",
	"target": "yeah a real person",
	"serverID": "auto",
	"matchID": "auto",
	"perChunk": 15,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"switchServerAfterChunks": 5,
	"steamWebAPIKey": "#####",
	"disableUpdateCheck": false
}

```

**Version**
- NodeJS: `v13.8.0` 
- Script version: `2.9.0`

**Comment by BeepIsla** [comment]
You cannot report during a live match.

**Comment by BananasToaster** [comment]
> You cannot report during a live match.

so uh i have to report him when the match ends right?

**Comment by BeepIsla** [comment]
Yes, and if you read the CHANGELOG & Keep up to date with your config you would already see functionality for automatically reporting when the match ends using the fetcher.

**Comment by BananasToaster** [comment]
> Yes, and if you read the CHANGELOG & Keep up to date with your config you would already see functionality for automatically reporting when the match ends using the fetcher.

alright, thanks for that :)
