### ISSUE TITLE
I really dont know 

### ISSUE THREAD

**Issue by Kasoar** [BeepIsla/csgo-commend-bot#517]
Hey can someone tell me how to fix this issue?
![Screenshot_1](https://user-images.githubusercontent.com/64645747/86773178-98691c80-c055-11ea-9350-a71ed3123222.png)

**Config**
```
Your "config.json" - Censor your API Key and account details
```

**Version**
- NodeJS: `vXX.XX.X` (You can find this using `node -v`)
- Script version: `X.X.X` (You can find this in **your** `package.json` file under `version`)

**Comment by BeepIsla** [comment]
Where in the README does it say to run `npm audit`?

**Comment by alioan** [comment]
@BeepIsla ppl dont read it sadly..

**Comment by BeepIsla** [comment]
True

**Comment by Kasoar** [comment]
Hey Isla, i have run npm audit and this was shown to me, then i went on the shown websites, but that did not help me :/

**Comment by Jaeger33211Sec** [comment]
> Hey Isla, i have run npm audit and this was shown to me, then i went on the shown websites, but that did not help me :/

But the bot should still run tho? 
It would help if you try to run the bot and then send ur error

**Comment by BeepIsla** [comment]
> Hey Isla, i have run npm audit and this was shown to me, then i went on the shown websites, but that did not help me :/

Nothing told you to run `npm audit` in the first place. Just ignore it and continue with the installation instructions in the README.
