### ISSUE TITLE
 UnhandledPromiseRejectionWarning When trying to add steam accs.

### ISSUE THREAD

**Issue by aixva** [BeepIsla/csgo-commend-bot#518]
This happens when i write: node databasemanager.js - select add accounts - from txt username:password.
Full log:
(node:17956) UnhandledPromiseRejectionWarning: TypeError: chunk.map(...).flat is not a function
    at askInput (C:\Users\aixva\Desktop\csgo-commend-bot-master\databasemanager.js:235:222)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:17956) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17956) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by BeepIsla** [comment]
What NodeJS version are you using? `node -v`

**Comment by aixva** [comment]
10.16.0

**Comment by aixva** [comment]
> What NodeJS version are you using? `node -v`

10.16.0

**Comment by BeepIsla** [comment]
Read the README, it says use `v12`.
