### ISSUE TITLE
Accounts doesnt work

### ISSUE THREAD

**Issue by gameslp** [BeepIsla/csgo-commend-bot#519]
So i started bot for 20, 20, 20 and it said that i have 22 operational accounts but then it said `"Not enough accounts available, got 7/20"
` What can i do

**Comment by BeepIsla** [comment]
They are either on cooldown or already commended the target once

**Comment by gameslp** [comment]
These are new accounts and didnt commend anyone. Should i disable steam guard?

**Comment by BeepIsla** [comment]
If they had Steam Guard enabled before and you tried using them then they are likely marked as "Invalid" now. Accounts don't randomly get set to be unusable.

**Comment by gameslp** [comment]
I checked in the database manager and it said all are good. So should i disable steam guard on all accounts?

**Comment by BeepIsla** [comment]
Steam Guard does not matter right now because the script never used the account. Download [SQLite Browser](https://sqlitebrowser.org/) and open the `accounts.sqlite`, click on `Browse Data` and see what the actual values are, if it has `operational` as `0` the accounts are unusable and the script did *try* to use the account before or something.

**Comment by gameslp** [comment]
ok and what is the fastest way to make accounts. I tried https://accgen.cathook.club/  but it blocks my gmail and some of accounts doesnt work

**Comment by BeepIsla** [comment]
I only know of that accgen. Steam does lots against generating accounts.

**Comment by gameslp** [comment]
And last question. Can 1 account commend another second time after some time or only once?

**Comment by BeepIsla** [comment]
Just like how it is in-game. You can only commend the same player once and 3 **different** players within 24 hours.

**Comment by gameslp** [comment]
Oh i did commend 3 players today, thats why. THX
