### ISSUE TITLE
Failed to decode Steam rich presence keyvalues | Failed to receive Valve CSGO Server information

### ISSUE THREAD

**Issue by PolakenZigeuner** [BeepIsla/csgo-commend-bot#525]
![image](https://user-images.githubusercontent.com/43918517/87234973-e2942a00-c3d6-11ea-8a66-f38b014f5d51.png)

Config: 

> {
	"commend": {
		"friendly": 40,
		"teaching": 40,
		"leader": 40
	},
	"report": {
		"aimbot": 10,
		"wallhack": 10,
		"speedhack": 10,
		"teamharm": 10,
		"abusive": 10
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"fetcher": {
		"username": "anezzzz187_cs1",
		"password": "**************",
		"sharedSecret": "",
		"maxTries": 10,
		"tryDelay": 2500,
		"askSteamGuard": true
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/profiles/76561199072604244/",
	"serverID": "auto",
	"matchID": "0",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"showCommends": true,
	"autoReportOnMatchEnd": false,
	"switchServerAfterChunks": 5,
	"steamWebAPIKey": "83055B146FE834F0ACDC42FF546487A4",
	"disableUpdateCheck": false
}
>

**Comment by BeepIsla** [comment]
Community server? Valve server?

**Comment by BeepIsla** [comment]
No response.
