### ISSUE TITLE
Error: Invalid status code

### ISSUE THREAD

**Issue by matoqueimado** [BeepIsla/csgo-commend-bot#526]
When i try to commend bot give this error: Error: Invalid Status Code: 500 - Visit https://httpstatuses.com/500
I do exactly what is to do
![Screenshot_1](https://user-images.githubusercontent.com/57582542/87276150-1eea8780-c4b6-11ea-8f72-7bf0850b76bd.png)

**Comment by BeepIsla** [comment]
Error during update check, Github likely had a server problem, just try again

**Comment by matoqueimado** [comment]
Now works \o/
