### ISSUE TITLE
why im getting this error?

### ISSUE THREAD

**Issue by Pecus35** [BeepIsla/csgo-commend-bot#528]
**Detailed bug description**
i just typed node index.js and this happend *you can see at the screenshot*
**Error**
```
A full error log or screenshot.
https://prnt.sc/ti9hbf

**Config**
```
https://prnt.sc/ti9ibk
```

**Version**
- NodeJS: `v12.18.12` (You can find this using `node -v`)
- Script version: `2.9.0` (You can find this in **your** `package.json` file under `version`)

**Comment by BeepIsla** [comment]
You are trying to use the fetcher without providing one. Put an account in the fetcher section of your config.

**Comment by Pecus35** [comment]
https://www.youtube.com/watch?v=C6DcZd5yJqE i watched this video but there is no something like fetcher can i remove it?

**Comment by BeepIsla** [comment]
Don't use `AUTO` in your config and it won't use fetcher.

**Comment by Pecus35** [comment]
okay thanks

**Comment by Pecus35** [comment]
and can i change the serverid at the cooldown?

**Comment by BeepIsla** [comment]
What do you mean? Any changes to your config will require a full restart.
