### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by zuzuman2** [BeepIsla/csgo-commend-bot#532]
**Detailed question description**
I am getting this error roughly 5 times every 20 tries. I beleve it's because of my internet connection.

 [eilonlav] Failed to login and has been marked as invalid (20/20) {
  name: 'Error',
  message: 'GC connection timeout - Hello',
  stack: 'Error: GC connection timeout - Hello\n' +
    '    at SteamUser.loggedOn (C:\\COMMEND_BOT\\helpers\\account.js:131:14)'

**Config**
```
{
	"commend": {
		"friendly": 750,
		"teaching": 750,
		"leader": 750
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"fetcher": {
		"username": "Account",
		"password": "Password",
		"sharedSecret": "",
		"maxTries": 10,
		"tryDelay": 2500,
		"askSteamGuard": true
	},
	"proxy": {
		"enabled": false,
		"file": "ss.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "http://steamcommunity.com/profiles/76561197962539771",
	"serverID": "185.93.71.241:12600",
	"matchID": "0",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"showCommends": false,
	"autoReportOnMatchEnd": false,
	"switchServerAfterChunks": 5,
	"steamWebAPIKey": "XXX",
	"disableUpdateCheck": false
}

**Version**
- NodeJS: v12.18.2
- Script version: latest

**Comment by BeepIsla** [comment]
Account logged onto Steam but failed to establish connected to the CSGO network. Its very likely your internet or Steam/CSGO having issues. There is nothing more to say to this.
