### ISSUE TITLE
Error: InvalidPassword , and big list of stuff i don't know

### ISSUE THREAD

**Issue by JamesGordan11** [BeepIsla/csgo-commend-bot#534]
![issue](https://user-images.githubusercontent.com/62112046/87851901-25816080-c8f5-11ea-8542-9d56b966701f.PNG)
![issue1](https://user-images.githubusercontent.com/62112046/87851903-26b28d80-c8f5-11ea-8c88-83f0ba4b4013.PNG)
![issue2](https://user-images.githubusercontent.com/62112046/87851905-274b2400-c8f5-11ea-9a26-86f0e6e0fe3a.PNG)
i think the problem is from the setup , cause when i type npm install it says " look at ss"
and when i type npm ci same issue " look at ss"

My 394 Steam acc are made by me and 100% working so its 90% problem with the setup

pls HELP and thanks

**Comment by BeepIsla** [comment]
Follow the issue template. What is your config?

**Comment by JamesGordan11** [comment]
> Follow the issue template. What is your config?

i am using default config i only removed the report lines , is the setup even install successfully as shown in ss ? 
![Uploading config.PNG…]()

**Comment by JamesGordan11** [comment]
![config](https://user-images.githubusercontent.com/62112046/87852070-de946a80-c8f6-11ea-834f-1d6538b4acc0.PNG)

**Comment by BeepIsla** [comment]
You are trying to use the fetcher without providing one. Read the README.

Either stop trying to use the fetcher by filling in all `auto`'s manually or generate an account and put it in the fetcher section of your config.
