### ISSUE TITLE
Error: GC connection timeout - Hello

### ISSUE THREAD

**Issue by alioan** [BeepIsla/csgo-commend-bot#535]
this is how my config looks like(also have a valid apy key). However i keep getting this error and i have troubles in understanding what does it truly mean.
![image](https://user-images.githubusercontent.com/63473026/87854223-1ca28600-c919-11ea-99d0-3d2889864dd1.png)

**Comment by BeepIsla** [comment]
Read the README.

You are trying to use a fetcher without providing one. Either stop using `auto` or enter a bot account in the fetcher section of your config.

**Comment by alioan** [comment]
i saw what i was doing wrong thx
