### ISSUE TITLE
TypeError: Cannot read property 'k_EMsgGCClientHello' of undefined

### ISSUE THREAD

**Issue by JamesGordan11** [BeepIsla/csgo-commend-bot#538]
i am using the latest version , the commend bot was working fine
![error](https://user-images.githubusercontent.com/62112046/87887488-a50a4f00-ca1d-11ea-9f38-8c0b3f01d099.PNG)

**Comment by BeepIsla** [comment]
Delete protobufs folder, try again

**Comment by JamesGordan11** [comment]
never mind the new config.json was the problem ,
