### ISSUE TITLE
Commend Bot issue

### ISSUE THREAD

**Issue by Captain1997** [BeepIsla/csgo-commend-bot#539]
While I run node index.js  for this file   <<https://github.com/BeepIsla/csgo-commend-bot >> I get an error like 
TypeError: Cannot read property 'toUpperCase' of undefined
    at C:\Users\Administrator\Desktop\csgo-commend-bot-master\index.js:276:23 Promise {
  <rejected> TypeError: Cannot read property 'toUpperCase' of undefined
      at C:\Users\Administrator\Desktop\csgo-commend-bot-master\index.js:276:23

**Comment by BeepIsla** [comment]
Fix your config, there are some values missing. Do not delete anything from it.
