### ISSUE TITLE
Help me plz :)

### ISSUE THREAD

**Issue by leoaslan0** [BeepIsla/csgo-commend-bot#542]
![help m](https://user-images.githubusercontent.com/68650899/88186329-b762d380-cc3d-11ea-98f5-ab5a01895b5d.PNG)

**Comment by BeepIsla** [comment]
There is nothing wrong here

**Comment by leoaslan0** [comment]
waiting 30000000ms what ?

**Comment by RoyalBaron** [comment]
you have to wait 5 minutes to receive another 20 commends, it's valve limit
