### ISSUE TITLE
pomocy error

### ISSUE THREAD

**Issue by foreverhappy123** [BeepIsla/csgo-commend-bot#543]
![pomocy error](https://user-images.githubusercontent.com/68666474/88229789-a6cc5080-cc71-11ea-9797-537f525e127c.png)
@BeepIsla proszę o pomoc

**Comment by BeepIsla** [comment]
Read the README.

NodeJS V12 not V14. Install the correct version.

**Comment by foreverhappy123** [comment]
thx
