### ISSUE TITLE
Failed to send message: Timeout

### ISSUE THREAD

**Issue by Noksiowski** [BeepIsla/csgo-commend-bot#544]
Fresh config, changed only target, matchid and serverid are on auto, changed api key to mine, 
Both reports and commends: 
![image](https://user-images.githubusercontent.com/57946555/88230240-55709100-cc72-11ea-9d57-544a796cb98b.png)
and then
![image](https://user-images.githubusercontent.com/57946555/88230255-5a354500-cc72-11ea-959e-fdc511bbcca7.png)
Same for reporting and commending. Ideas?

**Comment by BeepIsla** [comment]
You cannot use this on live matchmaking games. Casual modes or community servers only. For reporting you can set `autoReportOnMatchEnd` to `true` to automatically report as soon as the match ends at which point it will work.
