### ISSUE TITLE
kolejna pomoc sorki nie ogarniam

### ISSUE THREAD

**Issue by foreverhappy123** [BeepIsla/csgo-commend-bot#545]
![bład123](https://user-images.githubusercontent.com/68666474/88231724-f6f8e200-cc74-11ea-86ee-8c38881ed89a.png)
@BeepIsla proszę o pomoc

**Comment by BeepIsla** [comment]
What does `node -v` output?

**Comment by foreverhappy123** [comment]
no node-v12.9.1-x64.msi

**Comment by BeepIsla** [comment]
Install it.

**Comment by foreverhappy123** [comment]
ok narazie jest dobrze ale jeszcze nie zamykaj tematu proszę :D

**Comment by foreverhappy123** [comment]
wszystko było dobrze zainstalowałem noda dodalem 111kont a jak napisalem node.js to znowu ten sam problem
![123456789](https://user-images.githubusercontent.com/68666474/88234124-d0d54100-cc78-11ea-85cd-d546cd7d1c70.png)

**Comment by foreverhappy123** [comment]
@BeepIsla jakbym znowu nie miał zainstalowanego noda

**Comment by BeepIsla** [comment]
Where in the README does it say to type `node.js`? You must type `node index.js`

**Comment by foreverhappy123** [comment]
sorry im stupid przepraszam że tak truje dupe

**Comment by foreverhappy123** [comment]
![wercia](https://user-images.githubusercontent.com/68666474/88235051-59a0ac80-cc7a-11ea-9b6e-b67c32d5dcf2.png)

**Comment by foreverhappy123** [comment]
@BeepIsla ?

**Comment by BeepIsla** [comment]
Again: Read the README.

You need to put a bot account in the `fetcher` section of your config.

**Comment by foreverhappy123** [comment]
jak to zrobić?? @BeepIsla

**Comment by BeepIsla** [comment]
Replace `Account` and `Password` in your config with a bot account.

**Comment by foreverhappy123** [comment]
ale ja mam takich kont 111

**Comment by BeepIsla** [comment]
No, one. Make a new one, generate an account, use a one account for it.

**Comment by foreverhappy123** [comment]
![image](https://user-images.githubusercontent.com/68666474/88236448-5824b380-cc7d-11ea-9518-8603b0587055.png)

**Comment by foreverhappy123** [comment]
where i edit serwerid?

**Comment by BeepIsla** [comment]
Just connect to a community server or Valve deathmatch, it will automatically find serverid

**Comment by foreverhappy123** [comment]
dziękuje ci bardzo wszystko działa możesz już zamknąć temat jeszcze raz dzięki
trzymaj sie

**Comment by BeepIsla** [comment]
Also: I don't speak Polish and this is an English repository.
