### ISSUE TITLE
[Suggestion] New shipping type

### ISSUE THREAD

**Issue by FPSGuilherme** [BeepIsla/csgo-commend-bot#548]
**Detailed description of the suggestion**
I would like to suggest a change in the system for sending commends.

As many accounts stop working, it would be something more useful than the amount of praise that is set in the config were the ones that would actually go to the player's account, not counting those that went wrong.

Example: In my config I put to send 40 commends to a player, after I started the bot, 10 commends were sent and 10 failed, so the bot should be trying to send until the 40 commends set in the config

Sorry if you got a little confused

**Comment by BeepIsla** [comment]
You can see how many failed once it finished, just edit your config amount and start the bot again.
