### ISSUE TITLE
help retry

### ISSUE THREAD

**Issue by ByLaurant** [BeepIsla/csgo-commend-bot#551]
![image](https://user-images.githubusercontent.com/65298315/88468383-6ed04200-ceeb-11ea-83a8-9fbcb31721ce.png)

I delete the protobufs folder, but it occurs again and gives this error.

**Comment by BeepIsla** [comment]
You can reply to closed threads... you don't have to open a new one.

What is your config?

**Comment by ByLaurant** [comment]
![image](https://user-images.githubusercontent.com/65298315/88468405-c40c5380-ceeb-11ea-861e-8da5c405b6ca.png)

**Comment by BeepIsla** [comment]
You just shower your username, password AND API key to everyone. You should really quickly go and change them.

---

Does your folder structure look something like this?

- `config.json`
- `index.js`
- `protobufs`
  - `csgo`
    - `base_gcmessages.proto`
    - `cstrike15_gcmessages.proto`
  - `steam`
    - `steammessages_base.proto`
    - `steammessages_clientserver_2.proto`

**Comment by ByLaurant** [comment]
![image](https://user-images.githubusercontent.com/65298315/88468440-73e1c100-ceec-11ea-8cfa-264bc2627593.png)
in this way

**Comment by BeepIsla** [comment]
This does not answer my question. Do you have these folders/files?

- `protobufs`
  - `csgo`
    - `base_gcmessages.proto`
    - `cstrike15_gcmessages.proto`
  - `steam`
    - `steammessages_base.proto`
    - `steammessages_clientserver_2.proto`

**Comment by ByLaurant** [comment]
yes

**Comment by ByLaurant** [comment]
but there are other files, not just what you wrote

**Comment by ByLaurant** [comment]
ok ok working right now thx

**Comment by ByLaurant** [comment]
<3
