### ISSUE TITLE
question abuot cmmond bot 

### ISSUE THREAD

**Issue by medhat8989** [BeepIsla/csgo-commend-bot#552]
**Detailed question description**
[abbitsw2chiarugi27918] Requires a Steam Guard code and has been marked as invalid (1/20) {
  name: 'Error',

plz brother i need y r help why i get this problem plz help me ..thank u brother for this fantastic script

**Comment by BeepIsla** [comment]
Your bot has Steam Guard enabled, disable Steam Guard on it.

**Comment by medhat8989** [comment]
how i can do that brother plz ?

**Comment by medhat8989** [comment]
and i dont have accuont in this name abbitsw2chiarugi27918 in my list of accuont so i dont know the password in this accuont

**Comment by BeepIsla** [comment]
The database stores all passwords. Just download [SQLite Browser](https://sqlitebrowser.org/), open up `accounts.sqlite`, go to `data` and there are all passwords listed in plain text.

[Just disable Steam Guard like normal](https://support.steampowered.com/kb_article.php?ref=8625-wrah-9030).

**Comment by medhat8989** [comment]
ok brother i want tell u did great job i love u brother and i love  u r job keep going brother ..i just have one more question plz when i put file for proxy like this 
169.57.157.148:25
20.43.156.109:80
20.43.156.27:80
52.191.103.11:3128
8.210.111.210:80
81.201.60.130:80
he say to me alwys abbitsw2chiarugi27918 error to coonect proxy i dont know why i use ip proxy free

**Comment by BeepIsla** [comment]
Valve blocks proxies. You need to find good paid proxies which are not blocked by Valve.

**Comment by medhat8989** [comment]
umm that why the motherfuckers ban all  free ip proxy :DD .. but how can they differentiate between free ip proxy and paid ip proxy?

**Comment by BeepIsla** [comment]
They don't. They ban every proxy.

**Comment by medhat8989** [comment]
how they ban every proxy and if i paid for proxiex i will not ban !

**Comment by BeepIsla** [comment]
Google "How to detect proxies". There are entire services dedicated to detecting and blocking proxies.

**Comment by medhat8989** [comment]
and i try to cmmond 50 without eny proxy and its worked with my ip normal so why i shold need proxy?

**Comment by BeepIsla** [comment]
There is an IP limit.

**Comment by medhat8989** [comment]
how much ?

**Comment by medhat8989** [comment]
ah ok

**Comment by medhat8989** [comment]
thank u agine brother for y r time i love brothe i wich u all the best i sware :3  and so sorry for my english
