### ISSUE TITLE
what's wrong？

### ISSUE THREAD

**Issue by ricardosxx** [BeepIsla/csgo-commend-bot#555]
I tried to run in SERVER mode, but he kept telling me that the target was not in the SERVER. How should I solve it?

**Comment by BeepIsla** [comment]
Config? What server are you on? Valve Competitive, Valve Deathmatch, Community Server, Workshop, Offline with bots?

**Comment by ricardosxx** [comment]
I tried the Valve Competitive and Community Server
They're all the same

**Comment by ricardosxx** [comment]
They'll try 11 and fail 11 times

**Comment by BeepIsla** [comment]
You ignored my first question:

> Config?

Censor important information like account details and API key.

**Comment by ricardosxx** [comment]
![捕获](https://user-images.githubusercontent.com/62421009/88474687-a676d280-cf5b-11ea-87d9-3ee78cba69f8.PNG)

**Comment by BeepIsla** [comment]
You are using `auto` without providing a fetcher account. Generate an account and put it in the `fetcher` section of your config.

**Comment by ricardosxx** [comment]
I put in an account and he started to tell me that I didn't exist on the server

**Comment by BeepIsla** [comment]
1. Are you sure you put it in as `fetcher` and not as `account`?

2. Enter `cl_join_advertise 2` in your console in CSGO

3. Try Valve Deathmatch and Community Server

**Comment by ricardosxx** [comment]
yse it's fetcher
ok i'll try

**Comment by ricardosxx** [comment]
I switched to login mode and praised it for being valid but my account didn't receive it, which is strange

**Comment by BeepIsla** [comment]
#473
