### ISSUE TITLE
question abuot cmmond bot 2

### ISSUE THREAD

**Issue by medhat8989** [BeepIsla/csgo-commend-bot#556]
hello brother agine sorry Sorry for bothering you again.. i just i need to know after yur permission ofcuorse how its work report hacker i need to know the best way ..i tell u what i do i dont know its good or baad in game i press alt and tap and i open the program before ofcuorse i put he is url profile in config and i open and i start to ropert him its work for me i mean Sending reports is working its okay ..its this way is good or bad?  and i want show u my config plz like this u can tell me if good or bad here is my config 
{
	"commend": {
		"friendly": 50,
		"teaching": 50,
		"leader": 50
	},
	"report": {
		"aimbot": 20,
		"wallhack": 20,
		"speedhack": 20,
		"teamharm": 20,
		"abusive": 20
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"fetcher": {
		"username": "i have ",
		"password": "i have ",
		"sharedSecret": "",
		"maxTries": 10,
		"tryDelay": 2500,
		"askSteamGuard": true
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "REPORT",
	"method": "SERVER",
	"target": "https://steamcommunity.com/profiles/76561198432079827/",
	"serverID": "auto",
	"matchID": "0",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"showCommends": false,
	"autoReportOnMatchEnd": false,
	"switchServerAfterChunks": 5,
	"steamWebAPIKey": "i have webapiky :)",
	"disableUpdateCheck": false
}
so brother the way i do for report its good or bad tell me the best way and thank u agine brother:3

**Comment by BeepIsla** [comment]
There is no good or bad method, if it says successful then that's it.

**Comment by medhat8989** [comment]
yeh its send normal no problem

**Comment by medhat8989** [comment]
i ask u becuse i see yur comment   say  never report in game but its work in game

**Comment by BeepIsla** [comment]
I don't say never, I say it doesn't work. And it did not work several weeks ago.

**Comment by medhat8989** [comment]
ok thank u brother
