### ISSUE TITLE
GC connection timeout - Hello     at SteamUser.loggedOn

### ISSUE THREAD

**Issue by martinovjulian** [BeepIsla/csgo-commend-bot#559]
I get this error when trying to use the login method of the commend bot. 
config has my username and password and no shared secret. 
fetcher area has been left as is according to the readme. 
method type switched to login.
target switched to my steam profile ID(steamcommunity.id.com/id/"idhere"/)
protocol is on auto
steamwebAPIKey is my web api key. 
any idea why this is happening?

**Comment by BeepIsla** [comment]
Exit CSGO and don't open it.

**Comment by martinovjulian** [comment]
Not enough accounts available, got 0/13.
Now i get this error^^. generated a bunch of fresh accounts with cathook and it says it can't get any of them? however when i use the databasemanager to find accounts that don't work it says that they all should work?
edit* upon closer inspection, the account generation failed apparently. gotta find some accounts to use

**Comment by BeepIsla** [comment]
they are on cooldown or already commended you, just wait or modify the cooldown value in your config if you think they are on cooldown
