### ISSUE TITLE
Hello , any one here is kind enough to share commend Accounts, i will do to

### ISSUE THREAD

**Issue by JamesGordan11** [BeepIsla/csgo-commend-bot#560]
Creating account is easy but it takes alot of time , i found couple of sites that creat accounts but you need proxies and alot methods (not free)

any ppl kind enough to share there commend accounts with me , i  will share mine as well no worries to help each other

**Comment by BeepIsla** [comment]
This is not a platform to ask for accounts.

**Comment by 2kFlow** [comment]
@JamesGordan11 my discord is Flow#0058 dm me we could interchange our steam accounts
