### ISSUE TITLE
Hello im kinda new and could u tell me what or which bot account to add at the fetcher section , im kinda new pls

### ISSUE THREAD

**Issue by 2kFlow** [BeepIsla/csgo-commend-bot#562]
**Detailed question description**
A clear and concise description of your question.

**Config**
```
Your "config.json" - Censor your API Key and account details
```

**Version**
- NodeJS: `vXX.XX.X` (You can find this using `node -v`)
- Script version: `X.X.X` (You can find this in **your** `package.json` file under `version`)

**Comment by BeepIsla** [comment]
Why open a new issue? Just stay in #561?

I just told you what to do, just generate an account on [accgen.cathook.club](https://accgen.cathook.club/) take the username and password and put it in your config.

**Comment by 2kFlow** [comment]
![image](https://user-images.githubusercontent.com/68917063/88708593-839e1700-d131-11ea-86f8-d604ce026d4f.png)
what now?

**Comment by BeepIsla** [comment]
Join a casual or deathmatch server

**Comment by 2kFlow** [comment]
> Join a casual or deathmatch server

ayyo ty man god bless
