### ISSUE TITLE
about report plz

### ISSUE THREAD

**Issue by medhatmo** [BeepIsla/csgo-commend-bot#563]
![Screenshot (13)](https://user-images.githubusercontent.com/68933610/88759309-c7f9d900-d16a-11ea-918d-5b5f4abf343a.png)
![Screenshot (14)](https://user-images.githubusercontent.com/68933610/88759316-c9c39c80-d16a-11ea-86dc-14eab8a2b5d3.png)
plz i need help i did report end game and still not working i dont know what i shuold do with this problem plz guyes help me and this my config here {
	"commend": {
		"friendly": 30,
		"teaching": 30,
		"leader": 30
	},
	"report": {
		"aimbot": 50,
		"wallhack": 50,
		"speedhack": 50,
		"teamharm":50,
		"abusive": 50
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"fetcher": {      
		"username": "erhehehdhdfht",
		"password": "hfdhdhdhdhdhd",
		"sharedSecret": "",
		"maxTries": 10,
		"tryDelay": 2500,
		"askSteamGuard": true
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "REPORT",
	"method": "SERVER",
	"target": "https://steamcommunity.com/profiles/76561199065850527/",
	"serverID": "auto",
	"matchID": "auto",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"showCommends": false,
	"autoReportOnMatchEnd": true,
	"switchServerAfterChunks": 5,
	"steamWebAPIKey": "fdhdhddddhhdhdhdhdhdhdhdhdhdhd",
	"disableUpdateCheck": false
}

**Comment by BeepIsla** [comment]
They left too early

**Comment by karutaXkun** [comment]
Same error i did it in mid match

**Comment by Borlax2** [comment]
By looking at your matchID, the player you are trying to report is NOT in a matchmaking game!

**Comment by karutaXkun** [comment]
Then what about my match, I did it in mid of the match and still got timeout error? (Sry I don't have screenshots came post issue and saw this related thread)

**Comment by Borlax2** [comment]
as beeplsla said, if the target left the match too early, he won't get reported, this is how cheaters are bypassing some known reportbots services..

**Comment by medhatmo** [comment]
> 
> 
> By looking at your matchID, the player you are trying to report is NOT in a matchmaking game!

how is that brother i was play with him in the same match id and i did try a lot with a lot hacker in the end gmae and i get the same error brother i dont know man what i can do ..can i talk with u in discord my is medhat2020#6917   plzz

**Comment by BeepIsla** [comment]
You cannot use this mid match. You have to do it at *the end* and its entirely possible they just left the game too early.
