### ISSUE TITLE
Could you use a 1500+ accounts text file or is there a account limitation?

### ISSUE THREAD

**Issue by 2kFlow** [BeepIsla/csgo-commend-bot#564]
**Detailed question description**
A clear and concise description of your question.

**Config**
```
Your "config.json" - Censor your API Key and account details
```

**Version**
- NodeJS: `vXX.XX.X` (You can find this using `node -v`)
- Script version: `X.X.X` (You can find this in **your** `package.json` file under `version`)

**Comment by BeepIsla** [comment]
No limits in terms of how many accounts you can have
