### ISSUE TITLE
TypeError: Cannot read property 'k_EMsgGCClientHello' of undefined

### ISSUE THREAD

**Issue by 2kFlow** [BeepIsla/csgo-commend-bot#565]
**Detailed question description**
A clear and concise description of your question.
![image](https://user-images.githubusercontent.com/68917063/88773911-69e7e880-d1a0-11ea-9863-0dfb33a7d7fb.png)

**Config**
```
Your "config.json" - Censor your API Key and account details
```

**Version**
- NodeJS: `vXX.XX.X` (You can find this using `node -v`)
- Script version: `X.X.X` (You can find this in **your** `package.json` file under `version`)
![image](https://user-images.githubusercontent.com/68917063/88773919-6b191580-d1a0-11ea-8785-55e24339554e.png)
![image](https://user-images.githubusercontent.com/68917063/88773923-6ce2d900-d1a0-11ea-837a-e18a9c3d549a.png)

**Comment by BeepIsla** [comment]
Config? Try deleting your protobufs folder

**Comment by 2kFlow** [comment]
> Config? Try deleting your protobufs folder

Umm that error is actually fine now , i just re enetered few values . I have a new error . it shows that the accounts need steam guard code . Though i generated these accounts from https://accgen.cathook.club/

.........................................................................................................................................................................................................................................................................

![image](https://user-images.githubusercontent.com/68917063/88787703-ee8f3280-d1b1-11ea-9e87-f091275f9a9d.png)


.........................................................................................................................................................................................................................................................................

Config : 
 {
	"commend": {
		"friendly": 13,
		"teaching": 13,
		"leader": 13
	
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"fetcher": {
		"username": "ryxs15099980morita",
		"password": "ZGX2EB17XNW5887",
		"sharedSecret": "",
		"maxTries": 10,
		"tryDelay": 2500,
		"askSteamGuard": true
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/profiles/76561199046377250/",
	"serverID": "auto",
	"matchID": "0",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"showCommends": false,
	"autoReportOnMatchEnd": false,
	"switchServerAfterChunks": 5,
	"protocol": "Auto",
	"steamWebAPIKey": "E94EA950E399D500dawdawd0B7D990BF0D",
	"disableUpdateCheck": false
}

**Comment by BeepIsla** [comment]
1. You leaked your fetcher username & password, make a new one

2. You leaked your API key, make a new one

3. This is unrelated to this script, Steam says the account requires Steam Guard. So disable Steam Guard or make a new account instead
