### ISSUE TITLE
i need explyien plz 

### ISSUE THREAD

**Issue by medhatmo** [BeepIsla/csgo-commend-bot#567]
Checking for new update...
 Up to date!
 Checking protobufs...
 Found protobufs
 Opening database...
 There are a total of 45 operational accounts
 Parsing target account...
 Chunking 40 accounts into groups of 20...
 Parsing server input
 Parsed server input to ### 90137521546877955
 Logging in on chunk 1/2
 [Azthaiv] Logging into Steam
 [B1988923] Logging into Steam
 [BAO2006HKHK] Logging into Steam
 [BAYLOPS1] Logging into Steam
 [BBsVader] Logging into Steam
 [BEEZZUES] Logging into Steam

when i try to report i put the server id in my config  but her show me anther server input different why?it this right to show me anther server id !!?
my config 
{
	"commend": {
		"friendly": 5,
		"teaching": 10,
		"leader": 15
	},
	"report": {
		"aimbot": 30,
		"wallhack": 30,
		"speedhack": 30,
		"teamharm": 30,
		"abusive": 40
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"fetcher": {
		"username": "6666666666666644446",
		"password": "3O4546464644y4y4y4y4928",
		"sharedSecret": "",
		"maxTries": 10,
		"tryDelay": 2500,
		"askSteamGuard": true
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "REPORT",
	"method": "SERVER",
	"target": "http://steamcommunity.com/profiles/76561199072781182",
	"serverID": "[A:1:683432963:15257]",
	"matchID": "0",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"showCommends": false,
	"autoReportOnMatchEnd": false,
	"switchServerAfterChunks": 5,
	"protocol": "Auto",
	"steamWebAPIKey": "342242432222f2f2f2",
	"disableUpdateCheck": false
}

**Comment by BeepIsla** [comment]
Its the same server. They are just displayed in different formats.
