### ISSUE TITLE
'GC connection timeout - Hello',

### ISSUE THREAD

**Issue by 2kFlow** [BeepIsla/csgo-commend-bot#568]
config :  {
	"commend": {
		"friendly": 1750,
		"teaching": 1750,
		"leader": 1750
	
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"fetcher": {
		"username": "ryxs15********ita",
		"password": "ZGX2*******5887",
		"sharedSecret": "",
		"maxTries": 10,
		"tryDelay": 2500,
		"askSteamGuard": true
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/profiles/7656119907803****/",
	"serverID": "auto",
	"matchID": "0",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"showCommends": false,
	"autoReportOnMatchEnd": false,
	"switchServerAfterChunks": 5,
	"protocol": "Auto",
	"steamWebAPIKey": "E94EA950E399D500693D50B7********",
	"disableUpdateCheck": false
}

**Comment by BeepIsla** [comment]
No idea where it happens because you never show the actual error and where it is but basically just something logged into Steam but failed to connect to the CSGO network. All I can say.
