### ISSUE TITLE
Not receiving commends ingame

### ISSUE THREAD

**Issue by 2kFlow** [BeepIsla/csgo-commend-bot#569]
Ingame in the chat box it shows congratulations , You've received a commend! . But when i click on my profile the commends remain the same . Pls help 
cfg :
{
	"commend": {
		"friendly": 40,
		"teaching": 40,
		"leader": 40
	
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"fetcher": {
		"username": "yran**********ad",
		"password": "***************",
		"sharedSecret": "",
		"maxTries": 10,
		"tryDelay": 2500,
		"askSteamGuard": true
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/profiles/7****************3/",
	"serverID": "auto",
	"matchID": "0",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"showCommends": false,
	"autoReportOnMatchEnd": false,
	"switchServerAfterChunks": 5,
	"protocol": "Auto",
	"steamWebAPIKey": "E9*********************D",
	"disableUpdateCheck": false
}

**Comment by BeepIsla** [comment]
Duplicate #473
