### ISSUE TITLE
"Failed to log in within given 60000ms" I want to increase this num

### ISSUE THREAD

**Issue by KillingNights** [BeepIsla/csgo-commend-bot#571]
Sorry to trouble you.My vps net is so poor. How can i increase this number.Wich js control it.

**Comment by BeepIsla** [comment]
You can't. If you take over a minute to log into Steam I doubt its the connection and rather just something being wrong. What is your config?

**Comment by KillingNights** [comment]
Okey.I think my config is all right. I set 20 perchunks. The Front of 20(just like 10) is log in successful,but the others is "over time".

**Comment by BeepIsla** [comment]
Then I can't help you.

**Comment by KillingNights** [comment]
Thank you very much.I will try to set 10perchunks and decrease the number of waiting.
