### ISSUE TITLE
Failed to send message: Timeout

### ISSUE THREAD

**Issue by Waller1337** [BeepIsla/csgo-commend-bot#573]
Login method still working.
CONFIG:
{
"commend": {
"friendly": 40,
"teaching": 40,
"leader": 40
},
"report": {
"aimbot": 0,
"wallhack": 0,
"speedhack": 0,
"teamharm": 0,
"abusive": 0
},
"account": {
"username": "",
"password": "",
"sharedSecret": ""
},
"fetcher": {
"username": "",
"password": "",
"sharedSecret": "",
"maxTries": 0,
"tryDelay": 2500,
"askSteamGuard": true
},
"proxy": {
"enabled": false,
"file": "proxies.txt",
"switchProxyEveryXaccounts": 20
},
"type": "COMMEND",
"method": "SERVER",
"target": "XXX",
"serverID": "[A:1:XXX:XXXX]",
"matchID": "0",
"perChunk": 20,
"betweenChunks": 300000,
"cooldown": 28800000,
"showCommends": false,
"switchServerAfterChunks": 5,
"steamWebAPIKey": "XXXX",
"disableUpdateCheck": false
}
![image](https://user-images.githubusercontent.com/16866230/89388522-715d4380-d704-11ea-8e62-0e1bc89a69b8.png)

**Comment by BeepIsla** [comment]
What server is your target on? Valve Matchmaking? Deathmatch? Community?

**Comment by Waller1337** [comment]
In the server method, I used a different account and was on the workhop map

**Comment by BeepIsla** [comment]
Try a community server or Valve Deathmatch instead

**Comment by Waller1337** [comment]
I'll test and let you know

**Comment by Waller1337** [comment]
Error disappeared

**Comment by Waller1337** [comment]
on dm working again

**Comment by BeepIsla** [comment]
Problem solved, just don't use workshop/offline with bots
