### ISSUE TITLE
No way to bypass 20 commends per 5 minutes even with proxies.

### ISSUE THREAD

**Issue by Noksiowski** [BeepIsla/csgo-commend-bot#575]
Seems like something changed, tried even manualy from 2 computers with different ip's and different networks.
Sent 20 commends from pc #1, 20 successfull
Sent 20 commends from pc #2, 20 failed.

After 5-10 minutes i could success on #2 and failed on #1

Seems like 20 commends limitation is not based on sender ip adress but reciver account now, and nobody (even legit!!) can recive more than 20 commends per 5 minutes :(

**Comment by ghost** [comment]
Everyone knows that, so this is not an issue?

**Comment by Noksiowski** [comment]
Not really? This was the point of proxy suppot.
Some time ago i was able to send 800 commends in 5 minutes no problem. Just required me to use paid residental proxies.
Now even if i dont use proxies but 2 sepparate computers with 2 networks, 20 commends max.
¯\_(ツ)_/¯
