### ISSUE TITLE
What happened?

### ISSUE THREAD

**Issue by Seuz228** [BeepIsla/csgo-commend-bot#576]
![_n5scsT_7UQ](https://user-images.githubusercontent.com/57406186/89549469-04839f80-d811-11ea-9a20-f51561a91336.jpg)
**Detailed question description**
A clear and concise description of your question.

**Config**
```
Your "config.json" - Censor your API Key and account details
```

**Version**
- NodeJS: `v12. 18.4` (You can find this using `node -v`)
- Script version: `2.10.0` (You can find this in **your** `package.json` file under `version`)

**Comment by BeepIsla** [comment]
Read the error. You attempted to log into too many accounts and Steam is now blocking you from logging into any further accounts. To fix this either use a **good** proxy or wait 30 minutes. If you try to login before the 30 minutes expire the time will reset and you have to wait 30 minutes again.
