### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by crazy-dogman** [BeepIsla/csgo-commend-bot#579]
Checking for new update...
 Up to date!
 Checking protobufs...
 Found protobufs
 Opening database...
 There are a total of 8 operational accounts
 Parsing target account...
TypeError: Cannot read property 'switchProxyEveryXaccounts' of undefined
    at C:\Users\Administrator\Downloads\csgo-commend-bot-master (1)\csgo-commend-bot-master\index.js:250:35 Promise {
  <rejected> TypeError: Cannot read property 'switchProxyEveryXaccounts' of undefined
      at C:\Users\Administrator\Downloads\csgo-commend-bot-master (1)\csgo-commend-bot-master\index.js:250:35
}
[config.txt](https://github.com/BeepIsla/csgo-commend-bot/files/5048101/config.txt)

**Comment by BeepIsla** [comment]
1. You just leaked your Steam Web API key to everyone - **Make a new one**

2. Your config is all over the place, make a new one from the example config. Do not delete anything.

**Comment by crazy-dogman** [comment]
wow
thank！
