### ISSUE TITLE
report bot 

### ISSUE THREAD

**Issue by crazy-dogman** [BeepIsla/csgo-commend-bot#582]
Contact: Emlin#0505

 Update check skipped
 Checking protobufs...
 Found protobufs
 Opening database...
 There are a total of 307 operational accounts
 Parsing target account...
 Chunking 100 accounts into groups of 20...
 Parsing server input
 Logging into fetcher account...
 Trying to fetch target 10 times with a delay of 2500ms
 Target is likely not in a server or in a full server // Failed to find connect bytes
 Found target on Valve server 90137830021641227 after 1 try (3429812081296146493)
 Waiting until match is over before reporting...
 Match has ended, starting report bot...
 Logging in on chunk 1/5
 [gghvj021] Logging into Steam
 [gidtv143] Logging into Steam
 [gkbfp141] Logging into Steam
 [grjih961] Logging into Steam
 [gujju814] Logging into Steam
 [gvfak983] Logging into Steam
 [gyote315] Logging into Steam
 [hccom063] Logging into Steam
 [hgrvj589] Logging into Steam
 [hhcfg947] Logging into Steam
 [hjfka581] Logging into Steam
 [hnlrm904] Logging into Steam
 [hnxzk044] Logging into Steam
 [hovus598] Logging into Steam
 [hrpba266] Logging into Steam
 [hvmym135] Logging into Steam
 [hwcgr734] Logging into Steam
 [hwqcn053] Logging into Steam
 [hyjzb267] Logging into Steam
 [ibiho375] Logging into Steam
 [hovus598] Logged onto Steam - GC Time: 2020-8-11 4:50:54 ├F10: PM┤
 [hovus598] Authenticated with target server with ticket 1697021292
 [hnxzk044] Logged onto Steam - GC Time: 2020-8-11 4:50:56 ├F10: PM┤
 [hjfka581] Logged onto Steam - GC Time: 2020-8-11 4:50:56 ├F10: PM┤
 [hnxzk044] Authenticated with target server with ticket 2083007348
 [hjfka581] Authenticated with target server with ticket 2175691711
 [grjih961] Logged onto Steam - GC Time: 2020-8-11 4:50:59 ├F10: PM┤
 [hvmym135] Logged onto Steam - GC Time: 2020-8-11 4:50:59 ├F10: PM┤
 [hwcgr734] Logged onto Steam - GC Time: 2020-8-11 4:50:59 ├F10: PM┤
 [gghvj021] Logged onto Steam - GC Time: 2020-8-11 4:51:00 ├F10: PM┤
 [grjih961] Authenticated with target server with ticket 4176901832
 [hvmym135] Authenticated with target server with ticket 1972698294
 [hyjzb267] Logged onto Steam - GC Time: 2020-8-11 4:51:00 ├F10: PM┤
 [hwcgr734] Authenticated with target server with ticket 2173181774
 [gkbfp141] Logged onto Steam - GC Time: 2020-8-11 4:51:00 ├F10: PM┤
 [hccom063] Logged onto Steam - GC Time: 2020-8-11 4:51:00 ├F10: PM┤
 [hhcfg947] Logged onto Steam - GC Time: 2020-8-11 4:51:01 ├F10: PM┤
 [ibiho375] Logged onto Steam - GC Time: 2020-8-11 4:51:00 ├F10: PM┤
 [gujju814] Logged onto Steam - GC Time: 2020-8-11 4:51:00 ├F10: PM┤
 [gvfak983] Logged onto Steam - GC Time: 2020-8-11 4:51:00 ├F10: PM┤
 [gidtv143] Logged onto Steam - GC Time: 2020-8-11 4:51:01 ├F10: PM┤
 [gyote315] Logged onto Steam - GC Time: 2020-8-11 4:51:00 ├F10: PM┤
 [hgrvj589] Logged onto Steam - GC Time: 2020-8-11 4:51:01 ├F10: PM┤
 [hnlrm904] Logged onto Steam - GC Time: 2020-8-11 4:51:01 ├F10: PM┤
 [gghvj021] Authenticated with target server with ticket 3052049810
 [hwqcn053] Logged onto Steam - GC Time: 2020-8-11 4:51:01 ├F10: PM┤
 [hrpba266] Logged onto Steam - GC Time: 2020-8-11 4:51:01 ├F10: PM┤
 [hccom063] Authenticated with target server with ticket 3666255914
 [hyjzb267] Authenticated with target server with ticket 1143851541
 [gkbfp141] Authenticated with target server with ticket 3463152735
 [hhcfg947] Authenticated with target server with ticket 541442749
 [gujju814] Authenticated with target server with ticket 758124761
 [ibiho375] Authenticated with target server with ticket 2398694309
 [gidtv143] Authenticated with target server with ticket 3975421677
 [hgrvj589] Authenticated with target server with ticket 3256147626
 [gvfak983] Authenticated with target server with ticket 2205907020
 [gyote315] Authenticated with target server with ticket 1897186096
 [hnlrm904] Authenticated with target server with ticket 2394571390
 [hwqcn053] Authenticated with target server with ticket 2072731355
 [hrpba266] Authenticated with target server with ticket 7817046
 [hovus598] Failed to report (1/20) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\Administrator\\Downloads\\csgo-commend-bot-master (1)\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
}
[config.txt](https://github.com/BeepIsla/csgo-commend-bot/files/5055932/config.txt)

**Comment by BeepIsla** [comment]
1. You just leaked your `fetcher` details to everyone

2. What server are you using? Valve Competitive, Deathmatch, Community Server?

**Comment by crazy-dogman** [comment]
Valve Competitive

**Comment by crazy-dogman** [comment]
official matchmaking

**Comment by BeepIsla** [comment]
You cannot report/commend bot during a live matchmaking game. Try doing it at the end of the match, if it still fails the target has left the server too early for it to work.
