### ISSUE TITLE
Reportbot Timeout error

### ISSUE THREAD

**Issue by ninjaibiss** [BeepIsla/csgo-commend-bot#584]
reportbot sometimes send mostly failed Autoreportonmatchend = true
proxy = no proxy (and i think it doesnt matter)
perchunk = 300ms

**Comment by BeepIsla** [comment]
Target left the server too early

**Comment by ninjaibiss** [comment]
wait so i can change the reports instead of 20 into like 100? and perchunkms 0? or is there any fix?

**Comment by ninjaibiss** [comment]
are maybe theres a fix

**Comment by BeepIsla** [comment]
If the target left too early there is nothing you can do, report botting is useless anyways.
