### ISSUE TITLE
Commandprompt/powershell

### ISSUE THREAD

**Issue by ninjaibiss** [BeepIsla/csgo-commend-bot#587]
Does disabling auto check updates will make reportbot faster

**Comment by Waller1337** [comment]
Try forever

**Comment by ninjaibiss** [comment]
no that wont work

**Comment by ninjaibiss** [comment]
and waller can i talk to you at discord or something

**Comment by BeepIsla** [comment]
> Does disabling auto check updates will make reportbot faster

Update check should not take longer than a second

**Comment by ninjaibiss** [comment]
What is protocol on config

**Comment by BeepIsla** [comment]
Read the README

> protocol `String`: Either `Auto`, `TCP`, `WebSocket`, or `WebCompatibility` - Specify the connection protocol to use for Steam

If this still doesn't help: There are two main ways of connecting to Steam, TCP with Steam's encryption or WebSocket. Some proxies do not allow direct TCP connections, instead they only allow for WebSocket connections as those are also used on websites. 99.99% of the time you can just leave it at default (`Auto`).
