### ISSUE TITLE
failed to commend timeout

### ISSUE THREAD

**Issue by Ties113** [BeepIsla/csgo-commend-bot#595]
When i activate node index it gives me this error 

Chunk 1/1 finished with 0 successful commends and 5 failed commends
 Finished all chunks with a total of 0 successful and 5 failed commends

[XDLvgDgMej4G] Failed to commend (5/5) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\Floris\\Desktop\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'
i think it got patched again

**Comment by BeepIsla** [comment]
Duplicate #593
