### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by forevergay** [BeepIsla/csgo-commend-bot#599]
I always have timeout.I used command bot 14 days ago.Of course one on ten is good but almoust always have timeout
**My Config**
"commend": {
		"friendly": 300,
		"teaching": 300,
		"leader": 300
	},
	"report": {
		"aimbot": 0,
		"wallhack": 0,
		"speedhack": 0,
		"teamharm": 0,
		"abusive": 0
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"fetcher": {
		"username": "urkeysa1albrecht105",
		"password": "QFANISKZP04Q198",
		"sharedSecret": "",
		"maxTries": 10,
		"tryDelay": 2500,
		"askSteamGuard": true
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/profiles/76561198827568336/",
	"serverID": "auto",
	"matchID": "0",
	"perChunk": 20,
	"betweenChunks": 30000,
	"cooldown": 200000,
	"showCommends": false,
	"autoReportOnMatchEnd": false,
	"switchServerAfterChunks": 5,
	"protocol": "Auto",
	"steamWebAPIKey": "BFF17A64DF1570C33B1C667E269B4018",
	"disableUpdateCheck": false

**Comment by BeepIsla** [comment]
You leaked your fetcher details and API key to everyone good job. Make a new API key and change password.

Next time read the pinned issue at the top: #593
