### ISSUE TITLE
I still have timeouts unchanged

### ISSUE THREAD

**Issue by forevergay** [BeepIsla/csgo-commend-bot#600]
I still have timeouts unchanged

A full error log or screenshot.
![image](https://user-images.githubusercontent.com/69930225/90693196-b2159a80-e276-11ea-9f12-9730d0cac0a3.png)

**Config**
"commend": {
		"friendly": 300,
		"teaching": 300,
		"leader": 300
	},
	"report": {
		"aimbot": 0,
		"wallhack": 0,
		"speedhack": 0,
		"teamharm": 0,
		"abusive": 0
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"fetcher": {
		"username": "bartoszek219",
		"password": "cycek219",
		"sharedSecret": "",
		"maxTries": 10,
		"tryDelay": 2500,
		"askSteamGuard": true
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/profiles/76561198393502959/",
	"serverID": "auto",
	"matchID": "0",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown":  28800000,
	"showCommends": false,
	"autoReportOnMatchEnd": false,
	"switchServerAfterChunks": 5,
	"protocol": "Auto",
	"steamWebAPIKey": "",
	"disableUpdateCheck": false
Your "config.json" - Censor your API Key and account details
```

**Version**
- NodeJS: `vXX.XX.X` (You can find this using `node -v`)
- Script version: `X.X.X` (You can find this in **your** `package.json` file under `version`)

**Additional information**
Add any other potentially useful information about your issue here.

**Comment by BeepIsla** [comment]
Why do you open another one AND leak your fetcher username & password again? I said read #593. Now read it again. Its patched. If you have information about a fix post it in that other issue thread.

**Comment by forevergay** [comment]
this is wrong fetcher account

**Comment by forevergay** [comment]
:D
