### ISSUE TITLE
[SUGGESTION] Commend Bot solution

### ISSUE THREAD

**Issue by kleptotic** [BeepIsla/csgo-commend-bot#606]
Well , im not an expert about this but for this i'ill be using some logic 
First , so what the current commend bot method is using is  Get all the accounts in the same server as the target and send proto calls to the server for commends/reports but it dosen't work for invaladating sessions 
though there is the fake statrak bot which use similar solution which is creating a server and manually adding players to it
which is working , so why not use  this method for the commend bot
For instance :  When  the bot joined the server instead sending fake incrementation for the statrak   Just commend
if this will not work then the problem is with the commend proto i think
if all of this is wrong then im sorry i told you im not an expert it's just an idea that i had in mind
Have a good day everyone

**Comment by BeepIsla** [comment]
That's already what I am doing in my rewrite. The client must be on the fake-server the entire time but after like a minute Steam invalidates the session, that is the problem. The bots and commending is not the issue. Also this would related to the commend bots being patched, those discussions go in #593

**Comment by alioan** [comment]
@BeepIsla is there a way in which u can make the bots actually join a real server(a workshop map for example), commend the target and tgen simply leave?

**Comment by BeepIsla** [comment]
Not worth it, possible, a friend is making a bot which can join a real server, but its just too much work for a commend bot.
