### ISSUE TITLE
timed out

### ISSUE THREAD

**Issue by LoostNT** [BeepIsla/csgo-commend-bot#608]
[swkwgzgsn15hq5o] Failed to commend (20/20) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\natha\\Desktop\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:549:17)\n' +
    '    at processTimers (internal/timers.js:492:7)'

how do I fix this?

**Comment by markito12** [comment]
#593

**Comment by denpro4321** [comment]
> [swkwgzgsn15hq5o] Failed to commend (20/20) {
> name: 'Error',
> message: 'Failed to send message: Timeout',
> stack: 'Error: Failed to send message: Timeout\n' +
> ' at Timeout._onTimeout (C:\Users\natha\Desktop\csgo-commend-bot-master\helpers\GameCoordinator.js:124:12)\n' +
> ' at listOnTimeout (internal/timers.js:549:17)\n' +
> ' at processTimers (internal/timers.js:492:7)'
> 
> how do I fix this?

useless issue, bot  patched. Isla working about that #593  u can check here..
