### ISSUE TITLE
Why doesn't it work for me?

### ISSUE THREAD

**Issue by botoboua** [BeepIsla/csgo-commend-bot#609]
**Detailed question description**
PS D:\joinclient\csgo-commend-bot-master> npm ci

> protobufjs@6.9.0 postinstall D:\joinclient\csgo-commend-bot-master\node_modules\protobufjs
> node scripts/postinstall

> sqlite3@4.2.0 install D:\joinclient\csgo-commend-bot-master\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.11.0
node-pre-gyp info using node@12.9.1 | win32 | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "D:\joinclient\csgo-commend-bot-master\node_modules\sqlite3\lib\binding\node-v72-win32-x64\node_sqlite3.node" (not found)
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v72-win32-x64.tar.gz
node-pre-gyp http 200 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v72-win32-x64.tar.gz
node-pre-gyp info install unpacking node-v72-win32-x64/node_sqlite3.node
node-pre-gyp info tarball done parsing tarball
[sqlite3] Success: "D:\joinclient\csgo-commend-bot-master\node_modules\sqlite3\lib\binding\node-v72-win32-x64\node_sqlite3.node" is installed via remote
node-pre-gyp info ok
added 219 packages in 6.198s
PS D:\joinclient\csgo-commend-bot-master> node databaseManager.js
Opening database...

? What would you like to do? Add account(s) to database
? What would you like to do? Import from username:password file
? Enter the name of the file you want to import w.txt
Successfully added 16 accounts. Duplicates have been ignored.

? What would you like to do? Exit
Safely closing database...
PS D:\joinclient\csgo-commend-bot-master> node index.js
 Checking for new update...
 Up to date!
 Checking protobufs...
 Failed to find protobufs, downloading and extracting...
 Opening database...
 There are a total of 16 operational accounts
 Parsing target account...
 Chunking 15 accounts into groups of 5...
 Parsing server input
 Parsed server input to 85568392923545616
 Logging in on chunk 1/3
 [myassountsg1] Logging into Steam
 [myassountsg10] Logging into Steam
 [myassountsg11] Logging into Steam
 [myassountsg12] Logging into Steam
 [myassountsg13] Logging into Steam
 [myassountsg1] Requires a Steam Guard code and has been marked as invalid (1/5) {
  name: 'Error',
  message: 'Steam Guard required',
  stack: 'Error: Steam Guard required\n' +
    '    at SteamUser.steamGuard (D:\\joinclient\\csgo-commend-bot-master\\helpers\\account.js:191:12)\n' +
    '    at SteamUser.emit (events.js:209:13)\n' +
    '    at SteamUser._steamGuardPrompt (D:\\joinclient\\csgo-commend-bot-master\\node_modules\\steam-user\\components\\logon.js:606:8)\n' +
    '    at SteamUser.<anonymous> (D:\\joinclient\\csgo-commend-bot-master\\node_modules\\steam-user\\components\\logon.js:475:9)\n' +
    '    at D:\\joinclient\\csgo-commend-bot-master\\node_modules\\steam-user\\components\\classes\\HandlerManager.js:37:12\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at HandlerManager.emit (D:\\joinclient\\csgo-commend-bot-master\\node_modules\\steam-user\\components\\classes\\HandlerManager.js:36:12)\n' +
    '    at SteamUser._handleMessage (D:\\joinclient\\csgo-commend-bot-master\\node_modules\\steam-user\\components\\messages.js:555:24)\n' +
    '    at SteamUser.Coordinator.steamUser._handleMessage (D:\\joinclient\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:43:19)\n' +
    '    at SteamUser._handleNetMessage (D:\\joinclient\\csgo-commend-bot-master\\node_modules\\steam-user\\components\\messages.js:490:7)\n' +
    '    at SteamUser.processMulti (D:\\joinclient\\csgo-commend-bot-master\\node_modules\\steam-user\\components\\messages.js:582:9)\n' +
    '    at SteamUser.<anonymous> (D:\\joinclient\\csgo-commend-bot-master\\node_modules\\steam-user\\components\\messages.js:576:16)\n' +
    '    at D:\\joinclient\\csgo-commend-bot-master\\node_modules\\steam-user\\components\\classes\\HandlerManager.js:37:12\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at HandlerManager.emit (D:\\joinclient\\csgo-commend-bot-master\\node_modules\\steam-user\\components\\classes\\HandlerManager.js:36:12)\n' +
    '    at SteamUser._handleMessage (D:\\joinclient\\csgo-commend-bot-master\\node_modules\\steam-user\\components\\messages.js:555:24)'
}
 [myassountsg11] Logged onto Steam - GC Time: 2020-9-7 0:15:43
 [myassountsg12] Logged onto Steam - GC Time: 2020-9-7 0:15:43
 [myassountsg11] Authenticated with target server with ticket 2145837408
 [myassountsg12] Authenticated with target server with ticket 924236264
 [myassountsg13] Logged onto Steam - GC Time: 2020-9-7 0:15:47
 [myassountsg10] Logged onto Steam - GC Time: 2020-9-7 0:15:47
 [myassountsg13] Authenticated with target server with ticket 1659270958
 [myassountsg10] Authenticated with target server with ticket 1273175303
 [myassountsg11] Failed to commend (2/5) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (D:\\joinclient\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:531:17)\n' +
    '    at processTimers (internal/timers.js:475:7)'
}
 [myassountsg12] Failed to commend (3/5) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (D:\\joinclient\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:531:17)\n' +
    '    at processTimers (internal/timers.js:475:7)'
}
 [myassountsg13] Failed to commend (4/5) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (D:\\joinclient\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:531:17)\n' +
    '    at processTimers (internal/timers.js:475:7)'
}
 [myassountsg10] Failed to commend (5/5) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (D:\\joinclient\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:531:17)\n' +
    '    at processTimers (internal/timers.js:475:7)'
}
 Chunk 1/3 finished with 0 successful commends and 5 failed commends
 Waiting 300000ms...

PS D:\joinclient\csgo-commend-bot-master> node index.js
 Checking for new update...
 Up to date!
 Checking protobufs...
 Found protobufs
 Opening database...
 There are a total of 15 operational accounts
 Parsing target account...
 Not enough accounts available, got 11/15
PS D:\joinclient\csgo-commend-bot-master> node index.js
 Checking for new update...
 Up to date!
 Checking protobufs...
 Found protobufs
 Opening database...
 There are a total of 15 operational accounts
 Parsing target account...
 Not enough accounts available, got 11/15

**Config**
```
{
	"commend": {
		"friendly": 5,
		"teaching": 10,
		"leader": 15
	},
	"report": {
		"aimbot": 10,
		"wallhack": 10,
		"speedhack": 10,
		"teamharm": 10,
		"abusive": 10
	},
	"account": {
		"username": "USER_XXXX",
		"password": "PASSWORD_XXXXXXXXXX",
		"sharedSecret": ""
	},
	"fetcher": {
		"username": "Account",
		"password": "Password",
		"sharedSecret": "",
		"maxTries": 10,
		"tryDelay": 2500,
		"askSteamGuard": true
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/id/naykkkurl/",
	"serverID": "[G:1:3506192]",
	"matchID": "0",
	"perChunk": 5,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"showCommends": false,
	"autoReportOnMatchEnd": false,
	"switchServerAfterChunks": 5,
	"protocol": "Auto",
	"steamWebAPIKey": "E27BD3B4C323XXXXXXXXXXXXC0D392E",
	"disableUpdateCheck": false
}

```
![7l7iq7St_I4](https://user-images.githubusercontent.com/70862179/92335709-30a96f00-f0a2-11ea-9cbb-454b57eddd6d.jpg)

**Version**
- NodeJS: v12.9.1
- Script version: 2.10.0

**Comment by BeepIsla** [comment]
Next time read the pinned issue #593

While the error is entirely unrelated to the pinned issue regardless of what you do you will not be able to use it due to it being patched.
