### ISSUE TITLE
Hi i have a very big error when try to put some comms .

### ISSUE THREAD

**Issue by PtmSugePula** [BeepIsla/csgo-commend-bot#614]
https://gyazo.com/ff67393f189b9862ae0c00a77b339ea6

**Comment by PtmSugePula** [comment]
IDK whats the problem .

**Comment by BeepIsla** [comment]
1. Read the README

2. Read the example config

3. Read the error

4. https://github.com/BeepIsla/csgo-commend-bot/issues/593
