### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by 10345** [BeepIsla/csgo-commend-bot#615]
**Detailed bug description**

**Error**
Error: Failed to log in within given 60000ms
    at Timeout._onTimeout (C:\Users\gonia\Desktop\csgo-commend-bot-bc8435003e92db917a6c87dc700a0ec56f867802\helpers\account.js:52:12)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) Promise {
  <rejected> Error: Failed to log in within given 60000ms
      at Timeout._onTimeout (C:\Users\gonia\Desktop\csgo-commend-bot-bc8435003e92db917a6c87dc700a0ec56f867802\helpers\account.js:52:12)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)
}
A full error log or screenshot.
https://user-images.githubusercontent.com/72657798/95656380-3e716a80-0b0e-11eb-9d6b-f8af020fcd97.png

**Config**
{
	"commend": {
		"friendly": 5,
		"teaching": 5,
		"leader": 5
	},
	"report": {
		"aimbot": 10,
		"wallhack": 10,
		"speedhack": 10,
		"teamharm": 10,
		"abusive": 10
	},
	"account": {
		"username": "urvizlegit27",
		"password": "i write here my password",
		"sharedSecret": ""
	},
	"fetcher": {
		"username": "",
		"password": "",
		"sharedSecret": "",
		"maxTries": 10,
		"tryDelay": 2500,
		"askSteamGuard": true
	},
	"proxy": {
		"enabled": false,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "SERVER",
	"target": "https://steamcommunity.com/id/pwneddog/",
	"serverID": "auto",
	"matchID": "0",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"switchServerAfterChunks": 5,
	"steamWebAPIKey": "i write here my api code",
	"disableUpdateCheck": false
Your "config.json" - Censor your API Key and account details
```

**Version**
- NodeJS: `v12.18.3` (You can find this using `node -v`)
- Script version: `2.6.1` (You can find this in **your** `package.json` file under `version`)

**Additional information**
Add any other potentially useful information about your issue here.

**Comment by BeepIsla** [comment]
https://github.com/BeepIsla/csgo-commend-bot/issues/593
